import type { Metadata } from 'next'
import { StockImage, buildMetadata, ArticleLayout, EmailCapture, RelatedLinks, CrossPortfolioCard , AffiliateDisclosure, ArticleSourcesList } from '@carloOS/ui'
import { buildArticleSchema } from '@carloOS/ui'
import { ArticleByline, DropCap, CalloutBox } from '@carloOS/ui'

const SOURCES = [
  { label: "Trichopsis pumila — Seriously Fish species profile", url: "https://www.seriouslyfish.com/species/trichopsis-pumila/", publisher: "Seriously Fish" },
  { label: "Trichopsis pumila — FishBase species record", url: "https://www.fishbase.se/summary/Trichopsis-pumila.html", publisher: "FishBase" },
  { label: "Ladich, F. & Myrberg, A.A. Jr. Agonistic Behavior and Acoustical Communication in the Pygmy Gourami Trichopsis pumilus. Ethology, 1998.", publisher: "Ethology" },
  { label: "Riehl, R. & Baensch, H.A. Aquarium Atlas Vol 1. Baensch, 1991.", publisher: "Baensch" },
]
export const metadata: Metadata = buildMetadata({ siteId: 'fish-com', title: 'Sparkling Gourami Care Guide — The Croaking Nano Fish | Fish.com', description: "Sparkling gouramis are tiny labyrinth fish under 1.5 inches that audibly croak. Ideal for planted nano tanks with gentle flow and calm tankmates.", path: '/species/sparkling-gourami', type: 'article' })
const schema = buildArticleSchema({ siteId: 'fish-com', title: 'Sparkling Gourami Care Guide', description: 'Care, croaking behavior, and breeding for Trichopsis pumila, the sparkling gourami.', url: 'https://fish.com/species/sparkling-gourami', imageUrl: '', authorName: 'Fish.com Editorial', publishedAt: '2026-06-01T00:00:00Z', modifiedAt: '2026-06-01T00:00:00Z' })
export default function SparklingGouramiPage() {
  return (
    <ArticleLayout siteId="fish-com"
      hero={{ title: 'Sparkling Gourami Care Guide', subtitle: "Trichopsis pumila — the sparkling or pygmy gourami is a jewel-like labyrinth fish under an inch and a half long, with iridescent blue-green spangling across an amber body and striking red-rimmed eyes. Most remarkably, it produces an audible croaking sound. It is a perfect centerpiece for a quiet, well-planted nano aquarium.", category: 'Species Guide', authorName: 'Fish.com Editorial', publishedAt: 'June 2026', readTime: '7 min' }}
      breadcrumbs={[{ name: 'Home', href: '/' }, { name: 'Species', href: '/species' }, { name: 'Sparkling Gourami', href: '/species/sparkling-gourami' }]}
      schema={schema}
      relatedLinks={[{ title: "Species Hub", href: "/species", category: "Species" }, { title: "Dwarf Gourami", href: "/species/dwarf-gourami", category: "Species Guide" }, { title: "Pearl Gourami", href: "/species/pearl-gourami", category: "Species Guide" }, { title: "Nano Tank Setup", href: "/setup/nano-tank-setup", category: "Tank Setup" }]}
      sidebar={<>
        <div className="bg-brand-surface border border-brand-border rounded-xl p-5">
          <div className="text-2xs font-bold tracking-eyebrow uppercase text-brand-text-light mb-3">Quick Stats</div>
          {[['Scientific name', 'Trichopsis pumila'], ['Adult size', '1.25–1.5 inches'], ['Temperature', '76–82°F'], ['pH', '6.0–7.5 (soft preferred)'], ['Tank size', '10 gallons'], ['Temperament', 'Peaceful, shy'], ['Lifespan', '4–5 years']].map(([k, v]) => (
            <div key={k} className="flex justify-between py-1.5 border-b border-brand-border text-xs last:border-0">
              <span className="text-brand-text-light">{k}</span><span className="font-bold text-brand-dark text-right max-w-[55%]">{v}</span>
            </div>
          ))}
        </div>
        <RelatedLinks title="Related Guides" links={[{ label: 'Pearl Gourami', href: '/species/pearl-gourami' }, { label: 'Dwarf Gourami', href: '/species/dwarf-gourami' }, { label: 'Nano Tank Setup', href: '/setup/nano-tank-setup' }]} />
            <CrossPortfolioCard currentSite="fish-com" contentType="species" variant="sidebar" />
        <EmailCapture variant="sidebar" siteId="fish-com" title="The Weekly Tank" subtitle="Species spotlights every Thursday." source="species-sparkling-gourami" />
      </>}
    >
      <div className="carloOS-article">
        <ArticleByline siteName="Fish.com Editorial" publishedAt="2026-06-01T00:00:00Z" updatedAt="2026-06-01T00:00:00Z" reviewedBy="Editorial team" />
        <StockImage manifestKey="fish-com:species-sparkling-gourami" aspect="16:9" variant="inline" caption="A sparkling gourami in a home aquarium." priority />

        <h2>The Fish That Croaks</h2>
        <DropCap>The sparkling gourami's most famous trait is that it produces an audible croaking or purring noise, generated by specialized pectoral-fin tendons that snap against the body during courtship, territorial disputes, and general excitement. In a quiet room, the sound from a confident colony is clearly perceptible from outside the tank — a genuinely unusual experience among aquarium fish. The croaking is most pronounced when the fish feel secure, which is itself a useful welfare indicator: a silent, hiding sparkling gourami is usually a stressed one, while an audible, active group signals good conditions.</DropCap>
        <p>Like the betta and pearl gourami, this is a labyrinth fish that breathes atmospheric air at the surface, so it needs unobstructed surface access and warm, humid air above the waterline. A lid that traps cold room air directly over the water can chill the gulped air and harm the labyrinth organ.</p>

        <h2>A True Nano Species</h2>
        <p>At well under an inch and a half, the sparkling gourami is small enough that a planted 10-gallon tank can comfortably house a small group. It is shy and easily intimidated, so it should not be kept with boisterous or fin-nipping tankmates. The ideal setup is a quiet, densely planted tank with subdued lighting, plenty of cover, gentle filtration, and calm companions such as small rasboras, pygmy corydoras, or dwarf shrimp. In a busy community tank it will simply hide and rarely show its colors or croak.</p>

        <CalloutBox variant="info" title="A group brings them out">
          Sparkling gouramis are bolder and more vocal in a group of four to six. A single specimen often stays hidden; a small colony interacts, displays, and croaks far more readily.
        </CalloutBox>

        <h2>Water and Setup</h2>
        <p>Soft, slightly acidic, warm water best mimics the still, vegetation-choked ditches and rice paddies the species inhabits in Southeast Asia. Tannins from driftwood or Indian almond leaves are appreciated and intensify color. Because the fish comes from near-stagnant water, strong filter current is stressful — use gentle flow such as a sponge filter, which also doubles as safe filtration around any fry. Floating plants provide both shade and anchoring sites for bubble nests.</p>

        <h2>Bubble-Nest Breeding</h2>
        <p>Sparkling gouramis are bubble-nest builders, though some populations nest near the surface among plants and others build under broad leaves or in caves. The male tends the nest and guards the eggs and fry. Spawning is often preceded by especially intense croaking. Fry are tiny and require infusoria and other very fine first foods before graduating to baby brine shrimp. A species-only or heavily planted shrimp-safe tank gives the best fry survival.</p>
        <AffiliateDisclosure variant="inline" siteId="fish-com" />
          <div style={{ background: 'var(--brand-surface, #f7fbfd)', border: '1px solid var(--brand-border, #d4e5ee)', borderRadius: '10px', padding: '20px', margin: '32px 0 24px' }}>
          <div style={{ fontSize: '13px', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.05em', color: 'var(--brand-text-mid, #4a6573)', marginBottom: '8px' }}>Sparkling Gourami — Tank Setup</div>
          <p style={{ fontSize: '14px', margin: '0 0 12px', color: 'var(--brand-text-mid, #4a6573)', lineHeight: 1.55 }}>Browse nano tanks, gentle filters, heaters, live plants, and food sized for sparkling gourami care. Fish.com earns an affiliate commission on qualifying purchases — at no extra cost to you. Commission does not influence editorial content above.</p>
          <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
            <a href="/go/amazon-brand/sparkling%20gourami%20nano%20tank%20setup?s=species-sparkling-gourami" rel="sponsored noopener" style={{ display: 'inline-block', padding: '9px 16px', background: 'var(--brand-dark, #232f3e)', color: 'white', fontSize: '13px', fontWeight: 700, textDecoration: 'none', borderRadius: '6px' }}>Shop Sparkling Gourami Setup on Amazon →</a>
            <a href="/go/chewy-brand/sparkling%20gourami%20nano%20tank%20setup?s=species-sparkling-gourami" rel="sponsored noopener" style={{ display: 'inline-block', padding: '9px 16px', background: 'var(--brand-primary, #1e90ff)', color: 'white', fontSize: '13px', fontWeight: 700, textDecoration: 'none', borderRadius: '6px' }}>Shop on Chewy →</a>
          </div>
        </div>
        <ArticleSourcesList sources={SOURCES} />
      </div>
    </ArticleLayout>
  )
}
