import type { Metadata } from 'next'
import { buildMetadata, ArticleLayout, ArticleByline, CrossPortfolioCard, EmailCapture, RelatedLinks, TableOfContents, FAQAccordion, AffiliateDisclosure, ShopCtas } from '@carloOS/ui'
import { buildArticleSchema, SchemaScript } from '@carloOS/ui'

export const metadata: Metadata = buildMetadata({
  siteId: 'horses-com',
  title: "Winter Horse Care — Water, Forage, Shelter, and Footing",
  description:
    "Reference guide to winter horse care: keeping water unfrozen and intake up, feeding for warmth, shelter and blanketing decisions, and managing ice and mud.",
  path: '/care/winter-care',
  type: 'article',
})

const articleSchema = buildArticleSchema({
  siteId: 'horses-com',
  title: "Winter Horse Care — Water, Forage, Shelter, and Footing",
  description:
    "Reference guide to winter horse care: keeping water unfrozen and intake up, feeding for warmth, shelter and blanketing decisions, and managing ice and mud.",
  url: 'https://horses.com/care/winter-care',
  imageUrl: '',
  authorName: 'Horses.com Editorial',
  publishedAt: '2026-06-01T00:00:00Z',
  modifiedAt: '2026-09-04T00:00:00Z',
})

const FAQS = [
  {
    question: "Why is water so important in winter?",
    answer:
      "Horses drink less when water is icy, and reduced intake combined with dry winter forage is a leading cause of impaction colic. Keeping water unfrozen and offering slightly warmed water encourages drinking and is one of the most important winter management tasks for preventing colic.",
    answerText:
      "Cold water reduces drinking, and low intake plus dry forage causes impaction colic. Unfrozen, slightly warmed water keeps intake up and is key to preventing winter colic.",
  },
  {
    question: "Should I feed more hay or more grain to keep a horse warm in winter?",
    answer:
      "More hay. Heat is generated by microbial fermentation of fiber in the hindgut, so increasing forage warms a horse more effectively than feeding grain. Free-choice or near-continuous good hay is the best way to help a horse maintain body heat overnight in cold weather.",
    answerText:
      "More hay -- fiber fermentation in the hindgut generates the heat, so increasing forage warms a horse far better than grain. Near-continuous hay is ideal.",
  },
  {
    question: "Can a horse stay outside all winter?",
    answer:
      "Many healthy, unclipped horses winter outside comfortably given shelter from wind and wet, plenty of forage, and unfrozen water. The essentials are protection from the elements (a run-in shed or windbreak), enough hay to fuel internal heat, and water -- not necessarily a barn or a blanket.",
    answerText:
      "Yes, many healthy unclipped horses winter outside fine with shelter from wind and wet, ample forage, and unfrozen water -- not necessarily a barn or blanket.",
  },
]

export default function WinterCarePage() {
  return (
    <>
      <SchemaScript schema={articleSchema} />
      <ArticleLayout
        siteId="horses-com"
        contentType="care"
        relatedLinks={[
          { title: 'Horse Care Hub', href: '/care', category: 'Horse Care' },
          { title: 'Horse Blanketing Guide', href: '/care/blanketing' },
          { title: 'Deworming Program', href: '/care/deworming-program' },
          { title: 'Water Requirements', href: '/nutrition/water-requirements' },
        ]}
        hero={{
          title: "Winter Horse Care",
          subtitle:
            "Horses are well built for cold, but winter brings specific management challenges: water that freezes and intake that drops (raising colic risk), forage that must do double duty as fuel for warmth, and footing that turns to ice and mud. Get water, forage, and shelter right and most horses winter comfortably with little fuss. This is reference material to inform your winter routine.",
          category: "Horse Care",
          authorName: 'Horses.com Editorial',
          authorAvatar: '☘',
          publishedAt: 'June 2026',
          readTime: "10 min",
        }}
        breadcrumbs={[
          { name: 'Home', href: '/' },
          { name: "Care", href: "/care" },
          { name: "Winter Care", href: '/care/winter-care' },
        ]}
        sidebar={<>
          <TableOfContents items={[
            { label: "Water First", href: "#water" },
            { label: "Forage as Fuel", href: "#forage" },
            { label: "Shelter and Blanketing", href: "#shelter" },
            { label: "Footing, Ice, and Mud", href: "#footing" },
            { label: "Monitoring Condition", href: "#condition" },
            { label: "Winter-Care Kit", href: "#kit" },
            { label: "FAQ", href: "#faq" },
            { label: "References", href: "#references" },
          ]} />
          <RelatedLinks
            title="Related Reading"
            links={[
              { label: "Blanketing Guide", href: "/care/blanketing" },
              { label: "Best Winter Horse Blankets", href: "/reviews/best-winter-horse-blankets" },
              { label: "Water Requirements", href: "/nutrition/water-requirements" },
              { label: "Equine Colic", href: "/health/colic" },
            ]}
          />
          <CrossPortfolioCard currentSite="horses-com" contentType="care" variant="sidebar" />
          <EmailCapture
            variant="sidebar"
            siteId="horses-com"
            title="Practical Horse Reference"
            subtitle="Citation-anchored equine reference articles."
            source="care-winter"
          />
        </>}
      >
        <div className="carloOS-article">
          <ArticleByline
            siteName="Horses.com Editorial"
            publishedAt="2026-06-01"
            updatedAt="2026-09-04"
            reviewedBy="Editorial team"
          />

          {/* Under-hero capture — source must end in under-hero so it always renders. */}
          <div className="mb-8">
            <p className="mb-1 text-2xs font-bold uppercase tracking-eyebrow text-brand-primary">
              Keep the winter-care checklist
            </p>
            <h2 className="mb-2 font-display text-xl font-bold text-brand-dark">
              Horse winter-care checklist
            </h2>
            <p className="mb-3 text-sm leading-relaxed text-brand-text-mid">
              Email the everyday kit — a tank heater so water stays unfrozen,
              grit or sand for ice around gates and troughs, plus snow pads
              or studs when the farrier conversation is about working horses
              in winter. Educational checklist, not a diagnosis. No spam.
            </p>
            <EmailCapture
              variant="inline"
              siteId="horses-com"
              title="Horse winter-care checklist"
              subtitle="Email the tank-heater, ice-grit, snow-pad, and stud order. No spam."
              ctaText="Email my winter-care checklist"
              source="care-winter-care-under-hero"
            />
          </div>

          <h2 id="water">Water First</h2>
          <p>The biggest winter health risk is reduced water intake. Horses drink less when water is icy, and dehydration combined with dry winter forage is a leading cause of impaction colic. Keep water available and unfrozen with tank heaters or frequent breaking and refilling, and offer slightly warmed water, which horses drink more readily in cold weather. A horse needs roughly 5 to 10 gallons or more a day even in winter; monitor that troughs are actually being drunk down.</p>

          <h2 id="forage">Forage as Fuel</h2>
          <p>Forage is the horse&apos;s internal furnace -- the microbial fermentation of fiber in the hindgut generates heat. In cold weather, increasing hay (rather than grain) is the most effective way to help a horse stay warm. Free-choice or near-continuous good-quality hay keeps the fermentation going and the horse warm through the night. As a rough rule, intake needs rise as temperatures fall below the horse&apos;s comfort zone, so winter hay bills climb.</p>

          <h2 id="shelter">Shelter and Blanketing</h2>
          <p>What horses most need is shelter from wind and wet, which strip the coat&apos;s insulation, rather than from cold air. A three-sided run-in shed, a windbreak, or tree cover lets a horse with a full coat and forage cope with severe cold. Blanketing is justified for clipped, old, sick, or underweight horses, or where shelter is lacking in prolonged cold and wet -- but an unclipped, sheltered, well-fed horse often needs no rug. See the blanketing guide.</p>

          <h2 id="footing">Footing, Ice, and Mud</h2>
          <ul>
            <li><strong>Manage ice</strong> around gates, water, and high-traffic areas with grit or sand to prevent slips and injuries.</li>
            <li><strong>Address mud</strong> with hardstanding or a sacrifice area, since standing in deep mud causes mud fever and foot problems.</li>
            <li><strong>Adjust shoeing</strong> with your farrier -- snow pads or studs for working horses, or pulling shoes for wintered-off horses.</li>
            <li><strong>Keep feet picked out</strong> as snow and mud pack the hooves and hide problems.</li>
          </ul>

          <h2 id="condition">Monitoring Condition</h2>
          <p>A thick winter coat hides weight loss, so a horse can quietly drop condition under a fluffy or blanketed exterior. Put hands on the horse regularly -- feel the ribs, topline, and hindquarters rather than relying on the eye -- and use body condition scoring through the winter. Catching a horse losing condition early lets you increase forage or investigate before spring reveals a thin horse under the coat.</p>

          <h2 id="kit">Winter-Care Kit</h2>
          <p>Everyday physical supplies that match the water and footing copy above — a tank heater so troughs stay unfrozen, grit or sand for ice around gates and high-traffic areas, and snow pads or studs when the farrier conversation is about working horses in winter. These are not treatments for impaction colic, mud fever, or a horse that is losing condition under a winter coat; reduced drinking, persistent mud-related skin trouble, or unexplained weight loss belongs with your veterinarian, not a heater or a bag of grit. Blanketing decisions live on the blanketing guide. This page does not claim hands-on testing.</p>

          <AffiliateDisclosure variant="inline" siteId="horses-com" />

          {/* Money path — live amazon-brand search hops (winter-care kit).
              ShopCtas hides empty Chewy; never href="#" or PLACEHOLDER.
              Category searches only — everyday physical supplies matching
              on-page tank-heater / grit / snow-pad / stud copy, not colic
              or mud-fever diagnosis hops. Blankets stay on /care/blanketing. */}
          <div className="my-6 p-5 border border-brand-border rounded-xl bg-brand-surface not-prose">
            <div className="text-2xs font-bold uppercase tracking-eyebrow text-brand-primary mb-3">
              Shop the winter-care kit
            </div>
            <p className="text-sm text-brand-text-mid mb-4 leading-relaxed">
              These Amazon category searches match the on-page water and
              footing copy — a tank heater, ice grit, snow pads, and horse
              shoe studs. Everyday physical supplies only. They are not a
              ranked product list, they are not treatments for colic, mud
              fever, or weight loss, and they do not replace a veterinarian.
              Horses.com earns a commission on qualifying purchases at no
              extra cost to you. Empty Chewy buttons stay hidden.
            </p>
            <div className="flex flex-col gap-3">
              <ShopCtas
                amazonHref="/go/amazon-brand/horse+tank+heater?s=care-winter-care"
                amazonLabel="Browse horse tank heaters on Amazon →"
              />
              <ShopCtas
                amazonHref="/go/amazon-brand/ice+grit?s=care-winter-care"
                amazonLabel="Browse ice grit on Amazon →"
              />
              <ShopCtas
                amazonHref="/go/amazon-brand/horse+snow+pads?s=care-winter-care"
                amazonLabel="Browse horse snow pads on Amazon →"
              />
              <ShopCtas
                amazonHref="/go/amazon-brand/horse+shoe+studs?s=care-winter-care"
                amazonLabel="Browse horse shoe studs on Amazon →"
              />
            </div>
          </div>

          <h2 id="faq">Frequently Asked Questions</h2>
          <FAQAccordion items={FAQS} />

          <h2 id="references">References</h2>
          <ol className="text-sm text-brand-text-mid">
            <li>National Research Council. Nutrient Requirements of Horses, 6th ed., National Academies Press, 2007 (cold-weather energy needs).</li>
            <li>American Association of Equine Practitioners. “Winter Care” owner resources. aaep.org.</li>
            <li>Cohen ND, et al. Case-control studies on colic risk factors (water intake, weather). JAVMA.</li>
          </ol>
        </div>
      </ArticleLayout>
    </>
  )
}
