import type { Metadata } from 'next'
import { buildMetadata } from '@carloOS/ui'

export const metadata: Metadata = buildMetadata({
  siteId: 'askthevet',
  title: 'Editorial Standards',
  description: 'How AskTheVet generates triage guidance and the rules our AI follows.',
  path: '/legal/editorial-standards',
})

export default function Page() {
  return (
    <article className="max-w-2xl mx-auto px-6 py-12 prose">
      <h1>Editorial Standards</h1>
      <p>
        AskTheVet is a consumer triage tool, not a veterinary clinic. We do not employ
        veterinarians and we never claim to. The triage assessments shown on this site are
        generated by a large-language model with a single system prompt that:
      </p>
      <ul>
        <li>Never diagnoses, never prescribes doses.</li>
        <li>Routes any life-threatening symptom to <em>urgent_er</em> by default.</li>
        <li>Treats exotic species (reptile, bird, ferret, fish) more conservatively because they hide illness.</li>
        <li>Surfaces concrete next steps, not vague reassurance.</li>
        <li>Always includes a disclaimer that this is not veterinary advice.</li>
      </ul>
      <p>
        Our system prompt is versioned in the codebase. Monetization routes (telehealth,
        insurance, products, directory) are selected after the triage decision and never
        change the triage level.
      </p>
    </article>
  )
}
