import { MetadataRoute } from 'next'

/**
 * Auto-generated by scripts/regenerate-sitemaps.mjs.
 * To refresh after adding/removing pages, re-run:
 *   node scripts/regenerate-sitemaps.mjs
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()

  return [
    { url: 'https://ferrets.com', lastModified: now, changeFrequency: 'daily', priority: 1.00 },
    { url: 'https://ferrets.com/care', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://ferrets.com/directory/rescues', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://ferrets.com/disclosure', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://ferrets.com/find-a-vet', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://ferrets.com/states', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
  ]
}
