/**
 * Vivarium-build hub page — Lizard.com
 *
 * Lists all species-class vivarium builds generated by
 * /builds/[slug]/page.tsx. Each entry shows a difficulty badge,
 * scientific name, and the build's hero subtitle. High Amazon affiliate
 * intent: keepers arriving here are sourcing equipment to set up a new
 * enclosure.
 */

import type { Metadata } from 'next'
import Link from 'next/link'
import { buildMetadata, EmailCapture, StockImage } from '@carloOS/ui'
import { VivariumBuilds, difficultyLabel } from '../../data/vivarium-builds'

export const metadata: Metadata = buildMetadata({
  siteId: 'lizard-com',
  title: 'Reptile Vivarium Build Guides — Step-by-Step | Lizard.com',
  description:
    'Step-by-step vivarium build guides: bearded dragon, leopard gecko, ball python, crested gecko, corn snake. Equipment by category, cited sources.',
  path: '/builds',
})

export default function VivariumBuildsHubPage() {
  return (
    <>
      <div
        className="relative z-10 px-container-sm sm:px-container py-16"
        style={{ background: 'linear-gradient(135deg, #0D1A0D, #080C08)' }}
      >
        <div className="flex items-center gap-2.5 mb-5">
          <span className="w-6 h-0.5 bg-brand-primary" />
          <span className="text-2xs font-bold tracking-eyebrow uppercase text-brand-primary">
            Vivarium Builds
          </span>
        </div>
        <h1
          className="font-display font-bold text-brand-white tracking-tight leading-tight mb-4"
          style={{ fontSize: 'clamp(28px, 5vw, 52px)' }}
        >
          Species-Class Vivarium Build Guides
        </h1>
        <p
          className="text-lg font-light leading-relaxed max-w-2xl"
          style={{ color: 'rgba(238,240,228,0.55)' }}
        >
          Five complete, step-by-step vivarium setup guides — bearded dragon, leopard gecko,
          ball python, crested gecko, and corn snake. Equipment recommendations are by category
          with example products only; sourced from Mader&rsquo;s Reptile and Amphibian Medicine
          and Surgery (RAMS), the Journal of Herpetological Medicine and Surgery, ARAV
          continuing-education materials, and AAV reference texts.
        </p>
      </div>

      <div className="relative z-10 px-container-sm sm:px-container pt-8">
        <StockImage manifestKey="lizard-com:category-builds" aspect="16:9" variant="wide" priority />
      </div>

      <div className="relative z-10 px-container-sm sm:px-container py-14">
        <div className="grid sm:grid-cols-2 gap-4 max-w-content-wide mx-auto">
          {VivariumBuilds.map((b) => (
            <Link
              key={b.slug}
              href={`/builds/${b.slug}`}
              className="block rounded-lg p-5 no-underline hover:-translate-y-1 transition-all duration-200"
              style={{
                background: 'rgba(255,255,255,0.03)',
                border: '1px solid rgba(255,255,255,0.07)',
              }}
            >
              <div className="flex items-start gap-3">
                <div
                  style={{
                    fontFamily: 'var(--font-mono)',
                    fontSize: '11px',
                    fontWeight: 700,
                    color: 'var(--brand-primary)',
                    background: 'rgba(122,181,42,0.12)',
                    border: '1px solid rgba(122,181,42,0.25)',
                    padding: '4px 8px',
                    borderRadius: '4px',
                    letterSpacing: '0.06em',
                    textTransform: 'uppercase',
                    flexShrink: 0,
                  }}
                >
                  {difficultyLabel(b.suitableFor)}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="text-2xs font-bold tracking-eyebrow uppercase text-brand-primary mb-2">
                    {b.buildName}
                  </div>
                  <div className="font-display font-bold text-brand-white text-base mb-1.5">
                    {b.speciesName}
                  </div>
                  <div
                    className="text-xs"
                    style={{
                      color: 'rgba(238,240,228,0.45)',
                      fontStyle: 'italic',
                      marginBottom: '8px',
                    }}
                  >
                    {b.scientificName}
                  </div>
                  <div className="text-xs" style={{ color: 'rgba(238,240,228,0.55)' }}>
                    {b.shortDescription}
                  </div>
                </div>
              </div>
            </Link>
          ))}
        </div>
      </div>

      <div
        className="relative z-10 px-container-sm sm:px-container py-12"
        style={{ background: '#0D1A0D', borderTop: '1px solid rgba(122,181,42,0.1)' }}
      >
        <EmailCapture
          variant="inline"
          siteId="lizard-com"
          ctaText="Subscribe Free"
          source="builds-hub"
        />
      </div>

      <section className="border-t border-brand-border bg-brand-surface px-container-sm sm:px-container py-10">
        <h2 className="font-display font-bold text-brand-dark text-lg mb-4">
          All Vivarium Build Guides
        </h2>
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-x-6 gap-y-2">
          {VivariumBuilds.map((b) => (
            <Link
              key={b.slug}
              href={`/builds/${b.slug}`}
              className="text-sm text-brand-primary no-underline hover:underline"
            >
              {b.speciesName} Build
            </Link>
          ))}
        </div>
      </section>
    </>
  )
}
