import { MetadataRoute } from 'next'

/**
 * Auto-generated by scripts/regenerate-sitemaps.mjs.
 * To refresh after adding/removing pages, re-run:
 *   node scripts/regenerate-sitemaps.mjs
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()

  return [
    { url: 'https://petfoods.com', lastModified: now, changeFrequency: 'daily', priority: 1.00 },
    { url: 'https://petfoods.com/brands', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://petfoods.com/disclosure', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://petfoods.com/ingredients', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://petfoods.com/life-stage', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://petfoods.com/recalls', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
  ]
}
