import type { Metadata } from 'next'
import Link from 'next/link'
import { buildMetadata } from '@carloOS/ui'

export const metadata: Metadata = buildMetadata({
  siteId: 'dogpicture',
  title: 'Terms of Use | DogPicture.com',
  description: 'DogPicture.com terms of use.',
  path: '/legal/terms',
})

export default function TermsPage() {
  return (
    <div className="px-container-sm sm:px-10 py-16 max-w-content mx-auto">
      <nav className="text-xs text-brand-text-light flex gap-2 mb-8">
        <Link href="/" className="hover:text-brand-primary no-underline">Home</Link>
        <span>›</span>
        <span className="text-brand-text-mid">Terms of Use</span>
      </nav>
      <h1 className="font-display font-black text-brand-text-dark text-3xl tracking-tight mb-2">
        Terms of Use
      </h1>
      <p className="text-sm text-brand-text-light mb-10">Last updated: May 2026</p>

      <div className="carloOS-article">
        <h2>Acceptance of Terms</h2>
        <p>By using DogPicture.com, you agree to these Terms of Use. If you do not agree, do not use the site.</p>

        <h2>Your Account & Content</h2>
        <p>
          When you upload a photo, you confirm that you own the rights to that image and grant
          DogPicture.com a non-exclusive license to use the image solely to generate, deliver, and
          fulfill your portrait order. We do not use uploaded photos to train external AI models.
          You may request deletion of your uploaded source photo at any time by emailing
          <a href="mailto:hello@dogpicture.com"> hello@dogpicture.com</a>.
        </p>

        <h2>AI-Generated Output</h2>
        <p>
          Portraits are generated by third-party AI image models (OpenAI&apos;s gpt-image-1 or
          dall-e-3, depending on availability). The output is a creative interpretation of your
          source photo, not a photograph. You own the right to use the generated portrait for
          personal, non-commercial purposes (printing, gifting, social media). Commercial use
          requires written permission.
        </p>

        <h2>Payment & Fulfillment</h2>
        <p>
          Payments are processed by Stripe. Physical products are printed and shipped by Printify.
          See our <Link href="/legal/refund-policy">Refund Policy</Link> for refund and replacement
          terms.
        </p>

        <h2>Intellectual Property</h2>
        <p>
          All website content, branding, code, and the DogPicture name are owned by the operating
          entity and protected by copyright law.
        </p>

        <h2>Acceptable Use</h2>
        <p>You agree not to upload images that:</p>
        <ul>
          <li>Contain identifiable humans without their consent</li>
          <li>Are sexual, violent, or otherwise prohibited by OpenAI&apos;s usage policies</li>
          <li>Violate any third-party copyright or trademark</li>
        </ul>
        <p>We reserve the right to refuse service and refund any order that violates these terms.</p>

        <h2>Disclaimer of Warranties</h2>
        <p>
          DogPicture.com is provided &ldquo;as is&rdquo; without warranties of any kind. AI output is
          inherently variable — we do not guarantee a specific likeness, style, or quality outcome
          for any given input photo. Previews are shown before payment so you can decide.
        </p>

        <h2>Limitation of Liability</h2>
        <p>
          To the fullest extent permitted by law, the operating entity shall not be liable for any
          indirect, incidental, special, consequential, or punitive damages arising from your use
          of DogPicture.com.
        </p>

        <h2>Contact</h2>
        <p>Legal questions: <a href="mailto:legal@dogpicture.com">legal@dogpicture.com</a></p>
      </div>

      <div className="mt-12 pt-8 border-t border-brand-border flex gap-6 text-sm">
        <Link href="/legal/refund-policy" className="text-brand-primary hover:underline">Refund Policy</Link>
        <Link href="/legal/privacy-policy" className="text-brand-primary hover:underline">Privacy Policy</Link>
      </div>
    </div>
  )
}
