import { MetadataRoute } from 'next'
import { States } from '../data/states'
import { Symptoms } from '../data/symptoms'
import { Medications } from '../data/medications'
import { Diagnostics } from '../data/diagnostics'

/**
 * Auto-generated by scripts/regenerate-sitemaps.mjs, with manual additions
 * for the programmatic /find-a-vet/[state] routes (51 entries: 50 states + DC),
 * the /symptoms/[slug] symptom-triage routes (30 entries), the
 * /medications/[slug] medication overview routes (12 entries), and the
 * /diagnostics/[slug] diagnostic-test deep-dive routes (8 entries).
 * To refresh after adding/removing pages, re-run:
 *   node scripts/regenerate-sitemaps.mjs
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()

  const stateRoutes: MetadataRoute.Sitemap = States.map((s) => ({
    url: `https://vets.co/find-a-vet/${s.slug}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    priority: 0.70,
  }))

  const symptomRoutes: MetadataRoute.Sitemap = Symptoms.map((s) => ({
    url: `https://vets.co/symptoms/${s.slug}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    // ER NOW pages skew higher: highest-intent informational queries.
    priority: s.urgencyTriage === 'ER NOW' ? 0.85 : 0.75,
  }))

  const medicationRoutes: MetadataRoute.Sitemap = Medications.map((m) => ({
    url: `https://vets.co/medications/${m.slug}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    // High commercial intent — owners searching specific drug names.
    priority: 0.80,
  }))

  const diagnosticRoutes: MetadataRoute.Sitemap = Diagnostics.map((d) => ({
    url: `https://vets.co/diagnostics/${d.slug}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    // Diagnostic workups ($300-2,000) are a primary pet-insurance buyer trigger.
    priority: 0.80,
  }))

  return [
    { url: 'https://vets.co', lastModified: now, changeFrequency: 'daily', priority: 1.00 },
    { url: 'https://vets.co/breeds/beagle-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/chihuahua-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/french-bulldog-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/german-shepherd-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/golden-retriever-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/husky-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/labrador-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/pomeranian-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/yorkshire-terrier-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/editorial-standards', lastModified: now, changeFrequency: 'yearly', priority: 0.30 },
    { url: 'https://vets.co/emergency-triage-card', lastModified: now, changeFrequency: 'monthly', priority: 0.90 },
    { url: 'https://vets.co/find-a-vet', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    ...stateRoutes,
    { url: 'https://vets.co/health', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://vets.co/health/allergic-reactions-dogs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/canine-influenza', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/cognitive-dysfunction', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/cushing-disease-dogs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/dehydration-in-dogs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/dental-cleaning-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/dog-eye-conditions', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/dog-vaccinations-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/emergency-signs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/heartworm-in-dogs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/heat-stroke-dogs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/intestinal-parasites', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/leptospirosis', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/pain-management-dogs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/pain-signs-dogs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/preventive-care-schedule', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/senior-bloodwork-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/senior-pet-care', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/spay-neuter-benefits', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/tick-borne-diseases', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/urinary-tract-infection', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/weight-management', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/legal/affiliate-disclosure', lastModified: now, changeFrequency: 'yearly', priority: 0.20 },
    { url: 'https://vets.co/legal/privacy-policy', lastModified: now, changeFrequency: 'yearly', priority: 0.20 },
    { url: 'https://vets.co/legal/terms', lastModified: now, changeFrequency: 'yearly', priority: 0.20 },
    { url: 'https://vets.co/diagnostics', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    ...diagnosticRoutes,
    { url: 'https://vets.co/medications', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    ...medicationRoutes,
    { url: 'https://vets.co/reviews', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://vets.co/reviews/best-pet-insurance', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/symptoms', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    ...symptomRoutes,
    { url: 'https://vets.co/telehealth', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
  ]
}
