import { MetadataRoute } from 'next'

/**
 * Auto-generated by scripts/regenerate-sitemaps.mjs.
 * To refresh after adding/removing pages, re-run:
 *   node scripts/regenerate-sitemaps.mjs
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()

  return [
    { url: 'https://vets.co', lastModified: now, changeFrequency: 'daily', priority: 1.00 },
    { url: 'https://vets.co/breeds', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://vets.co/breeds/beagle-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/chihuahua-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/french-bulldog-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/german-shepherd-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/golden-retriever-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/husky-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/labrador-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/pomeranian-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/yorkshire-terrier-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/data', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://vets.co/diagnostics', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://vets.co/disclosure', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://vets.co/editorial-standards', lastModified: now, changeFrequency: 'yearly', priority: 0.30 },
    { url: 'https://vets.co/emergency-triage-card', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://vets.co/find-a-vet', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://vets.co/health', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://vets.co/health/allergic-reactions-dogs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/canine-influenza', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/cognitive-dysfunction', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/cushing-disease-dogs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/dehydration-in-dogs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/dental-cleaning-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/dog-eye-conditions', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/dog-vaccinations-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/emergency-signs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/heartworm-in-dogs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/heat-stroke-dogs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/intestinal-parasites', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/leptospirosis', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/pain-management-dogs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/pain-signs-dogs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/preventive-care-schedule', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/senior-bloodwork-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/senior-pet-care', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/spay-neuter-benefits', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/tick-borne-diseases', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/urinary-tract-infection', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/weight-management', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/legal/affiliate-disclosure', lastModified: now, changeFrequency: 'yearly', priority: 0.20 },
    { url: 'https://vets.co/legal/privacy-policy', lastModified: now, changeFrequency: 'yearly', priority: 0.20 },
    { url: 'https://vets.co/legal/terms', lastModified: now, changeFrequency: 'yearly', priority: 0.20 },
    { url: 'https://vets.co/medications', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://vets.co/pet-insurance', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://vets.co/reviews', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://vets.co/reviews/best-pet-insurance', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/specialists', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://vets.co/symptoms', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://vets.co/telehealth', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://vets.co/tools', lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: 'https://vets.co/tools/insurance-reimbursement-estimator', lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    // /vets directory hub + state/city pages are noIndex (placeholder/sample data) until a
    // verified data source lands — intentionally omitted from the sitemap (IR P1-1).
  ]
}
