import { MetadataRoute } from 'next'
import { States } from '../data/states'
import { Symptoms } from '../data/symptoms'
import { Cities } from '../data/cities'
import { Reviewers, reviewersGloballyVisible } from '../data/reviewers'

/**
 * Auto-generated by scripts/regenerate-sitemaps.mjs, with manual additions
 * for the programmatic /find-a-vet/[state] routes (51 entries: 50 states + DC)
 * and the /symptoms/[slug] symptom-triage routes (30 entries).
 * To refresh after adding/removing pages, re-run:
 *   node scripts/regenerate-sitemaps.mjs
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()

  const stateRoutes: MetadataRoute.Sitemap = States.map((s) => ({
    url: `https://vets.co/find-a-vet/${s.slug}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    priority: 0.70,
  }))

  const symptomRoutes: MetadataRoute.Sitemap = Symptoms.map((s) => ({
    url: `https://vets.co/symptoms/${s.slug}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    // ER NOW pages skew higher: highest-intent informational queries.
    priority: s.urgencyTriage === 'ER NOW' ? 0.85 : 0.75,
  }))

  // Twenty metro-level /find-a-vet/in/[city] landing pages.
  const cityRoutes: MetadataRoute.Sitemap = Cities.map((c) => ({
    url: `https://vets.co/find-a-vet/in/${c.slug}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    priority: 0.75,
  }))

  // Reviewer pages are conditionally indexed: only included in the sitemap
  // when NEXT_PUBLIC_SHOW_REVIEWERS === 'true'. The /reviewers index page is
  // always included (it serves as the recruitment CTA when reviewers are
  // not yet active). Individual /reviewers/[slug] entries appear only when
  // both the global gate AND per-slot is_visible are flipped on.
  const reviewersLive = reviewersGloballyVisible()
  const reviewerIndexRoute: MetadataRoute.Sitemap = [
    {
      url: 'https://vets.co/reviewers',
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: reviewersLive ? 0.80 : 0.40,
    },
  ]
  const reviewerProfileRoutes: MetadataRoute.Sitemap = reviewersLive
    ? Reviewers.filter((r) => r.is_visible && r.status === 'active').map((r) => ({
        url: `https://vets.co/reviewers/${r.slug}`,
        lastModified: now,
        changeFrequency: 'monthly' as const,
        priority: 0.70,
      }))
    : []

  return [
    { url: 'https://vets.co', lastModified: now, changeFrequency: 'daily', priority: 1.00 },
    { url: 'https://vets.co/breeds/beagle-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/chihuahua-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/french-bulldog-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/german-shepherd-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/golden-retriever-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/husky-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/labrador-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/pomeranian-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/breeds/yorkshire-terrier-health', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/editorial-standards', lastModified: now, changeFrequency: 'yearly', priority: 0.30 },
    { url: 'https://vets.co/emergency-triage-card', lastModified: now, changeFrequency: 'monthly', priority: 0.90 },
    { url: 'https://vets.co/find-a-vet', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    ...stateRoutes,
    ...cityRoutes,
    ...reviewerIndexRoute,
    ...reviewerProfileRoutes,
    { url: 'https://vets.co/health', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://vets.co/health/allergic-reactions-dogs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/canine-influenza', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/cognitive-dysfunction', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/cushing-disease-dogs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/dehydration-in-dogs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/dental-cleaning-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/dog-eye-conditions', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/dog-vaccinations-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/emergency-signs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/heartworm-in-dogs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/heat-stroke-dogs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/intestinal-parasites', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/leptospirosis', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/pain-management-dogs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/pain-signs-dogs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/preventive-care-schedule', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/senior-bloodwork-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/senior-pet-care', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/spay-neuter-benefits', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/tick-borne-diseases', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/urinary-tract-infection', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/health/weight-management', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/legal/affiliate-disclosure', lastModified: now, changeFrequency: 'yearly', priority: 0.20 },
    { url: 'https://vets.co/legal/privacy-policy', lastModified: now, changeFrequency: 'yearly', priority: 0.20 },
    { url: 'https://vets.co/legal/terms', lastModified: now, changeFrequency: 'yearly', priority: 0.20 },
    { url: 'https://vets.co/reviews', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://vets.co/reviews/best-pet-insurance', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://vets.co/symptoms', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    ...symptomRoutes,
    { url: 'https://vets.co/telehealth', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
  ]
}
