import { MetadataRoute } from 'next'

/**
 * Auto-generated by scripts/regenerate-sitemaps.mjs.
 * To refresh after adding/removing pages, re-run:
 *   node scripts/regenerate-sitemaps.mjs
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()

  return [
    { url: 'https://petfood.com', lastModified: now, changeFrequency: 'daily', priority: 1.00 },
    { url: 'https://petfood.com/brands/blue-buffalo-evaluation', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://petfood.com/brands/hills-vs-royal-canin', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://petfood.com/brands/orijen-vs-acana-comparison', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://petfood.com/conditions', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://petfood.com/disclosure', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://petfood.com/guides/aafco-completeness-explained', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://petfood.com/guides/methodology', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://petfood.com/guides/raw-pet-food-evaluation', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://petfood.com/guides/reading-pet-food-labels', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://petfood.com/ingredients/animal-protein-sources', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://petfood.com/ingredients/grain-free-dcm-risk', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://petfood.com/ingredients/preservatives-pet-food', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://petfood.com/life-stage', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://petfood.com/tools', lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: 'https://petfood.com/tools/food-cost-calculator', lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
  ]
}
