import { SRC, STD } from './_shared.mjs'

const D = 'compare'

const RAW = [
  {
    dir: D, slug: 'wet-vs-dry-food', date: '2026-06-01',
    title: 'Wet vs Dry Food',
    metaTitle: 'Wet vs Dry Pet Food — An Even-Handed Comparison | PetFood.com',
    metaDesc:
      'How canned and dry food compare on moisture, calorie density, dental claims, cost, and palatability, and why the species and the individual animal decide.',
    category: 'Food-Type Comparison', readTime: '10 min',
    hero:
      "Wet versus dry is the most common format question owners ask, and the honest answer is that it depends on the species and the individual. Each format has real advantages — dry food on cost and convenience, wet food on hydration and palatability — and the popular claims (notably that dry food cleans teeth) are weaker than commonly believed. This page compares them dimension by dimension.",
    toc: [
      { label: 'The Core Difference — Moisture', id: 'moisture' },
      { label: 'Calorie Density', id: 'calories' },
      { label: 'The Dental Claim', id: 'dental' },
      { label: 'Cost and Convenience', id: 'cost' },
      { label: 'Palatability and Hydration', id: 'palatability' },
      { label: 'Choosing or Combining', id: 'choosing' },
    ],
    body: [
      { p: "The defining difference between wet and dry food is water content: canned food is roughly 75 to 82 percent water, dry kibble about 6 to 12 percent. Almost every other practical difference flows from that, plus the manufacturing difference (extrusion requires starch; canning does not). Neither format is universally better; the right choice depends on the species, the individual animal, and the household. Nutrient comparisons between them must be done on a dry-matter basis. See [[Dry-Matter Basis Explained|/nutrition/dry-matter-basis-explained]]." },
      { h2: 'The Core Difference — Moisture', id: 'moisture' },
      { p: "The high moisture of canned food is its biggest functional advantage, especially for cats. Cats have a weak thirst drive and tend to under-hydrate on dry food, and increased dietary water supports urinary and kidney health. For cats with a history of urinary disease or kidney disease, the moisture of canned food is a genuine clinical benefit. See [[Water and Hydration|/nutrition/water-and-hydration]] and [[Urinary and Bladder Stone Diets|/diets/urinary-tract-diets]]." },
      { h2: 'Calorie Density', id: 'calories' },
      { p: "Per gram as-fed, canned food is far lower in calories than kibble because so much of it is water — which can help with satiety and weight control, since the animal eats a larger, more filling volume for the same calories. Per dry gram, however, canned diets are often quite energy-dense. The practical point is that wet and dry calories must be summed correctly when mixing, and the calorie statement read for each. See [[Pet Food Calories and Energy Density|/nutrition/calories-and-energy-density]]." },
      { h2: 'The Dental Claim', id: 'dental' },
      { p: "The belief that dry food cleans teeth is largely overstated. Most kibble shatters on contact and provides little mechanical cleaning, and dental disease is common in dry-fed animals. Specially designed dental kibbles with a larger, fibrous matrix do have some plaque- and tartar-reducing effect, and certain ones carry the Veterinary Oral Health Council (VOHC) seal — but ordinary kibble is not a substitute for dental care. Do not choose dry food primarily for dental benefit." },
      { h2: 'Cost and Convenience', id: 'cost' },
      { p: "Dry food is generally cheaper per calorie, stores easily once sealed, can be left out longer (though meal feeding is still preferred), and works in puzzle and automatic feeders. Canned food costs more per calorie, must be refrigerated after opening and used within days, and spoils if left in the bowl. For large dogs especially, the cost difference is significant. See the [[Food Cost Calculator|/tools/food-cost-calculator]] and [[Pet Food Storage and Safety|/feeding/food-storage-and-safety]]." },
      { h2: 'Palatability and Hydration', id: 'palatability' },
      { p: "Canned food is typically more palatable due to its aroma, texture, and higher fat and protein, which makes it valuable for sick, inappetent, or senior animals that need encouragement to eat, and for cats recovering from illness. Its hydration benefit reinforces this in animals that need more water. For a picky or convalescing animal, the palatability of wet food can be the deciding factor." },
      { h2: 'Choosing or Combining', id: 'choosing' },
      { p: "Many owners successfully combine the two: kibble for cost and convenience, with canned food added for hydration, palatability, and satiety. A combination captures several of each format's advantages, provided total calories are counted across both. For most healthy animals either format, if complete and balanced, supports good health; the choice can be made on the individual's needs and the household's practicality. See [[How Much to Feed a Cat|/feeding/how-much-to-feed-a-cat]]." },
    ],
    related: [
      { label: 'Dry-Matter Basis Explained', href: '/nutrition/dry-matter-basis-explained' },
      { label: 'Water and Hydration', href: '/nutrition/water-and-hydration' },
      { label: 'Pet Food Calories and Energy Density', href: '/nutrition/calories-and-energy-density' },
    ],
    sources: [...STD],
  },

  {
    dir: D, slug: 'raw-vs-cooked-diets', date: '2026-06-01',
    title: 'Raw vs Cooked Diets',
    metaTitle: 'Raw vs Cooked Pet Diets — The Evidence | PetFood.com',
    metaDesc:
      'How raw and cooked diets compare on digestibility, pathogen risk, nutrient availability, and the veterinary consensus, with a harm-reduction framing.',
    category: 'Food-Type Comparison', readTime: '11 min',
    hero:
      "Raw versus cooked is the most polarized comparison in pet nutrition, and the evidence is more one-sided than the debate suggests: the major veterinary bodies caution against raw diets primarily on pathogen-safety grounds. This page compares the two on digestibility, safety, and nutrient availability, and lays out a harm-reduction approach for owners who choose raw anyway.",
    toc: [
      { label: 'What Cooking Does', id: 'cooking' },
      { label: 'Pathogen Risk', id: 'pathogen' },
      { label: 'Digestibility and Nutrients', id: 'digestibility' },
      { label: 'The Veterinary Consensus', id: 'consensus' },
      { label: 'Completeness and Balance', id: 'completeness' },
      { label: 'Harm Reduction', id: 'harmreduction' },
    ],
    body: [
      { p: "Cooking transforms food in ways that matter nutritionally and microbiologically. Proponents of raw feeding argue that cooking destroys enzymes and nutrients and that raw is more natural; the veterinary professional bodies counter that cooking's pathogen-control benefit outweighs its costs and that the naturalness argument is overstated for domesticated animals. This page weighs the specific claims. For the full treatment, see the [[Raw Pet Food Evaluation|/guides/raw-pet-food-evaluation]]." },
      { h2: 'What Cooking Does', id: 'cooking' },
      { p: "Heat denatures proteins (which can improve digestibility of some and reduce it for others), gelatinizes starch (making it digestible), destroys most pathogenic bacteria, inactivates certain anti-nutritional factors, and degrades some heat-sensitive vitamins (which is why cooked commercial diets are vitamin-supplemented). The claim that raw food retains beneficial enzymes is largely irrelevant: dietary enzymes are denatured by stomach acid and do not contribute meaningfully to the animal's own digestion." },
      { h2: 'Pathogen Risk', id: 'pathogen' },
      { p: "This is the crux. Raw meat diets carry documented contamination with Salmonella, Listeria, Campylobacter, and other pathogens, posing risk both to the pet and — through shed bacteria and contaminated surfaces — to people in the household, especially the immunocompromised, children, and the elderly. Studies repeatedly find pathogen contamination in commercial raw diets. Cooking eliminates this risk, and high-pressure processing (HPP) reduces it in some commercial raw products without heat. See [[Pet Food Storage and Safety|/feeding/food-storage-and-safety]]." },
      { h2: 'Digestibility and Nutrients', id: 'digestibility' },
      { p: "Raw diets can be highly digestible, and some animals do well on a properly formulated raw diet. But raw is not inherently more digestible than a well-made cooked diet, and the nutrient-availability claims cut both ways — cooking improves the availability of some nutrients (notably starch) while reducing others. The decisive nutritional issue is usually not raw versus cooked but whether the diet is complete and balanced, which many home-prepared raw diets are not. See [[Animal Protein Sources|/ingredients/animal-protein-sources]]." },
      { h2: 'The Veterinary Consensus', id: 'consensus' },
      { p: "The WSAVA, AVMA, AAHA, and FDA have all published statements cautioning against raw meat-based diets, principally on the basis of pathogen risk to pets and humans, and (for home-prepared raw) the high rate of nutritional imbalance. This is a clear professional consensus. It does not mean every raw-fed animal will become ill, but it reflects a population-level risk assessment that owners should weigh honestly." },
      { h2: 'Completeness and Balance', id: 'completeness' },
      { p: "Home-prepared raw diets are frequently nutritionally incomplete — analyses have found widespread deficiencies and imbalances, particularly in calcium-to-phosphorus ratio and several micronutrients. An all-meat raw diet without proper calcium balancing is a classic cause of skeletal disease. A complete cooked commercial diet (or a properly formulated raw diet validated against AAFCO profiles) avoids this. See [[Home-Cooked vs Commercial Diets|/compare/home-cooked-vs-commercial]] and [[Minerals in Pet Food|/nutrition/minerals-in-pet-food]]." },
      { h2: 'Harm Reduction', id: 'harmreduction' },
      { p: "For owners who choose raw despite the consensus, harm reduction means: select a commercial raw diet formulated to meet AAFCO profiles (ideally HPP-treated) rather than an unbalanced home recipe, or work with a board-certified veterinary nutritionist on a balanced formulation; handle the food with strict hygiene; and avoid raw feeding in households with immunocompromised members, young children, or pregnant people. These steps mitigate but do not eliminate the documented risks. See the [[Raw Pet Food Evaluation|/guides/raw-pet-food-evaluation]]." },
    ],
    related: [
      { label: 'Raw Pet Food Evaluation', href: '/guides/raw-pet-food-evaluation' },
      { label: 'Home-Cooked vs Commercial Diets', href: '/compare/home-cooked-vs-commercial' },
      { label: 'Pet Food Storage and Safety', href: '/feeding/food-storage-and-safety' },
    ],
    sources: [...STD, SRC.fdaPet],
  },

  {
    dir: D, slug: 'fresh-vs-kibble', date: '2026-06-01',
    title: 'Fresh vs Kibble',
    metaTitle: 'Fresh Pet Food vs Kibble — Comparison | PetFood.com',
    metaDesc:
      'How fresh and gently cooked diets compare to kibble on processing, digestibility, cost, and evidence, and what the fresh-food category does and does not prove.',
    category: 'Food-Type Comparison', readTime: '10 min',
    hero:
      "Fresh, gently cooked, refrigerated pet food has grown into a major category positioned against kibble on the strength of minimal processing. Some of its advantages are real, some claims outrun the evidence, and the cost difference is substantial. This page compares fresh and kibble on processing, digestibility, evidence, and practicality.",
    toc: [
      { label: 'What Fresh Food Is', id: 'whatis' },
      { label: 'Processing Differences', id: 'processing' },
      { label: 'Digestibility Evidence', id: 'digestibility' },
      { label: 'Completeness and AAFCO', id: 'aafco' },
      { label: 'Cost and Practicality', id: 'cost' },
      { label: 'Evaluating a Fresh Diet', id: 'evaluating' },
    ],
    body: [
      { p: "Fresh pet food refers to gently cooked, minimally processed, usually refrigerated or frozen complete diets, often sold by subscription. The category positions itself against extruded kibble on the basis of lower-temperature cooking, recognizable whole ingredients, and higher moisture. The honest comparison separates the parts of that pitch supported by evidence from the parts that are marketing. See [[Pet Food Calories and Energy Density|/nutrition/calories-and-energy-density]]." },
      { h2: 'What Fresh Food Is', id: 'whatis' },
      { p: "Fresh diets are cooked at lower temperatures than the high-heat extrusion used for kibble, then refrigerated or frozen, with moisture content far higher than dry food (closer to canned). They use whole, identifiable ingredients and avoid the shelf-stable preservatives kibble requires. Like all complete diets, they should be formulated to meet AAFCO nutrient profiles for the life stage." },
      { h2: 'Processing Differences', id: 'processing' },
      { p: "Extrusion subjects kibble to high heat and pressure, which gelatinizes starch (necessary for the kibble structure), kills pathogens, and degrades some heat-sensitive nutrients that are then replaced by the vitamin premix. Gentle cooking uses lower temperatures, which preserves more heat-sensitive nutrients in their natural form and avoids the high-starch requirement of extrusion. The processing difference is real; whether it translates to a meaningful health difference is less established. See [[Vitamins in Pet Food|/nutrition/vitamins-in-pet-food]]." },
      { h2: 'Digestibility Evidence', id: 'digestibility' },
      { p: "Some studies, several of them industry-funded, report higher digestibility and favorable stool quality for fresh diets compared with kibble. Higher digestibility is plausible given the ingredients and processing, but the independent, long-term outcome evidence (longevity, disease incidence) is limited, and many comparative studies have funding or design limitations. The category is promising but the strongest health claims outrun the current independent evidence." },
      { h2: 'Completeness and AAFCO', id: 'aafco' },
      { p: "A fresh diet is only as good as its formulation. The key question is the same as for any food: does it carry an AAFCO complete-and-balanced statement for the appropriate life stage, by formulation or feeding trial, and is it made under sound manufacturing controls? Fresh diets that meet AAFCO profiles via feeding trial and disclose their manufacturing are stronger than those relying on formulation alone with thin disclosure. See [[AAFCO Completeness Explained|/guides/aafco-completeness-explained]]." },
      { h2: 'Cost and Practicality', id: 'cost' },
      { p: "Fresh food costs substantially more per calorie than kibble — often several times more, especially for large dogs — and requires refrigerator or freezer space, thawing, and use within a few days of opening. Subscription models add convenience but lock in the higher cost. For many households the cost is the deciding factor, and a high-quality kibble or canned diet remains a sound choice. See the [[Food Cost Calculator|/tools/food-cost-calculator]]." },
      { h2: 'Evaluating a Fresh Diet', id: 'evaluating' },
      { p: "Judge a fresh diet the way you would any other: confirm the AAFCO statement and life-stage match, prefer feeding-trial substantiation, look for manufacturing and sourcing transparency and a board-certified veterinary nutritionist on staff, and check the calorie density so you feed the right amount. Do not assume fresh equals better without checking the formulation; a poorly formulated fresh diet is inferior to a well-formulated kibble. See [[Pet Food Storage and Safety|/feeding/food-storage-and-safety]]." },
    ],
    related: [
      { label: 'AAFCO Completeness Explained', href: '/guides/aafco-completeness-explained' },
      { label: 'Vitamins in Pet Food', href: '/nutrition/vitamins-in-pet-food' },
      { label: 'Home-Cooked vs Commercial Diets', href: '/compare/home-cooked-vs-commercial' },
    ],
    sources: [...STD],
  },

  {
    dir: D, slug: 'grain-free-vs-grain-inclusive', date: '2026-06-01',
    title: 'Grain-Free vs Grain-Inclusive',
    metaTitle: 'Grain-Free vs Grain-Inclusive Pet Food | PetFood.com',
    metaDesc:
      'What grain-free actually changes, the grain-allergy myth, the FDA DCM investigation, and why grain-free is not the same as low-carbohydrate.',
    category: 'Food-Type Comparison', readTime: '11 min',
    hero:
      "Grain-free became one of the best-selling positions in pet food on the strength of a claim — that grain is a common allergen and an inferior filler — that the evidence does not support. The FDA investigation into grain-free diets and heart disease then complicated the picture further. This page separates what grain-free actually changes from the marketing around it.",
    toc: [
      { label: 'What Grain-Free Means', id: 'whatis' },
      { label: 'The Grain-Allergy Myth', id: 'allergy' },
      { label: 'Grain-Free Is Not Low-Carb', id: 'notlowcarb' },
      { label: 'The FDA DCM Investigation', id: 'dcm' },
      { label: 'When Grain-Free Makes Sense', id: 'whensense' },
      { label: 'The Bottom Line', id: 'bottomline' },
    ],
    body: [
      { p: "Grain-free pet food replaces cereal grains (corn, wheat, rice) with other carbohydrate sources, most often potatoes, peas, lentils, and other legumes. The category was built on the marketing premise that grains are common allergens and low-quality fillers, and that a grain-free diet is therefore healthier. Neither premise holds up well, and the FDA later identified a possible association between some grain-free diets and canine heart disease. See [[Grain-Free and DCM Risk|/ingredients/grain-free-dcm-risk]]." },
      { h2: 'What Grain-Free Means', id: 'whatis' },
      { p: "Grain-free means only that the recipe contains no cereal grains. It says nothing about carbohydrate content, protein quality, or overall nutritional value, because the grains are simply replaced by other carbohydrate ingredients. The term is a marketing claim about one ingredient category, not a measure of diet quality." },
      { h2: 'The Grain-Allergy Myth', id: 'allergy' },
      { p: "Grains are an uncommon cause of food allergy in dogs and cats; the most common food allergens are animal proteins — beef, dairy, chicken, fish — not grains. The frequent assumption that an itchy dog needs a grain-free diet is usually misplaced. True food allergy is diagnosed by an elimination trial, and the offending allergen is far more often a protein than a grain. See [[Food Allergy and Elimination Diets|/diets/food-allergy-and-elimination-diets]]." },
      { h2: 'Grain-Free Is Not Low-Carbohydrate', id: 'notlowcarb' },
      { p: "Because extruded kibble requires starch for its structure, grain-free kibble simply uses potato, pea, lentil, or tapioca starch in place of grain starch — and the total carbohydrate is often similar to a grain-inclusive food. Owners seeking a low-carbohydrate diet (for instance, for a diabetic cat) are frequently misled by grain-free into thinking they have one; a truly low-carbohydrate diet is more reliably achieved with canned food. See [[Carbohydrates in Pet Food|/nutrition/carbohydrates-in-pet-food]]." },
      { h2: 'The FDA DCM Investigation', id: 'dcm' },
      { p: "From 2018, the FDA investigated reports of dilated cardiomyopathy (DCM) in dogs eating grain-free, legume-heavy diets. The investigation identified an association — not proven causation — between certain grain-free, legume-rich formulations and DCM, and the mechanism remains unresolved. The episode turned the grain-free health claim on its head for many veterinarians. The full record is covered on our dedicated page. See [[Grain-Free and DCM Risk|/ingredients/grain-free-dcm-risk]]." },
      { h2: 'When Grain-Free Makes Sense', id: 'whensense' },
      { p: "Grain-free is genuinely appropriate in the uncommon case of a confirmed grain allergy diagnosed by elimination trial. Outside that specific situation, there is no general health advantage to grain-free, and the DCM association gives reason for caution about legume-heavy grain-free formulations in particular. A grain-inclusive diet from a reputable manufacturer is a sound default for most animals." },
      { h2: 'The Bottom Line', id: 'bottomline' },
      { p: "Grain-free is a marketing position, not a quality tier. It does not reduce allergy risk for most animals, does not necessarily lower carbohydrate, and — in legume-heavy forms — has been associated with a heart-disease signal still under investigation. Choose a diet on its overall formulation, manufacturer transparency, and AAFCO substantiation rather than on the presence or absence of grain. See [[Pet Food Myths|/myths]]." },
    ],
    related: [
      { label: 'Grain-Free and DCM Risk', href: '/ingredients/grain-free-dcm-risk' },
      { label: 'Carbohydrates in Pet Food', href: '/nutrition/carbohydrates-in-pet-food' },
      { label: 'Food Allergy and Elimination Diets', href: '/diets/food-allergy-and-elimination-diets' },
    ],
    sources: [...STD, SRC.fdaDcm],
  },

  {
    dir: D, slug: 'home-cooked-vs-commercial', date: '2026-06-01',
    title: 'Home-Cooked vs Commercial Diets',
    metaTitle: 'Home-Cooked vs Commercial Pet Diets | PetFood.com',
    metaDesc:
      'Why home-cooked diets so often end up unbalanced, the role of board-certified veterinary nutritionists, supplement requirements, and when home cooking is justified.',
    category: 'Food-Type Comparison', readTime: '11 min',
    hero:
      "Home-cooking for a pet is appealing and, done correctly, legitimate — but the evidence is unambiguous that most home-prepared recipes, including those from books and websites, are nutritionally incomplete. The gap between a balanced home diet and an unbalanced one is a board-certified veterinary nutritionist and a precise recipe. This page covers the risks, the right way to do it, and when it is justified.",
    toc: [
      { label: 'The Appeal', id: 'appeal' },
      { label: 'The Imbalance Problem', id: 'imbalance' },
      { label: 'Why Recipes Fail', id: 'recipesfail' },
      { label: 'Doing It Correctly', id: 'correctly' },
      { label: 'Supplements Are Required', id: 'supplements' },
      { label: 'When It Is Justified', id: 'justified' },
    ],
    body: [
      { p: "Home-cooking lets owners control ingredients, accommodate preferences and some medical needs, and avoid commercial processing. The problem is not the concept but the execution: balancing a complete diet by hand is genuinely difficult, and study after study finds that the large majority of home-prepared recipes — including many published in books and online and even some from veterinarians without nutrition training — fail to meet established nutrient requirements. See [[Minerals in Pet Food|/nutrition/minerals-in-pet-food]]." },
      { h2: 'The Appeal', id: 'appeal' },
      { p: "Owners turn to home-cooking for control over ingredient quality, to manage picky eaters or food sensitivities, for animals with multiple conditions that no single commercial diet addresses, and out of distrust of commercial processing. These are understandable motivations, and a properly formulated home diet can be a fine choice — the issue is ensuring proper formulation." },
      { h2: 'The Imbalance Problem', id: 'imbalance' },
      { p: "Analyses of home-prepared maintenance recipes consistently find a majority deficient in multiple essential nutrients, with calcium, several trace minerals, and certain vitamins most often inadequate, and calcium-to-phosphorus ratio frequently wrong. An all-meat homemade diet is calcium-deficient and phosphorus-rich, causing nutritional secondary hyperparathyroidism and skeletal disease. The imbalances are usually invisible for months before clinical signs appear. See [[Taurine and Amino Acids|/nutrition/taurine-and-amino-acids]]." },
      { h2: 'Why Recipes Fail', id: 'recipesfail' },
      { p: "Recipes fail because balancing dozens of nutrients to meet minima without exceeding maxima requires nutritional software and expertise, because owners substitute ingredients (changing the nutrient profile), because supplements are omitted or dosed by guess, and because cooking and ingredient variation alter the numbers. A recipe that is balanced on paper is often not followed exactly, and small deviations compound. Popularity or a veterinarian byline does not guarantee a recipe is complete." },
      { h2: 'Doing It Correctly', id: 'correctly' },
      { p: "A complete home-cooked diet should be formulated by a board-certified veterinary nutritionist (a Diplomate of the American College of Veterinary Nutrition or equivalent) or via a reputable formulation service, individualized to the animal, followed precisely without ingredient substitution, and rechecked if anything changes. The recipe will specify exact quantities, a specific supplement product, and the cooking method. This is the difference between a balanced and an unbalanced home diet." },
      { h2: 'Supplements Are Required', id: 'supplements' },
      { p: "A balanced home-cooked diet essentially always requires a supplement to supply nutrients that whole-food ingredients cannot provide in the right amounts — calcium being the most critical, plus a vitamin-and-mineral source and often specific additions like taurine for cats. Generic human multivitamins are not adequate substitutes. The formulating nutritionist specifies the exact supplement and dose. See [[Multivitamins for Pets|/supplements/multivitamins-for-pets]]." },
      { h2: 'When It Is Justified', id: 'justified' },
      { p: "Home-cooking is justified when an animal will not eat or cannot tolerate suitable commercial diets, when a combination of medical conditions is not addressed by any commercial therapeutic diet, or when an owner is committed to it and willing to do it properly through a veterinary nutritionist. It is not justified as a casual swap from commercial food based on a recipe found online. Done right it is excellent; done casually it is a common cause of preventable nutritional disease. See [[Fresh vs Kibble|/compare/fresh-vs-kibble]]." },
    ],
    related: [
      { label: 'Minerals in Pet Food', href: '/nutrition/minerals-in-pet-food' },
      { label: 'Multivitamins for Pets', href: '/supplements/multivitamins-for-pets' },
      { label: 'Raw vs Cooked Diets', href: '/compare/raw-vs-cooked-diets' },
    ],
    sources: [...STD],
  },

  {
    dir: D, slug: 'kibble-vs-canned-for-cats', date: '2026-06-01',
    title: 'Kibble vs Canned for Cats',
    metaTitle: 'Kibble vs Canned Food for Cats — The Feline Case | PetFood.com',
    metaDesc:
      'Why the wet-vs-dry question is sharper for cats — obligate-carnivore physiology, hydration, carbohydrate, weight, and urinary health all favor wet for many cats.',
    category: 'Food-Type Comparison', readTime: '10 min',
    hero:
      "For cats specifically, the wet-versus-dry question carries more weight than it does for dogs, because feline physiology amplifies the differences. Obligate-carnivore metabolism, a weak thirst drive, and a tendency toward obesity, diabetes, and urinary disease all tilt the balance toward canned food for many cats. This page makes the feline-specific case.",
    toc: [
      { label: 'Why Cats Are Different', id: 'different' },
      { label: 'Hydration', id: 'hydration' },
      { label: 'Carbohydrate and Diabetes', id: 'carbdiabetes' },
      { label: 'Weight Control', id: 'weight' },
      { label: 'Urinary Health', id: 'urinary' },
      { label: 'The Practical Verdict', id: 'verdict' },
    ],
    body: [
      { p: "The general wet-versus-dry comparison applies to cats, but several feline traits sharpen it. Cats are obligate carnivores adapted to a high-moisture, high-protein, low-carbohydrate prey diet, and they have a weak thirst drive. Modern indoor cats fed dry food face higher rates of obesity, diabetes, and urinary disease — problems to which diet format contributes. For many cats, canned food addresses several of these at once. See [[Dog vs Cat Nutrition|/species/dog-vs-cat-nutrition-overview]]." },
      { h2: 'Why Cats Are Different', id: 'different' },
      { p: "A cat's ancestral diet was small prey — high in water, high in animal protein and fat, very low in carbohydrate. Cats evolved to obtain most of their water from food and to run their metabolism on protein and fat. Dry kibble, by necessity high in starch and low in moisture, departs from this template more than canned food does. The mismatch is the root of the feline-specific concerns." },
      { h2: 'Hydration', id: 'hydration' },
      { p: "Because cats have a weak thirst drive, those on dry food often run chronically under-hydrated and produce concentrated urine, while cats on canned food obtain much of their water from the diet. Better hydration supports kidney and urinary health — both common problem areas in cats. This is the single strongest feline argument for canned food. See [[Water and Hydration|/nutrition/water-and-hydration]]." },
      { h2: 'Carbohydrate and Diabetes', id: 'carbdiabetes' },
      { p: "Cats handle dietary carbohydrate less efficiently than dogs and have limited carbohydrate-digesting enzyme activity. High-carbohydrate dry diets are implicated in feline obesity and diabetes, and low-carbohydrate (typically canned) diets improve glycemic control and can support diabetic remission in cats. For a diabetic or diabetes-prone cat, the lower carbohydrate of canned food is a meaningful advantage. See [[Diabetic Diets|/diets/diabetic-diets]] and [[Carbohydrates in Pet Food|/nutrition/carbohydrates-in-pet-food]]." },
      { h2: 'Weight Control', id: 'weight' },
      { p: "Canned food's lower calorie density per gram and higher water content help with satiety and weight control, and measured wet meals are easier to portion than free-fed kibble. Given the high rate of feline obesity, this matters. That said, weight control ultimately depends on total calories and measured feeding regardless of format. See [[How Much to Feed a Cat|/feeding/how-much-to-feed-a-cat]]." },
      { h2: 'Urinary Health', id: 'urinary' },
      { p: "Increased water intake dilutes the urine, reducing the supersaturation that forms crystals and stones and helping flush the lower urinary tract. For cats with a history of feline lower urinary tract disease, urinary stones, or idiopathic cystitis, the moisture of canned food is part of standard management. See [[Urinary and Bladder Stone Diets|/diets/urinary-tract-diets]]." },
      { h2: 'The Practical Verdict', id: 'verdict' },
      { p: "For many cats, canned food (alone or combined with kibble) offers real advantages in hydration, carbohydrate, weight, and urinary health, and is often the better default — especially for cats prone to obesity, diabetes, or urinary disease. Dry food remains acceptable for healthy cats when used with measured feeding and good water access, and is cheaper and more convenient. A wet-and-dry combination is a reasonable middle ground. The choice should weigh the individual cat's health risks." },
    ],
    related: [
      { label: 'Wet vs Dry Food', href: '/compare/wet-vs-dry-food' },
      { label: 'Dog vs Cat Nutrition', href: '/species/dog-vs-cat-nutrition-overview' },
      { label: 'Urinary and Bladder Stone Diets', href: '/diets/urinary-tract-diets' },
    ],
    sources: [...STD],
  },

  {
    dir: D, slug: 'freeze-dried-and-dehydrated', date: '2026-06-01',
    title: 'Freeze-Dried and Dehydrated Diets',
    metaTitle: 'Freeze-Dried and Dehydrated Pet Food Explained | PetFood.com',
    metaDesc:
      'How freeze-dried and dehydrated diets are made, the raw-versus-cooked distinction, rehydration and pathogen considerations, and how to evaluate them.',
    category: 'Food-Type Comparison', readTime: '9 min',
    hero:
      "Freeze-dried and dehydrated diets occupy a middle ground between kibble and fresh or raw food — shelf-stable like kibble, but often minimally cooked or raw. The key questions are whether the product is raw or cooked, whether it is complete and balanced, and how it is meant to be served. This page explains the processes and how to evaluate the category.",
    toc: [
      { label: 'How They Are Made', id: 'howmade' },
      { label: 'Raw vs Cooked Base', id: 'rawcooked' },
      { label: 'Rehydration', id: 'rehydration' },
      { label: 'Pathogen Considerations', id: 'pathogen' },
      { label: 'Complete vs Topper', id: 'completetopper' },
      { label: 'Evaluating the Product', id: 'evaluating' },
    ],
    body: [
      { p: "Freeze-drying and dehydration both remove water to make food shelf-stable, but by different methods and at different temperatures, and the starting material may be raw or cooked. The category includes complete diets meant to be the sole food and toppers meant only to enhance a complete diet. Because of this variety, the label and the AAFCO statement matter as much here as anywhere. See [[Raw vs Cooked Diets|/compare/raw-vs-cooked-diets]]." },
      { h2: 'How They Are Made', id: 'howmade' },
      { p: "Freeze-drying (lyophilization) freezes the food, then removes water by sublimation under vacuum at low temperature, preserving structure and most nutrients with minimal heat. Dehydration removes water using warm air, which is gentler than extrusion but applies more heat than freeze-drying. Both yield a lightweight, shelf-stable product that is usually rehydrated before feeding. Freeze-drying is more expensive and better at preserving heat-sensitive nutrients." },
      { h2: 'Raw vs Cooked Base', id: 'rawcooked' },
      { p: "A crucial distinction: many freeze-dried diets are made from raw ingredients and are therefore raw diets in shelf-stable form, carrying the same pathogen considerations as other raw food. Dehydrated diets may be raw or gently cooked depending on the temperature used. The package usually states whether the product is raw; this determines the handling-safety profile. See [[Pet Food Storage and Safety|/feeding/food-storage-and-safety]]." },
      { h2: 'Rehydration', id: 'rehydration' },
      { p: "Most freeze-dried and dehydrated complete diets are designed to be rehydrated with water before feeding, which restores moisture (a hydration benefit similar to wet food) and releases aroma for palatability. Feeding them dry is possible for some products but reduces the moisture benefit and, for a thirsty animal, may be less ideal. Follow the manufacturer's rehydration instructions, and use clean water." },
      { h2: 'Pathogen Considerations', id: 'pathogen' },
      { p: "Freeze-drying and dehydration reduce but do not reliably eliminate pathogens, particularly in raw-based products — drying is not a kill step the way cooking is. Some manufacturers apply high-pressure processing or another validated kill step; others do not. Raw freeze-dried diets therefore carry handling-safety considerations like other raw food, and the same cautions apply for immunocompromised households. See [[Raw Pet Food Evaluation|/guides/raw-pet-food-evaluation]]." },
      { h2: 'Complete vs Topper', id: 'completetopper' },
      { p: "Some freeze-dried products are complete and balanced diets; many are toppers, mixers, or treats intended only to supplement a complete diet, and carry the intermittent-or-supplemental-feeding statement rather than a complete-and-balanced one. Feeding a topper as the sole diet causes nutritional imbalance. Always check the AAFCO statement to know which you have. See [[AAFCO Completeness Explained|/guides/aafco-completeness-explained]]." },
      { h2: 'Evaluating the Product', id: 'evaluating' },
      { p: "Check whether the product is raw or cooked (for the safety profile), whether it carries a complete-and-balanced AAFCO statement for the life stage or is intended only as a topper, the calorie density (these diets are energy-dense by dry weight, so portions are small), and the manufacturer's transparency and kill-step practices. The convenience and palatability are real; the safety and completeness depend on the specific product." },
    ],
    related: [
      { label: 'Raw vs Cooked Diets', href: '/compare/raw-vs-cooked-diets' },
      { label: 'Pet Food Storage and Safety', href: '/feeding/food-storage-and-safety' },
      { label: 'AAFCO Completeness Explained', href: '/guides/aafco-completeness-explained' },
    ],
    sources: [...STD, SRC.fdaPet],
  },

  {
    dir: D, slug: 'prescription-vs-otc-diets', date: '2026-06-01',
    title: 'Prescription vs Over-the-Counter Diets',
    metaTitle: 'Prescription vs OTC Pet Diets — What Differs | PetFood.com',
    metaDesc:
      'Why therapeutic diets require veterinary authorization, how they are formulated and tested differently, the cost and access trade-offs, and when each is appropriate.',
    category: 'Food-Type Comparison', readTime: '9 min',
    hero:
      "Prescription (therapeutic) diets occupy a distinct regulatory and clinical space from over-the-counter foods, and the difference is more than marketing. They are formulated to specific therapeutic targets, often validated in the target disease, and require veterinary authorization for sound reasons. This page explains what differs, why the gatekeeping exists, and the trade-offs.",
    toc: [
      { label: 'What Prescription Means Here', id: 'whatmeans' },
      { label: 'Formulation Differences', id: 'formulation' },
      { label: 'Why Veterinary Authorization', id: 'authorization' },
      { label: 'Evidence and Testing', id: 'evidence' },
      { label: 'Cost and Access', id: 'cost' },
      { label: 'Choosing Between Them', id: 'choosing' },
    ],
    body: [
      { p: "Therapeutic diets, commonly called prescription diets, are foods formulated to manage specific diagnosed conditions and sold only with veterinary authorization. Despite the name, they are not drugs and the prescription is not a legal controlled-substance requirement; rather, manufacturers restrict them to veterinary channels because their correct use depends on diagnosis and monitoring. Over-the-counter wellness and even condition-themed foods are formulated to ordinary maintenance standards. See [[Condition-Specific Diets|/diets]]." },
      { h2: 'What Prescription Means Here', id: 'whatmeans' },
      { p: "A prescription diet is authorized by a veterinarian for a patient with a diagnosed condition. The veterinary-channel restriction exists because these diets can be inappropriate or harmful for animals that do not have the target condition — a phosphorus-restricted renal diet, for example, is not suitable for a healthy growing animal. The authorization ties the diet to a diagnosis and to follow-up monitoring." },
      { h2: 'Formulation Differences', id: 'formulation' },
      { p: "Therapeutic diets are formulated to specific nutrient targets that often fall outside the normal range for maintenance foods — sharply restricted phosphorus and moderated protein for kidney disease, very low fat for pancreatitis, hydrolyzed protein for allergy, controlled mineral and pH targets for urinary stones. OTC foods, including those marketed for sensitive skin or weight, are formulated to ordinary AAFCO maintenance profiles and do not hit these therapeutic targets. See [[Kidney Disease Diets|/diets/kidney-disease-diets]]." },
      { h2: 'Why Veterinary Authorization', id: 'authorization' },
      { p: "The gatekeeping protects animals: a therapeutic diet used without the matching diagnosis can cause harm (feeding a low-protein renal diet to a healthy puppy), and a therapeutic diet used correctly requires monitoring (bloodwork to track kidney values, glucose curves for diabetes). It also protects the integrity of diagnostic diet trials — an elimination diet only works if the veterinarian controls the protocol. The restriction is clinical, not merely commercial. See [[Food Allergy and Elimination Diets|/diets/food-allergy-and-elimination-diets]]." },
      { h2: 'Evidence and Testing', id: 'evidence' },
      { p: "Many therapeutic diets are supported by published feeding studies in the target disease — renal diets, for instance, have controlled-trial evidence for extending survival in CKD. This disease-specific evidence is a meaningful advantage over condition-themed OTC foods, whose claims are typically not validated in the disease. Feeding-trial substantiation and disease-specific research strengthen the case for the veterinary product where one is indicated." },
      { h2: 'Cost and Access', id: 'cost' },
      { p: "Therapeutic diets generally cost more than OTC foods and require a veterinary relationship to obtain, which can be a barrier. Some owners seek OTC substitutes to save money, but for a genuine therapeutic need, the OTC food usually does not meet the same targets and is not equivalent. The cost is best weighed against the clinical benefit and the cost of poorly managed disease. See the [[Food Cost Calculator|/tools/food-cost-calculator]]." },
      { h2: 'Choosing Between Them', id: 'choosing' },
      { p: "For a diagnosed condition with a therapeutic diet validated in that disease, the prescription diet is usually the right choice, used under veterinary direction. For a healthy animal, an OTC complete-and-balanced diet is appropriate and a therapeutic diet is unnecessary and potentially harmful. The decision is driven by diagnosis: match the diet to the documented need, not to the marketing. See [[Scoring Methodology|/guides/methodology]]." },
    ],
    related: [
      { label: 'Kidney Disease Diets', href: '/diets/kidney-disease-diets' },
      { label: 'Food Allergy and Elimination Diets', href: '/diets/food-allergy-and-elimination-diets' },
      { label: 'Scoring Methodology', href: '/guides/methodology' },
    ],
    sources: [...STD],
  },

  {
    dir: D, slug: 'breed-specific-diets', date: '2026-06-01',
    title: 'Breed-Specific Diets — Useful or Marketing?',
    metaTitle: 'Are Breed-Specific Pet Diets Worth It? | PetFood.com',
    metaDesc:
      'What breed-specific diets actually change — kibble shape, calorie density, and breed-prevalent-condition targeting — and where the value is real versus marketing.',
    category: 'Food-Type Comparison', readTime: '9 min',
    hero:
      "Breed-specific diets — a formula for the Labrador, another for the Persian — are a prominent premium category, and the honest answer to whether they are worth it is: sometimes. Some breed-specific features address real breed predispositions; others are size-based generalizations dressed as breed precision. This page separates the substantive from the marketing.",
    toc: [
      { label: 'What They Claim', id: 'claim' },
      { label: 'Size-Based Reality', id: 'size' },
      { label: 'Kibble Shape', id: 'shape' },
      { label: 'Breed-Prevalent Conditions', id: 'conditions' },
      { label: 'The Marketing Layer', id: 'marketing' },
      { label: 'When It Is Worth It', id: 'worthit' },
    ],
    body: [
      { p: "Breed-specific diets are formulated and marketed for individual breeds, implying a precision-tailored nutrition. Some of what they offer is genuinely useful — addressing the calorie needs, kibble preferences, and disease predispositions that do vary by breed and size. But much of the differentiation is size-based or cosmetic, and the breed-precise framing often outruns the actual formulation differences. The category is a mix of substance and marketing. See [[How to Choose a Pet Food|/guides/how-to-choose-a-pet-food]]." },
      { h2: 'What They Claim', id: 'claim' },
      { p: "Breed-specific lines claim to tailor nutrition to a breed's unique needs — energy level, body type, coat, and predisposition to certain conditions. The implication is that a generic diet cannot serve a specific breed as well. Some of this is real; much is a premium-positioning narrative built on features that are really about size category." },
      { h2: 'Size-Based Reality', id: 'size' },
      { p: "Much of what breed-specific diets deliver is actually size-based: small breeds need energy-dense, small kibble and have different metabolic rates and dental profiles than large breeds, and large- and giant-breed needs (including the growth calcium ceiling) are well-established. A breed-specific diet for a giant breed largely reflects giant-breed nutrition, which a good large-breed diet also provides. The breed label often repackages size-appropriate formulation. See [[Large-Breed Puppy Nutrition|/feeding/large-breed-puppy-nutrition]]." },
      { h2: 'Kibble Shape', id: 'shape' },
      { p: "One genuine breed-specific feature is kibble shape and size designed for a breed's jaw and eating style — for example, a kibble shaped for a brachycephalic (flat-faced) breed like the Bulldog or Persian to pick up more easily, or a larger kibble to slow a fast-eating breed and encourage chewing. This is a real, if modest, functional tailoring that affects how easily and how fast a dog or cat eats. It is one of the more defensible breed-specific features." },
      { h2: 'Breed-Prevalent Conditions', id: 'conditions' },
      { p: "Some breed-specific diets target conditions a breed is prone to — added taurine for breeds at DCM risk, joint support for large breeds prone to arthritis, urinary support for breeds prone to stones, skin-and-coat support for coat-intensive breeds. Where the breed predisposition is real and the dietary lever is evidence-supported (such as omega-3s for joints), this targeting has value. But the same support is often available in a non-breed-labeled diet. See [[Joint and Mobility Diets|/diets/joint-and-mobility-diets]] and [[Grain-Free and DCM Risk|/ingredients/grain-free-dcm-risk]]." },
      { h2: 'The Marketing Layer', id: 'marketing' },
      { p: "Layered over the substantive features is a marketing premium: breed imagery, breed-precise naming, and the implication of bespoke formulation justify a higher price. The actual nutrient differences between a breed-specific diet and a well-matched size-and-life-stage diet are often small. As with all pet food, the regulated back of the bag and the manufacturer's substantiation matter more than the breed name on the front. See [[Pet Food Marketing Terms|/myths/marketing-terms-decoded]]." },
      { h2: 'When It Is Worth It', id: 'worthit' },
      { p: "A breed-specific diet is worth considering when its features address a real need for your animal — an appropriate kibble shape for a flat-faced breed, evidence-supported targeting of a genuine breed predisposition — and when it is otherwise a complete, well-substantiated diet from a transparent manufacturer. It is not worth a premium for breed branding alone. For most animals, a quality diet matched to size, life stage, and any medical needs serves as well. See [[How to Choose a Pet Food|/guides/how-to-choose-a-pet-food]]." },
    ],
    related: [
      { label: 'How to Choose a Pet Food', href: '/guides/how-to-choose-a-pet-food' },
      { label: 'Large-Breed Puppy Nutrition', href: '/feeding/large-breed-puppy-nutrition' },
      { label: 'Pet Food Marketing Terms', href: '/myths/marketing-terms-decoded' },
    ],
    sources: [...STD],
  },
]

export const COMPARE = RAW.map((p) => ({ ...p, hubName: 'Compare' }))
