import { SRC, STD } from './_shared.mjs'

const D = 'diets'
const VET_SRC =
  'American Animal Hospital Association (AAHA) and American College of Veterinary Internal Medicine (ACVIM) consensus statements and nutrition guidelines, as applicable to the condition.'

const RAW = [
  {
    dir: D, slug: 'kidney-disease-diets', date: '2026-06-01',
    title: 'Kidney Disease Diets for Dogs and Cats',
    metaTitle: 'Kidney Disease (Renal) Diets for Dogs and Cats | PetFood.com',
    metaDesc:
      'How therapeutic renal diets work — phosphorus and protein restriction, the IRIS staging framework, omega-3 and buffering, and why these diets require a diagnosis.',
    category: 'Condition-Specific Diet', readTime: '12 min',
    hero:
      "Chronic kidney disease is one of the most common conditions of older cats and a frequent diagnosis in older dogs, and diet is the single intervention with the strongest evidence for extending both lifespan and quality of life. Therapeutic renal diets are not a wellness category — they are formulated tools tied to a diagnosis and a staging system. This page explains the nutrient targets, the evidence, and why they require veterinary direction.",
    toc: [
      { label: 'What Renal Diets Do', id: 'whatdo' },
      { label: 'Phosphorus Restriction', id: 'phosphorus' },
      { label: 'Protein — Quality over Quantity', id: 'protein' },
      { label: 'IRIS Staging', id: 'iris' },
      { label: 'Other Modifications', id: 'other' },
      { label: 'Why a Diagnosis Is Required', id: 'diagnosis' },
    ],
    body: [
      { p: "Chronic kidney disease (CKD) is the progressive, irreversible loss of functioning kidney tissue. As nephrons are lost, the kidney becomes less able to excrete metabolic waste, regulate phosphorus and electrolytes, concentrate urine, and produce erythropoietin. Therapeutic renal diets are designed to reduce the workload on the remaining nephrons and to control the metabolic consequences of declining function. Multiple controlled studies have shown that dogs and cats fed a renal therapeutic diet live longer and experience fewer uremic crises than those kept on a maintenance diet." },
      { h2: 'What Renal Diets Do', id: 'whatdo' },
      { p: "A renal therapeutic diet differs from a maintenance diet in several coordinated ways: it restricts phosphorus, moderates and improves the quality of protein, often increases omega-3 fatty acids, adds buffering to counter metabolic acidosis, and supports caloric intake and palatability so the animal keeps eating. No single nutrient does the work alone — it is the combination, validated in feeding studies, that produces the survival benefit." },
      { h2: 'Phosphorus Restriction', id: 'phosphorus' },
      { p: "Phosphorus restriction is the best-supported element of renal nutrition. As the kidney fails, phosphorus accumulates, driving secondary hyperparathyroidism and contributing to further kidney damage. Renal diets sharply lower dietary phosphorus relative to maintenance foods, and where diet alone is insufficient, phosphorus binders are added under veterinary direction. Serum phosphorus targets are tied to disease stage. See [[Minerals in Pet Food|/nutrition/minerals-in-pet-food]]." },
      { h2: 'Protein — Quality over Quantity', id: 'protein' },
      { p: "Protein in renal diets is moderated and made highly digestible rather than simply slashed. Reducing protein lowers the nitrogenous-waste load the kidney must clear, easing uremic signs, but excessive restriction risks muscle loss, which is itself harmful — particularly in cats, whose obligate-carnivore metabolism makes severe protein restriction risky. The modern approach emphasizes high-biological-value protein at a moderated level, individualized to the patient and stage. See [[Dietary Protein Requirements|/nutrition/dietary-protein-requirements]]." },
      { h2: 'IRIS Staging', id: 'iris' },
      { p: "The International Renal Interest Society (IRIS) staging system classifies CKD into stages 1 through 4 based on creatinine and SDMA, with substaging by proteinuria and blood pressure. Dietary and medical recommendations are tied to stage: phosphorus targets tighten, and the timing of diet transition is guided by the stage at diagnosis. This staging framework is why a renal diet is a medical decision, not a shelf choice — the right diet and target depend on bloodwork the owner cannot perform." },
      { h2: 'Other Modifications', id: 'other' },
      { p: "Renal diets typically add EPA and DHA omega-3 fatty acids, which have evidence for slowing progression; potassium supplementation (cats with CKD are prone to hypokalemia); alkalinizing agents to counter metabolic acidosis; B-vitamin supplementation to replace losses in dilute urine; and high moisture (canned formats) to support hydration in animals that can no longer concentrate urine. See [[Water and Hydration|/nutrition/water-and-hydration]] and [[Fish Oil and Omega-3|/supplements/fish-oil-omega-3]]." },
      { h2: 'Why a Diagnosis Is Required', id: 'diagnosis' },
      { p: "Renal diets are therapeutic foods sold for diagnosed kidney disease. Feeding a phosphorus- and protein-restricted diet to a healthy animal that does not need it provides no benefit and can cause harm, particularly to growing animals and to cats. Diagnosis, staging, and diet selection require bloodwork, urinalysis, and ongoing monitoring by a veterinarian. This page is reference material, not a treatment plan." },
    ],
    related: [
      { label: 'Minerals in Pet Food', href: '/nutrition/minerals-in-pet-food' },
      { label: 'Senior Pet Diets', href: '/diets/senior-pet-diets' },
      { label: 'Water and Hydration', href: '/nutrition/water-and-hydration' },
    ],
    sources: [...STD, VET_SRC],
  },

  {
    dir: D, slug: 'food-allergy-and-elimination-diets', date: '2026-06-01',
    title: 'Food Allergy and Elimination Diets',
    metaTitle: 'Food Allergy and Elimination Diets for Pets | PetFood.com',
    metaDesc:
      'How cutaneous adverse food reactions are diagnosed, the elimination-diet trial, novel-protein vs hydrolyzed diets, and why over-the-counter limited-ingredient foods often fail.',
    category: 'Condition-Specific Diet', readTime: '12 min',
    hero:
      "Food allergy in dogs and cats is real but less common than the marketing suggests, and it cannot be diagnosed by a blood or saliva test. The only validated diagnostic is a strict elimination-diet trial, and the diets that work are specific — novel-protein or hydrolyzed — and easy to undermine. This page covers the diagnosis, the diet options, and the pitfalls.",
    toc: [
      { label: 'What Food Allergy Is', id: 'whatis' },
      { label: 'Diagnosis — The Elimination Trial', id: 'trial' },
      { label: 'Novel-Protein Diets', id: 'novel' },
      { label: 'Hydrolyzed Diets', id: 'hydrolyzed' },
      { label: 'Why OTC Limited-Ingredient Foods Fail', id: 'otc' },
      { label: 'The Provocation Step', id: 'provocation' },
    ],
    body: [
      { p: "Cutaneous adverse food reaction (the precise term for what owners call food allergy) is an immune or non-immune reaction to a dietary protein that produces itching, recurrent skin and ear infections, and sometimes gastrointestinal signs. The most common culprit proteins in dogs are beef, dairy, chicken, and wheat; in cats, beef, dairy, and fish. Importantly, the allergen is almost always a protein the animal has eaten before — grain is a far less common trigger than the grain-free narrative implies." },
      { h2: 'What Food Allergy Is', id: 'whatis' },
      { p: "Food allergy is one of several causes of itch in dogs and cats, alongside environmental allergy (atopic dermatitis), flea allergy, and parasites. It is frequently overdiagnosed by owners and overpromised by products. There is no validated blood, saliva, or hair test for food allergy; the serum and saliva tests marketed to owners have repeatedly failed validation studies, returning positives for water and for foods the animal has never eaten." },
      { h2: 'Diagnosis — The Elimination Trial', id: 'trial' },
      { p: "The only reliable diagnostic is a strict elimination-diet trial: feed a diet containing a protein and carbohydrate source the animal has never encountered (or a hydrolyzed protein) and nothing else — no treats, flavored medications, table scraps, or flavored toothpaste — for a defined period, typically 8 to 12 weeks, then assess whether signs resolve. The strictness is the hard part and the most common reason trials fail." },
      { h2: 'Novel-Protein Diets', id: 'novel' },
      { p: "A novel-protein diet uses a protein the individual animal has not previously eaten — venison, rabbit, kangaroo, duck, or insect protein, paired with an unusual carbohydrate. The logic is that the immune system has not been sensitized to a protein it has never seen. The challenge is finding a genuinely novel protein given how many proteins are now in mainstream foods and treats, and the risk of cross-contamination in non-veterinary novel-protein products. See [[Animal Protein Sources|/ingredients/animal-protein-sources]]." },
      { h2: 'Hydrolyzed Diets', id: 'hydrolyzed' },
      { p: "Hydrolyzed-protein diets break the protein into peptide fragments small enough that the immune system is less likely to recognize them as an allergen. These are veterinary therapeutic diets (such as those built on hydrolyzed soy or hydrolyzed chicken liver), and the degree of hydrolysis matters — lower-molecular-weight hydrolysates are used when standard ones fail. Hydrolyzed diets sidestep the difficulty of sourcing a truly novel protein. See [[Hydrolyzed and Novel-Protein Diets|/diets/hydrolyzed-protein-diets]]." },
      { h2: 'Why OTC Limited-Ingredient Foods Fail', id: 'otc' },
      { p: "Over-the-counter limited-ingredient diets are not equivalent to veterinary elimination diets. Independent testing has repeatedly found undeclared proteins (commonly chicken, beef, or soy) in OTC limited-ingredient foods, because the same production lines run multiple formulas and cross-contamination occurs. A diet that secretly contains the offending protein cannot serve as a diagnostic trial. Veterinary therapeutic elimination diets are manufactured to avoid this contamination." },
      { h2: 'The Provocation Step', id: 'provocation' },
      { p: "A properly conducted trial does not end when signs resolve — it ends with provocation: reintroducing the original diet to confirm that signs return, which proves the response was diet-related rather than coincidental (or due to seasonal change in environmental allergy). Only after a positive provocation is food allergy confirmed; individual ingredients can then be reintroduced to identify the specific trigger. This entire process should be directed by a veterinarian." },
    ],
    related: [
      { label: 'Hydrolyzed and Novel-Protein Diets', href: '/diets/hydrolyzed-protein-diets' },
      { label: 'Animal Protein Sources', href: '/ingredients/animal-protein-sources' },
      { label: 'Limited-Ingredient Diets Myth', href: '/myths/limited-ingredient-diet-myth' },
    ],
    sources: [...STD, VET_SRC],
  },

  {
    dir: D, slug: 'weight-management-diets', date: '2026-06-01',
    title: 'Weight-Management Diets',
    metaTitle: 'Weight-Loss and Weight-Management Diets for Pets | PetFood.com',
    metaDesc:
      'How weight-loss diets work — calorie restriction, protein-sparing, fiber satiety, the difference between light and therapeutic metabolic diets, and safe rate of loss.',
    category: 'Condition-Specific Diet', readTime: '11 min',
    hero:
      "More than half of dogs and cats in many surveys are overweight or obese, and excess weight shortens lifespan and worsens nearly every chronic disease. Weight-management diets are designed to create a calorie deficit while preserving lean mass and keeping the animal satisfied. This page covers how they work, the difference between light foods and therapeutic metabolic diets, and how to lose weight safely.",
    toc: [
      { label: 'The Scale of the Problem', id: 'problem' },
      { label: 'How Weight-Loss Diets Work', id: 'howwork' },
      { label: 'Light vs Therapeutic Diets', id: 'lightvstherapeutic' },
      { label: 'Protein-Sparing', id: 'protein' },
      { label: 'Satiety and Fiber', id: 'satiety' },
      { label: 'Safe Rate of Loss', id: 'rate' },
    ],
    body: [
      { p: "Obesity in pets is a clinical disease, not a cosmetic issue. Excess adipose tissue is metabolically active and pro-inflammatory, and obesity is associated with shortened lifespan, osteoarthritis, diabetes (especially in cats), respiratory compromise, and reduced quality of life. A landmark lifetime study in Labrador Retrievers found that dogs kept lean lived roughly two years longer than their overweight littermates. Weight management is among the highest-impact nutritional interventions available." },
      { h2: 'The Scale of the Problem', id: 'problem' },
      { p: "Body condition is assessed on a 9-point body condition score (BCS), where 4 to 5 is ideal; each point above 5 represents roughly 10 to 15 percent over ideal weight. Most owners underestimate their pet's body condition. Establishing the ideal target weight is the first step, and it should be set by a veterinarian based on frame and BCS, not by breed-average tables. See [[Body Condition Scoring|/feeding/body-condition-scoring]]." },
      { h2: 'How Weight-Loss Diets Work', id: 'howwork' },
      { p: "Weight loss requires a sustained calorie deficit. A weight-loss diet achieves this while avoiding the trap of simply feeding less of a maintenance food — which would also cut protein, vitamins, and minerals below requirement. Instead, these diets are formulated with reduced calorie density and increased protein and micronutrient density, so the animal eats a satisfying volume and meets nutrient needs while taking in fewer calories. See [[Pet Food Calories and Energy Density|/nutrition/calories-and-energy-density]]." },
      { h2: 'Light vs Therapeutic Metabolic Diets', id: 'lightvstherapeutic' },
      { p: "Over-the-counter light or weight-management foods carry modest calorie reductions and are aimed at preventing gain or supporting gentle loss. Therapeutic metabolic diets, available through veterinarians, are more aggressively formulated for active weight loss in obese patients and are paired with a structured plan and monitoring. AAFCO defines the terms light, lean, and low calorie with specific maximum calorie thresholds, so those claims are meaningful, but they are not the same as a supervised therapeutic program." },
      { h2: 'Protein-Sparing', id: 'protein' },
      { p: "During calorie restriction, the body can break down muscle as well as fat. Higher dietary protein during weight loss spares lean mass, so the weight lost is preferentially fat. This is why weight-loss diets are protein-dense relative to their calories. Preserving muscle matters for metabolic rate and for function, particularly in older animals. See [[Dietary Protein Requirements|/nutrition/dietary-protein-requirements]]." },
      { h2: 'Satiety and Fiber', id: 'satiety' },
      { p: "Eating less is hard on the animal and on the owner who faces the begging. Weight-loss diets use increased fiber and protein, and sometimes increased dietary water, to promote satiety so the animal feels full on fewer calories. Some diets manipulate the fiber blend specifically for the satiety effect. Measured feeding with a kitchen scale, scheduled meals, and substituting low-calorie enrichment for food treats all support adherence." },
      { h2: 'Safe Rate of Loss', id: 'rate' },
      { p: "Weight should come off gradually: roughly 1 to 2 percent of body weight per week is a common safe target, individualized by the veterinarian. Cats in particular must not lose weight too fast — rapid weight loss or anorexia in an overweight cat can precipitate hepatic lipidosis, a life-threatening liver condition. Any weight-loss program should include regular weigh-ins and reassessment of the plan. See [[Body Condition Scoring|/feeding/body-condition-scoring]]." },
    ],
    related: [
      { label: 'Body Condition Scoring', href: '/feeding/body-condition-scoring' },
      { label: 'Pet Food Calories and Energy Density', href: '/nutrition/calories-and-energy-density' },
      { label: 'Diabetic Diets for Dogs and Cats', href: '/diets/diabetic-diets' },
    ],
    sources: [...STD, VET_SRC],
  },

  {
    dir: D, slug: 'diabetic-diets', date: '2026-06-01',
    title: 'Diabetic Diets for Dogs and Cats',
    metaTitle: 'Diabetic Diets for Dogs and Cats | PetFood.com',
    metaDesc:
      'How diet supports diabetes management — the species split between low-carb feline and high-fiber canine approaches, consistency, and the link to weight and remission.',
    category: 'Condition-Specific Diet', readTime: '11 min',
    hero:
      "Diabetes mellitus is managed primarily with insulin, but diet is a powerful co-therapy — and the dietary approach differs sharply between cats and dogs because their diabetes differs. For cats, a low-carbohydrate diet can even support remission. This page covers the species split, the role of consistency, and the central importance of body weight.",
    toc: [
      { label: 'Two Different Diseases', id: 'twodiseases' },
      { label: 'Feline — Low Carbohydrate', id: 'feline' },
      { label: 'Canine — Consistency and Fiber', id: 'canine' },
      { label: 'Consistency and Timing', id: 'consistency' },
      { label: 'Weight and Remission', id: 'weight' },
      { label: 'Coordinating with Insulin', id: 'insulin' },
    ],
    body: [
      { p: "Diabetes mellitus results from inadequate insulin action, leading to high blood glucose. The condition is common in middle-aged and older cats and dogs, and while insulin therapy is the foundation of treatment, diet meaningfully influences glycemic control, insulin requirements, and — in cats — the chance of remission. The right dietary approach depends on which species and which form of diabetes is present." },
      { h2: 'Two Different Diseases', id: 'twodiseases' },
      { p: "Feline diabetes resembles human type 2 diabetes: it is closely tied to obesity and insulin resistance, and the high-carbohydrate diets historically common in cat food are implicated. Canine diabetes more often resembles type 1, with absolute insulin deficiency, frequently following pancreatitis or immune destruction of the beta cells. Because the underlying problem differs, the dietary strategy differs." },
      { h2: 'Feline Diabetes — Low Carbohydrate', id: 'feline' },
      { p: "For diabetic cats, a low-carbohydrate, high-protein diet reduces post-meal glucose spikes and lowers insulin requirements. Multiple studies show diabetic cats fed low-carbohydrate diets are more likely to achieve remission — a state where they no longer require insulin — particularly when the diet is combined with weight loss and good glycemic control early in the disease. Canned diets make a low-carbohydrate target easier to hit than kibble. See [[Carbohydrates in Pet Food|/nutrition/carbohydrates-in-pet-food]]." },
      { h2: 'Canine Diabetes — Consistency and Fiber', id: 'canine' },
      { p: "For diabetic dogs, the emphasis is less on slashing carbohydrate and more on consistency and on moderating the glycemic response. Diets with increased fiber and complex carbohydrate slow glucose absorption and blunt post-meal spikes, smoothing the glucose curve that insulin must match. The most important dietary factor in dogs is feeding the same food in the same amount at the same times every day." },
      { h2: 'Consistency and Timing', id: 'consistency' },
      { p: "Whatever the species, diabetic feeding must be consistent. Meals are typically timed to insulin injections so that the glucose load and the insulin peak coincide. Erratic feeding, treats of unknown calorie content, and free-choice grazing all destabilize glucose control. Diabetic management is built on a fixed, measured routine." },
      { h2: 'Weight and Remission', id: 'weight' },
      { p: "Obesity drives insulin resistance, so weight loss in overweight diabetic animals improves control and, in cats, raises the chance of remission. Conversely, many diabetic dogs are diagnosed after weight loss and need their weight stabilized. Body condition management is integral to diabetic feeding. See [[Weight-Management Diets|/diets/weight-management-diets]] and [[Body Condition Scoring|/feeding/body-condition-scoring]]." },
      { h2: 'Coordinating with Insulin', id: 'insulin' },
      { p: "Diet changes alter insulin requirements, so any dietary change in a diabetic animal must be coordinated with the veterinarian and accompanied by glucose monitoring — switching a diabetic cat to a low-carbohydrate diet can drop insulin needs quickly, risking hypoglycemia if the insulin dose is not adjusted. Diabetic diet selection is a medical decision made with the treating veterinarian, not a standalone choice." },
    ],
    related: [
      { label: 'Carbohydrates in Pet Food', href: '/nutrition/carbohydrates-in-pet-food' },
      { label: 'Weight-Management Diets', href: '/diets/weight-management-diets' },
      { label: 'Body Condition Scoring', href: '/feeding/body-condition-scoring' },
    ],
    sources: [...STD, VET_SRC],
  },

  {
    dir: D, slug: 'senior-pet-diets', date: '2026-06-01',
    title: 'Senior Pet Diets',
    metaTitle: 'Senior Dog and Cat Diets — What Changes | PetFood.com',
    metaDesc:
      'What senior nutrition actually means without an AAFCO senior life stage, the energy and protein debate, supporting muscle mass, and tailoring to age-related disease.',
    category: 'Condition-Specific Diet', readTime: '11 min',
    hero:
      "Senior is the most-marketed and least-regulated label on a pet food bag. There is no AAFCO senior life stage, so a senior diet can legally be almost anything. The real nutritional questions of aging — preserving muscle, adjusting calories, and tailoring to emerging disease — are more nuanced than the bag suggests. This page separates the marketing from the physiology.",
    toc: [
      { label: 'There Is No AAFCO Senior Stage', id: 'noaafco' },
      { label: 'What Changes with Age', id: 'changes' },
      { label: 'The Protein Debate', id: 'protein' },
      { label: 'Energy and Body Condition', id: 'energy' },
      { label: 'Tailoring to Disease', id: 'disease' },
      { label: 'Choosing a Senior Food', id: 'choosing' },
    ],
    body: [
      { p: "Dogs and cats are generally considered senior in the last quarter to third of their expected lifespan — roughly 7 years and up for many dogs (earlier for giant breeds), and 10 to 11 years and up for cats, with cats over 15 sometimes termed geriatric. Aging brings real physiological changes, but the senior pet food category is unregulated, and a senior diet must be evaluated on its actual formulation, not its label claim." },
      { h2: 'There Is No AAFCO Senior Stage', id: 'noaafco' },
      { p: "AAFCO recognizes growth, reproduction, adult maintenance, and all life stages — there is no senior or mature category. A food labeled senior is sold under the adult-maintenance designation, and its nutrient profile need only meet the adult-maintenance minimums. This means senior diets vary enormously: some are lower in calories, some higher in protein, some add joint or cognitive support, and some differ from the brand's adult food only in name. See [[Pet Food by Life Stage|/life-stage]]." },
      { h2: 'What Changes with Age', id: 'changes' },
      { p: "Aging animals tend to lose lean muscle mass (sarcopenia), may digest and absorb nutrients less efficiently, are more prone to dental disease affecting food choice, and have a rising prevalence of chronic conditions — kidney disease and hyperthyroidism in cats, osteoarthritis and cognitive decline in dogs. Nutritional needs in old age are therefore better individualized than generalized." },
      { h2: 'The Protein Debate', id: 'protein' },
      { p: "Older thinking restricted protein in healthy seniors out of concern for the kidneys, but current evidence does not support protein restriction in healthy older animals — adequate high-quality protein helps counter age-related muscle loss. Protein restriction is appropriate for animals with diagnosed kidney disease, but that is a disease-specific decision, not a blanket senior recommendation. See [[Dietary Protein Requirements|/nutrition/dietary-protein-requirements]] and [[Kidney Disease Diets|/diets/kidney-disease-diets]]." },
      { h2: 'Energy and Body Condition', id: 'energy' },
      { p: "Many middle-aged and early-senior animals have lower energy needs and are prone to weight gain, favoring a lower-calorie diet. But the oldest animals often have the opposite problem — reduced appetite, weight loss, and muscle wasting — and need energy- and protein-dense, palatable food to maintain condition. Body condition and muscle assessment, not age alone, should drive the calorie decision. See [[Body Condition Scoring|/feeding/body-condition-scoring]]." },
      { h2: 'Tailoring to Disease', id: 'disease' },
      { p: "The most valuable nutritional decisions in old age are condition-specific: a renal diet for diagnosed kidney disease, a joint diet with omega-3s and glucosamine for osteoarthritis, a diet supporting cognitive function (with antioxidants and medium-chain triglycerides) for canine cognitive dysfunction. These are targeted interventions tied to a diagnosis, far more useful than a generic senior label. See [[Joint and Mobility Diets|/diets/joint-and-mobility-diets]]." },
      { h2: 'Choosing a Senior Food', id: 'choosing' },
      { p: "Because senior is unregulated, evaluate the actual diet: confirm it is complete and balanced for adult maintenance, check the calorie density against your animal's body condition, confirm adequate high-quality protein, and look for evidence-supported additions (EPA/DHA, antioxidants) rather than marketing buzzwords. For an animal with a diagnosed condition, a targeted therapeutic diet usually beats a generic senior food." },
    ],
    related: [
      { label: 'Kidney Disease Diets', href: '/diets/kidney-disease-diets' },
      { label: 'Joint and Mobility Diets', href: '/diets/joint-and-mobility-diets' },
      { label: 'Pet Food by Life Stage', href: '/life-stage' },
    ],
    sources: [...STD, VET_SRC],
  },

  {
    dir: D, slug: 'urinary-tract-diets', date: '2026-06-01',
    title: 'Urinary and Bladder Stone Diets',
    metaTitle: 'Urinary Tract and Bladder Stone Diets for Pets | PetFood.com',
    metaDesc:
      'How urinary diets manage struvite and calcium-oxalate stones and FLUTD — urine pH, mineral targets, dilution, and why stone type determines the diet.',
    category: 'Condition-Specific Diet', readTime: '11 min',
    hero:
      "Urinary therapeutic diets manage two of the most common lower-urinary-tract problems: mineral stones (uroliths) and feline idiopathic cystitis. The right diet depends entirely on the stone type, because the diet that dissolves one stone can promote another. This page covers struvite versus calcium oxalate, urine pH and dilution, and the central role of water.",
    toc: [
      { label: 'The Lower Urinary Tract', id: 'lut' },
      { label: 'Struvite Stones', id: 'struvite' },
      { label: 'Calcium Oxalate Stones', id: 'oxalate' },
      { label: 'Urine pH and Minerals', id: 'ph' },
      { label: 'Dilution and Moisture', id: 'dilution' },
      { label: 'Feline Idiopathic Cystitis', id: 'fic' },
    ],
    body: [
      { p: "Lower urinary tract disease in dogs and cats includes uroliths (bladder stones), urethral plugs, infection, and — in cats especially — idiopathic cystitis. Diet is a cornerstone of both treating and preventing mineral stones, and stone composition determines everything: the dietary changes that dissolve a struvite stone can worsen a calcium-oxalate stone, so a diagnosis of stone type, ideally by analysis of a retrieved stone, must precede the diet decision." },
      { h2: 'The Lower Urinary Tract', id: 'lut' },
      { p: "Uroliths form when urine becomes supersaturated with stone-forming minerals. The two most common types in dogs and cats are struvite (magnesium ammonium phosphate) and calcium oxalate. Their behavior is opposite in important ways: struvite can often be dissolved medically and is influenced by infection and pH, while calcium oxalate cannot be dissolved by diet and must be managed by prevention after surgical or other removal." },
      { h2: 'Struvite Stones', id: 'struvite' },
      { p: "In cats, struvite stones are usually sterile and diet-responsive; therapeutic struvite-dissolution diets acidify the urine and restrict magnesium and phosphorus, dissolving existing stones over weeks and preventing recurrence. In dogs, struvite stones are most often associated with urinary tract infection, so treatment combines an appropriate diet with antibiotic therapy directed at the infection. Dissolution diets are used short-term and require veterinary monitoring." },
      { h2: 'Calcium Oxalate Stones', id: 'oxalate' },
      { p: "Calcium oxalate stones cannot be dissolved by diet — they must be removed, then prevented. Prevention diets aim to reduce urinary calcium and oxalate saturation, avoid over-acidifying the urine (excessive acidification promotes oxalate), and most importantly maximize urine dilution. Calcium-oxalate prevalence has risen alongside the use of acidifying struvite diets, illustrating why matching the diet to the stone type matters." },
      { h2: 'Urine pH and Minerals', id: 'ph' },
      { p: "Urine pH strongly influences which minerals precipitate: alkaline urine favors struvite, while excessively acidic urine favors calcium oxalate. Urinary diets manipulate pH through dietary cation-anion balance and restrict the relevant minerals (magnesium and phosphorus for struvite). Because the two stone types pull pH in opposite directions, a one-size urinary diet does not exist. See [[Minerals in Pet Food|/nutrition/minerals-in-pet-food]]." },
      { h2: 'Dilution and Moisture', id: 'dilution' },
      { p: "Diluting the urine reduces mineral supersaturation regardless of stone type and is the single most broadly beneficial strategy. Urinary diets often include added sodium to stimulate drinking and increase urine volume, and a canned (high-moisture) format helps enormously, especially in cats with their weak thirst drive. Increasing water intake is first-line for prevention of both stone types and for cystitis. See [[Water and Hydration|/nutrition/water-and-hydration]]." },
      { h2: 'Feline Idiopathic Cystitis', id: 'fic' },
      { p: "Feline idiopathic cystitis (FIC) is bladder inflammation with no identifiable cause, strongly associated with stress, and the most common reason for lower-urinary signs in young to middle-aged cats. Management is multimodal: increasing water intake (often via canned food), environmental enrichment and stress reduction, and sometimes diets formulated to support urinary health and reduce recurrence. Diet alone does not treat FIC; it is part of a broader plan with the veterinarian." },
    ],
    related: [
      { label: 'Water and Hydration', href: '/nutrition/water-and-hydration' },
      { label: 'Minerals in Pet Food', href: '/nutrition/minerals-in-pet-food' },
      { label: 'Wet vs Dry Food', href: '/compare/wet-vs-dry-food' },
    ],
    sources: [...STD, VET_SRC],
  },

  {
    dir: D, slug: 'fiber-and-digestive-health', date: '2026-06-01',
    title: 'Fiber and Digestive Health Diets',
    metaTitle: 'Fiber and Digestive Health Diets for Pets | PetFood.com',
    metaDesc:
      'How fiber type and gastrointestinal diets manage diarrhea, constipation, IBD, and colitis — soluble vs insoluble fiber, prebiotics, digestibility, and fat level.',
    category: 'Condition-Specific Diet', readTime: '11 min',
    hero:
      "Gastrointestinal therapeutic diets are among the most-used veterinary diets, because digestive upset is one of the most common reasons pets visit the clinic. The tools are highly digestible ingredients, adjusted fat, and — above all — carefully chosen fiber. This page explains how fiber type drives the effect and how GI diets manage diarrhea, constipation, and inflammatory bowel disease.",
    toc: [
      { label: 'Fiber Types', id: 'fibertypes' },
      { label: 'Highly Digestible GI Diets', id: 'digestible' },
      { label: 'Diarrhea and Colitis', id: 'diarrhea' },
      { label: 'Constipation and Megacolon', id: 'constipation' },
      { label: 'Inflammatory Bowel Disease', id: 'ibd' },
      { label: 'Prebiotics and the Microbiome', id: 'prebiotics' },
    ],
    body: [
      { p: "Fiber is the indigestible carbohydrate fraction of the diet, and its functional effects depend on type. Gastrointestinal therapeutic diets manipulate fiber, fat, and ingredient digestibility to manage a wide range of digestive disorders. The same nutritional category can be tuned in opposite directions — a low-residue highly digestible diet for one problem, a high-fiber bulking diet for another — which is why GI diets are matched to the specific disorder." },
      { h2: 'Fiber Types — Soluble vs Insoluble', id: 'fibertypes' },
      { p: "Insoluble fiber (cellulose, many vegetable fibers) adds bulk, speeds transit in constipation, and firms stool. Soluble and fermentable fibers (beet pulp, psyllium, inulin, fructooligosaccharides) absorb water, slow transit, and feed colonic bacteria that produce short-chain fatty acids nourishing the gut lining. Many GI diets use a blend tuned to the disorder. See [[Carbohydrates in Pet Food|/nutrition/carbohydrates-in-pet-food]]." },
      { h2: 'Highly Digestible GI Diets', id: 'digestible' },
      { p: "For acute and many chronic digestive upsets, a highly digestible, low-residue diet reduces the workload on an inflamed gut: high-quality protein, easily digested carbohydrate, moderated fat, and modest fiber so that more nutrient is absorbed in the small intestine and less reaches the colon. These diets are the workhorses of GI management and are often the first dietary step in vomiting and diarrhea cases once a diet trial is indicated." },
      { h2: 'Diarrhea and Colitis', id: 'diarrhea' },
      { p: "Large-bowel diarrhea and colitis (inflammation of the colon) often respond to added fermentable fiber, which normalizes colonic motility and feeds beneficial bacteria. Small-bowel diarrhea more often calls for a highly digestible, moderate-fat diet. Because fat maldigestion worsens some diarrheas, fat level is a key lever. Persistent or bloody diarrhea requires veterinary diagnosis before a diet is chosen." },
      { h2: 'Constipation and Megacolon', id: 'constipation' },
      { p: "Constipation, common in older cats and in cats with megacolon, is managed with increased dietary fiber to add bulk and stimulate motility, alongside aggressive hydration. In some cats a low-residue diet that produces less stool volume is preferred over a high-fiber approach, depending on the severity — illustrating again that fiber strategy is individualized. Adequate water intake is essential. See [[Water and Hydration|/nutrition/water-and-hydration]]." },
      { h2: 'Inflammatory Bowel Disease', id: 'ibd' },
      { p: "Inflammatory bowel disease (IBD) is chronic gut inflammation managed with diet and, often, medication. Dietary approaches include highly digestible diets, novel-protein or hydrolyzed diets (since dietary antigen drives some cases), and fiber adjustment. A subset of IBD cases respond to diet alone (food-responsive enteropathy), which is why a controlled diet trial is part of the work-up. See [[Hydrolyzed and Novel-Protein Diets|/diets/hydrolyzed-protein-diets]]." },
      { h2: 'Prebiotics and the Microbiome', id: 'prebiotics' },
      { p: "Prebiotics are fermentable fibers (such as fructooligosaccharides and inulin) that selectively feed beneficial gut bacteria, and many GI diets include them. The gut microbiome is increasingly recognized as central to digestive and immune health, and dietary fiber is the primary lever owners have to shape it. Probiotic supplements are a separate, complementary tool. See [[Probiotics for Pets|/supplements/probiotics-for-pets]]." },
    ],
    related: [
      { label: 'Carbohydrates in Pet Food', href: '/nutrition/carbohydrates-in-pet-food' },
      { label: 'Probiotics for Pets', href: '/supplements/probiotics-for-pets' },
      { label: 'Hydrolyzed and Novel-Protein Diets', href: '/diets/hydrolyzed-protein-diets' },
    ],
    sources: [...STD, VET_SRC],
  },

  {
    dir: D, slug: 'liver-disease-diets', date: '2026-06-01',
    title: 'Liver Disease Diets',
    metaTitle: 'Liver (Hepatic) Disease Diets for Dogs and Cats | PetFood.com',
    metaDesc:
      'How hepatic diets support the diseased liver — protein quality and hepatic encephalopathy, copper restriction, antioxidants, and the feline anorexia risk.',
    category: 'Condition-Specific Diet', readTime: '10 min',
    hero:
      "The liver is central to metabolism, and liver disease demands a careful nutritional balance — enough high-quality protein to support regeneration without overwhelming a compromised organ, plus management of copper, antioxidants, and (in cats) the ever-present risk of anorexia. This page covers the principles of hepatic nutrition and why they are tightly disease-specific.",
    toc: [
      { label: 'The Liver in Nutrition', id: 'liver' },
      { label: 'Protein and Encephalopathy', id: 'protein' },
      { label: 'Copper-Associated Disease', id: 'copper' },
      { label: 'Antioxidants and Support', id: 'antioxidants' },
      { label: 'The Feline Anorexia Risk', id: 'feline' },
      { label: 'Individualizing the Diet', id: 'individual' },
    ],
    body: [
      { p: "The liver processes nutrients, synthesizes proteins, detoxifies metabolic waste, and stores vitamins and minerals. Liver disease ranges from copper-associated hepatopathy and chronic hepatitis to portosystemic shunts and hepatic lipidosis, and the dietary needs differ by diagnosis. The shared goals are to support hepatic regeneration, minimize the buildup of toxins the failing liver cannot clear, and maintain adequate intake and body condition." },
      { h2: 'The Liver in Nutrition', id: 'liver' },
      { p: "Because the liver is so metabolically central, its disease affects protein metabolism, ammonia handling, copper storage, vitamin status, and energy balance. Unlike some organ-failure diets, hepatic diets generally do not severely restrict protein — the liver needs protein to regenerate — but they emphasize protein quality and may moderate quantity only when specific complications arise." },
      { h2: 'Protein and Hepatic Encephalopathy', id: 'protein' },
      { p: "In advanced liver disease or portosystemic shunts, the liver cannot clear ammonia from protein metabolism, and ammonia accumulation causes hepatic encephalopathy (neurological signs). For these patients, protein is moderated and shifted toward highly digestible, plant- and dairy-based sources that produce less ammonia, alongside medical management. For most other liver patients, adequate high-quality protein is maintained, because excessive restriction impairs recovery." },
      { h2: 'Copper-Associated Disease', id: 'copper' },
      { p: "Some dogs accumulate copper in the liver, causing progressive damage — a problem with a strong breed predisposition in Bedlington Terriers, Labrador Retrievers, Dobermans, and others. Management includes copper-restricted diets and avoidance of copper-rich foods and supplements. Rising dietary copper levels in commercial foods have drawn recent scrutiny for this reason. Hepatic therapeutic diets are formulated low in copper. See [[Minerals in Pet Food|/nutrition/minerals-in-pet-food]]." },
      { h2: 'Antioxidants and Support', id: 'antioxidants' },
      { p: "Liver disease generates oxidative stress, so hepatic diets and supportive supplements often emphasize antioxidants — vitamin E, S-adenosylmethionine (SAMe), silybin (milk thistle), and zinc. Adequate B-vitamins and, in some cases, L-carnitine are also supported. These are used under veterinary direction as part of a hepatic-support protocol rather than as routine wellness additions." },
      { h2: 'The Feline Anorexia Risk', id: 'feline' },
      { p: "In cats, the overriding nutritional priority in liver disease is preventing anorexia. A cat that stops eating, especially an overweight cat, can develop hepatic lipidosis — fat accumulation in the liver — which is itself a life-threatening liver disease. Maintaining caloric intake, by assisted or tube feeding if necessary, can take precedence over feeding the theoretically ideal hepatic diet. Palatability and intake are paramount in feline hepatic care." },
      { h2: 'Individualizing the Diet', id: 'individual' },
      { p: "Because liver disease is so varied, there is no single hepatic diet that fits every patient — the plan depends on the specific diagnosis, the presence of encephalopathy or copper accumulation, the species, and the animal's appetite. Hepatic nutrition must be directed by the veterinarian managing the case, with monitoring of liver values and body condition over time." },
    ],
    related: [
      { label: 'Minerals in Pet Food', href: '/nutrition/minerals-in-pet-food' },
      { label: 'Dietary Protein Requirements', href: '/nutrition/dietary-protein-requirements' },
      { label: 'Pancreatitis and Low-Fat Diets', href: '/diets/pancreatitis-low-fat-diets' },
    ],
    sources: [...STD, VET_SRC],
  },

  {
    dir: D, slug: 'pancreatitis-low-fat-diets', date: '2026-06-01',
    title: 'Pancreatitis and Low-Fat Diets',
    metaTitle: 'Pancreatitis and Low-Fat Diets for Dogs and Cats | PetFood.com',
    metaDesc:
      'Why dietary fat matters in pancreatitis, the difference between canine and feline disease, low-fat diet targets, treat discipline, and managing recurrence.',
    category: 'Condition-Specific Diet', readTime: '10 min',
    hero:
      "Pancreatitis is painful, sometimes life-threatening, and strongly linked to dietary fat in dogs. Long-term management hinges on a low-fat diet and the discipline to keep high-fat treats and scraps out of reach. The feline picture differs. This page covers the fat connection, the species split, and how to read fat content for a pancreatitis-prone animal.",
    toc: [
      { label: 'What Pancreatitis Is', id: 'whatis' },
      { label: 'The Fat Connection in Dogs', id: 'dogfat' },
      { label: 'Feline Pancreatitis', id: 'feline' },
      { label: 'Low-Fat Diet Targets', id: 'targets' },
      { label: 'Treats and Scraps', id: 'treats' },
      { label: 'Managing Recurrence', id: 'recurrence' },
    ],
    body: [
      { p: "Pancreatitis is inflammation of the pancreas, in which digestive enzymes activate prematurely and damage the organ. It ranges from mild and self-limiting to severe and fatal. In dogs it is frequently triggered by a high-fat meal — the classic case follows a holiday when the dog ate fatty table food — and dietary fat management is central to prevention. The condition can become chronic and recurrent, making long-term diet a priority." },
      { h2: 'What Pancreatitis Is', id: 'whatis' },
      { p: "The pancreas produces digestive enzymes and insulin. In pancreatitis, enzyme activation within the gland causes inflammation, pain, vomiting, and in severe cases systemic illness. Acute pancreatitis requires immediate veterinary care; chronic or recurrent pancreatitis is managed largely through diet. Repeated episodes can damage the pancreas enough to cause diabetes or exocrine pancreatic insufficiency." },
      { h2: 'The Fat Connection in Dogs', id: 'dogfat' },
      { p: "Dietary fat strongly stimulates pancreatic secretion, and high-fat meals are a well-documented trigger for canine pancreatitis, especially in predisposed breeds such as Miniature Schnauzers (often associated with high blood triglycerides). For dogs with a history of pancreatitis, a sustained low-fat diet reduces the risk of recurrence. Fat must be controlled not only in the main diet but across every treat and table scrap. See [[Dietary Fat and Essential Fatty Acids|/nutrition/dietary-fat-and-fatty-acids]]." },
      { h2: 'Feline Pancreatitis', id: 'feline' },
      { p: "Feline pancreatitis is less clearly linked to dietary fat than the canine form, and cats often have concurrent inflammatory bowel disease and liver inflammation (the triad). Severe fat restriction is generally less central in cats, and the priority is often maintaining intake to avoid hepatic lipidosis. Feline pancreatitis management is highly individualized and centers on supportive care and the concurrent conditions." },
      { h2: 'Low-Fat Diet Targets', id: 'targets' },
      { p: "Therapeutic low-fat diets for dogs are formulated well below the fat content of typical maintenance foods. Because guaranteed-analysis fat is reported as-fed and as a minimum, the meaningful comparison is fat grams per 1000 kcal on a measured basis, which a veterinarian or the manufacturer can provide. A diet that looks low-fat by percentage can still be fat-dense per calorie, so the per-energy figure is what matters. See [[The Guaranteed Analysis Explained|/nutrition/guaranteed-analysis-explained]]." },
      { h2: 'Treats and Scraps', id: 'treats' },
      { p: "For a pancreatitis-prone dog, the diet is only as low-fat as the least-disciplined treat. A single fatty indulgence can trigger an episode, so treats must be low-fat, table scraps eliminated, and the whole household informed. Low-fat treat options include small amounts of the dog's own kibble, plain cooked lean foods approved by the veterinarian, and commercial low-fat treats. See [[Treats and the 10 Percent Rule|/feeding/treats-and-the-ten-percent-rule]]." },
      { h2: 'Managing Recurrence', id: 'recurrence' },
      { p: "Chronic pancreatitis is managed by maintaining a consistent low-fat diet indefinitely, controlling body weight, and avoiding dietary indiscretion. Dogs with high blood triglycerides may need additional management. Recurrent or severe disease should be monitored by a veterinarian, who can confirm the diagnosis (pancreas-specific lipase testing and imaging) and set the long-term fat target appropriate to the individual." },
    ],
    related: [
      { label: 'Dietary Fat and Essential Fatty Acids', href: '/nutrition/dietary-fat-and-fatty-acids' },
      { label: 'The Guaranteed Analysis Explained', href: '/nutrition/guaranteed-analysis-explained' },
      { label: 'Treats and the 10 Percent Rule', href: '/feeding/treats-and-the-ten-percent-rule' },
    ],
    sources: [...STD, VET_SRC],
  },

  {
    dir: D, slug: 'joint-and-mobility-diets', date: '2026-06-01',
    title: 'Joint and Mobility Diets',
    metaTitle: 'Joint and Mobility Diets for Dogs and Cats | PetFood.com',
    metaDesc:
      'How mobility diets support osteoarthritis — the strong evidence for weight control and omega-3s, the weaker evidence for glucosamine, and what to expect.',
    category: 'Condition-Specific Diet', readTime: '10 min',
    hero:
      "Osteoarthritis is extremely common in older dogs and underdiagnosed in cats, and diet is a genuine tool for managing it — though the evidence is strongest for the least-marketed interventions. Weight control and marine omega-3s have solid support; glucosamine and chondroitin have weaker evidence. This page sorts the mobility-diet claims by the strength of their evidence.",
    toc: [
      { label: 'Osteoarthritis in Pets', id: 'oa' },
      { label: 'Weight — The Strongest Lever', id: 'weight' },
      { label: 'Omega-3 Fatty Acids', id: 'omega3' },
      { label: 'Glucosamine and Chondroitin', id: 'glucosamine' },
      { label: 'Other Ingredients', id: 'other' },
      { label: 'Realistic Expectations', id: 'expectations' },
    ],
    body: [
      { p: "Osteoarthritis (degenerative joint disease) causes cartilage breakdown, joint inflammation, pain, and reduced mobility. It affects a large share of older dogs and is increasingly recognized in cats, where it is easy to miss. Mobility diets and joint supplements are a major commercial category, but the evidence behind the various components varies widely, and the most effective intervention is also the most basic." },
      { h2: 'Osteoarthritis in Pets', id: 'oa' },
      { p: "Arthritis management is multimodal: weight control, pain medication where indicated, controlled exercise, physical rehabilitation, and nutritional support. Diet contributes through two well-supported mechanisms — reducing the mechanical load on joints via weight loss, and reducing joint inflammation via omega-3 fatty acids — plus several less-proven additives." },
      { h2: 'Weight — The Strongest Lever', id: 'weight' },
      { p: "Excess weight increases joint loading and is itself pro-inflammatory, and weight loss in overweight arthritic dogs produces measurable improvement in lameness — in some studies, weight loss alone improved mobility before any other treatment. This is the single most effective dietary intervention for arthritis, and it is free of cost beyond feeding less. See [[Weight-Management Diets|/diets/weight-management-diets]] and [[Body Condition Scoring|/feeding/body-condition-scoring]]." },
      { h2: 'Omega-3 Fatty Acids', id: 'omega3' },
      { p: "Marine-sourced EPA and DHA reduce the production of inflammatory mediators in the joint, and multiple controlled studies support diets enriched with high levels of fish-oil omega-3s for improving comfort and weight-bearing in arthritic dogs. Therapeutic mobility diets deliver EPA and DHA at levels well above ordinary maintenance foods. This is the best-supported active dietary ingredient for joints. See [[Fish Oil and Omega-3 Supplements|/supplements/fish-oil-omega-3]]." },
      { h2: 'Glucosamine and Chondroitin', id: 'glucosamine' },
      { p: "Glucosamine and chondroitin sulfate are the most-marketed joint supplements, but the clinical evidence in dogs and cats is mixed and generally weaker than for weight control and omega-3s. They appear safe and may help some animals, and they are commonly included in mobility diets and supplements, but they should not be expected to substitute for weight management or veterinary pain control. See [[Glucosamine and Joint Supplements|/supplements/glucosamine-and-joint-support]]." },
      { h2: 'Other Ingredients', id: 'other' },
      { p: "Mobility diets may add green-lipped mussel (a natural omega-3 and glycosaminoglycan source with some supporting evidence), antioxidants, and specific amino acids or botanicals. Evidence for these ranges from modest to preliminary. As a rule, the more a product leans on proprietary blends rather than the well-supported basics, the more skeptical the buyer should be." },
      { h2: 'Realistic Expectations', id: 'expectations' },
      { p: "Diet and supplements support joint comfort but do not regrow cartilage or cure arthritis. They are part of a multimodal plan that, for most animals with clinical disease, also includes weight management and veterinary-directed pain control. Set expectations accordingly, give interventions adequate time (weeks to months for omega-3 effects), and reassess with the veterinarian rather than stacking unproven supplements." },
    ],
    related: [
      { label: 'Fish Oil and Omega-3 Supplements', href: '/supplements/fish-oil-omega-3' },
      { label: 'Glucosamine and Joint Supplements', href: '/supplements/glucosamine-and-joint-support' },
      { label: 'Weight-Management Diets', href: '/diets/weight-management-diets' },
    ],
    sources: [...STD, VET_SRC],
  },

  {
    dir: D, slug: 'hydrolyzed-protein-diets', date: '2026-06-01',
    title: 'Hydrolyzed and Novel-Protein Diets',
    metaTitle: 'Hydrolyzed and Novel-Protein Diets for Pets | PetFood.com',
    metaDesc:
      'How hydrolyzed and novel-protein therapeutic diets work for food allergy and GI disease, molecular weight and efficacy, and why they are veterinary products.',
    category: 'Condition-Specific Diet', readTime: '10 min',
    hero:
      "Hydrolyzed and novel-protein diets are the therapeutic backbone of food-allergy and food-responsive gastrointestinal management. They work by either shrinking the protein below the immune system's recognition threshold or presenting a protein the animal has never encountered. This page explains the mechanisms, the molecular-weight question, and why they are veterinary-channel products.",
    toc: [
      { label: 'The Two Strategies', id: 'strategies' },
      { label: 'How Hydrolysis Works', id: 'hydrolysis' },
      { label: 'Molecular Weight and Efficacy', id: 'mw' },
      { label: 'Novel Proteins', id: 'novel' },
      { label: 'Uses Beyond Allergy', id: 'beyond' },
      { label: 'Why Veterinary-Channel', id: 'vetchannel' },
    ],
    body: [
      { p: "When dietary protein drives disease — through allergic skin disease or food-responsive enteropathy — two therapeutic strategies remove the offending antigen. The first hydrolyzes the protein into fragments too small to provoke an immune response; the second uses a protein the individual has never eaten, so no sensitization exists. Both are central to the elimination-diet approach and to managing dietary-antigen-driven gut disease. See [[Food Allergy and Elimination Diets|/diets/food-allergy-and-elimination-diets]]." },
      { h2: 'The Two Strategies', id: 'strategies' },
      { p: "Hydrolyzed diets are made from a conventional protein (such as soy or chicken liver) broken down enzymatically into small peptides. Novel-protein diets use an intact but unusual protein (venison, rabbit, kangaroo, duck, or insect). Hydrolyzed diets have the advantage that they do not depend on finding a protein the animal has truly never seen — increasingly difficult as exotic proteins enter mainstream foods and treats." },
      { h2: 'How Hydrolysis Works', id: 'hydrolysis' },
      { p: "The immune system recognizes proteins by their three-dimensional shape and by linear segments of a certain size. Hydrolysis cleaves the protein into peptides below the size the immune system typically recognizes, reducing the likelihood of an allergic response. The process does not change the amino-acid content, so the diet remains nutritionally complete, but it can reduce palatability for some animals. See [[Animal Protein Sources|/ingredients/animal-protein-sources]]." },
      { h2: 'Molecular Weight and Efficacy', id: 'mw' },
      { p: "The degree of hydrolysis matters. Standard hydrolyzed diets reduce protein to a moderate peptide size adequate for many patients; extensively hydrolyzed diets, with very low molecular weight (often below 1 kilodalton, with substantial free amino acids), are used when a standard hydrolyzed diet has failed to control signs. The clinician escalates to a more extensively hydrolyzed product when the first does not resolve the disease." },
      { h2: 'Novel Proteins', id: 'novel' },
      { p: "A novel protein works only if it is genuinely novel for that individual, which requires a careful diet history. Cross-contamination is a real risk in non-therapeutic novel-protein products, where the same equipment runs common proteins; veterinary therapeutic novel-protein diets are manufactured to minimize this. Insect protein is an emerging novel option with the advantage that almost no dog or cat has prior exposure. See [[Limited-Ingredient Diets Myth|/myths/limited-ingredient-diet-myth]]." },
      { h2: 'Uses Beyond Allergy', id: 'beyond' },
      { p: "Beyond cutaneous food allergy, these diets manage food-responsive enteropathy — a subset of chronic gastrointestinal disease that resolves with a controlled antigen diet rather than medication. Identifying food-responsive cases through a diet trial spares the animal long-term drug therapy, which is one reason a hydrolyzed or novel-protein trial is part of the GI work-up. See [[Fiber and Digestive Health Diets|/diets/fiber-and-digestive-health]]." },
      { h2: 'Why Veterinary-Channel', id: 'vetchannel' },
      { p: "Hydrolyzed and true elimination novel-protein diets are sold through veterinarians because their correct use depends on diagnosis, on strict adherence during the trial, and on manufacturing control to avoid antigen contamination. Using them without veterinary guidance — feeding treats alongside, or choosing an OTC product with hidden proteins — defeats their diagnostic and therapeutic purpose." },
    ],
    related: [
      { label: 'Food Allergy and Elimination Diets', href: '/diets/food-allergy-and-elimination-diets' },
      { label: 'Animal Protein Sources', href: '/ingredients/animal-protein-sources' },
      { label: 'Limited-Ingredient Diets Myth', href: '/myths/limited-ingredient-diet-myth' },
    ],
    sources: [...STD, VET_SRC],
  },

  {
    dir: D, slug: 'puppy-and-kitten-growth-diets', date: '2026-06-01',
    title: 'Puppy and Kitten Growth Diets',
    metaTitle: 'Puppy and Kitten Growth Diet Requirements | PetFood.com',
    metaDesc:
      'Why growth diets differ from adult food — higher protein, fat, calcium, and DHA, the large-breed calcium ceiling, and the risks of feeding adult food to young animals.',
    category: 'Condition-Specific Diet', readTime: '11 min',
    hero:
      "Growth is the most nutritionally demanding life stage, and the consequences of getting it wrong — skeletal disease in large-breed puppies, developmental deficits in kittens — can be permanent. Growth diets carry higher minimums for several nutrients and, for large-breed puppies, a critical calcium ceiling. This page covers the growth requirements and the common feeding errors.",
    toc: [
      { label: 'Why Growth Is Demanding', id: 'demanding' },
      { label: 'Higher Nutrient Minimums', id: 'minimums' },
      { label: 'DHA for Development', id: 'dha' },
      { label: 'The Large-Breed Calcium Ceiling', id: 'calcium' },
      { label: 'Kitten Specifics', id: 'kitten' },
      { label: 'Common Feeding Errors', id: 'errors' },
    ],
    body: [
      { p: "During growth, an animal builds bone, muscle, organs, and nervous tissue at a rapid rate, requiring more energy and more of nearly every nutrient per unit of body weight than at any other life stage except lactation. AAFCO sets a distinct growth-and-reproduction nutrient profile with higher minimums, and feeding a growing animal a diet formulated only for adult maintenance can produce deficiencies with lasting consequences. See [[Pet Food by Life Stage|/life-stage]]." },
      { h2: 'Why Growth Is Demanding', id: 'demanding' },
      { p: "A growing puppy or kitten may need roughly twice the energy per kilogram of an adult, and proportionally more protein to lay down lean tissue, more calcium and phosphorus to mineralize the skeleton, and more of several micronutrients. This is why growth diets and all-life-stages diets carry higher minimums than adult-maintenance foods, and why a food labeled for adult maintenance only is inappropriate for a youngster." },
      { h2: 'Higher Nutrient Minimums', id: 'minimums' },
      { p: "The AAFCO growth profile sets higher minimums than adult maintenance for crude protein (22.5 percent versus 18 percent dry-matter for dogs; 30 percent for cats), crude fat, calcium, phosphorus, and several other nutrients. A complete growth diet is formulated to these elevated targets. See [[Dietary Protein Requirements|/nutrition/dietary-protein-requirements]] and [[Minerals in Pet Food|/nutrition/minerals-in-pet-food]]." },
      { h2: 'DHA for Development', id: 'dha' },
      { p: "Docosahexaenoic acid (DHA), a long-chain omega-3, supports neural and retinal development in puppies and kittens, and growth diets are commonly DHA-supplemented for this reason. Adequate DHA during early development is associated with better trainability and visual function. This is one of the evidence-supported reasons to feed a genuine growth diet rather than an adult food. See [[Dietary Fat and Essential Fatty Acids|/nutrition/dietary-fat-and-fatty-acids]]." },
      { h2: 'The Large-Breed Calcium Ceiling', id: 'calcium' },
      { p: "Large- and giant-breed puppies are uniquely vulnerable to excess calcium during growth, which can cause developmental orthopedic disease including osteochondrosis. AAFCO created a separate large-size growth profile (for dogs reaching 70 pounds or more as adults) with a tighter calcium maximum. Owners of large-breed puppies must confirm the food is validated for growth including large-size growth, because an all-life-stages food not so validated can legally exceed the safe ceiling. See [[Large-Breed Puppy Nutrition|/feeding/large-breed-puppy-nutrition]]." },
      { h2: 'Kitten Specifics', id: 'kitten' },
      { p: "Kittens, as obligate carnivores in their most demanding life stage, require high protein, taurine, arachidonic acid, and pre-formed vitamin A, plus high energy density. They generally do well on a kitten or all-life-stages diet fed to appetite during early growth. Unlike large-breed puppies, kittens do not have the same calcium-ceiling concern, but they share the need for a properly formulated growth diet. See [[Dog vs Cat Nutrition|/species/dog-vs-cat-nutrition-overview]]." },
      { h2: 'Common Feeding Errors', id: 'errors' },
      { ol: [
        "Feeding an adult-maintenance diet to a growing animal — it does not meet growth minimums.",
        "Feeding a large-breed puppy an all-life-stages food not validated for large-size growth, risking excess calcium.",
        "Over-supplementing calcium (with bone meal or calcium tablets) on top of a complete growth diet, which is a classic cause of orthopedic disease.",
        "Overfeeding to maximize growth rate — rapid growth raises orthopedic-disease risk; lean, steady growth is the goal.",
        "Switching to adult food too early or too late — timing depends on breed size and should follow veterinary guidance.",
      ]},
    ],
    related: [
      { label: 'Large-Breed Puppy Nutrition', href: '/feeding/large-breed-puppy-nutrition' },
      { label: 'Minerals in Pet Food', href: '/nutrition/minerals-in-pet-food' },
      { label: 'Pet Food by Life Stage', href: '/life-stage' },
    ],
    sources: [...STD],
  },

  {
    dir: D, slug: 'cardiac-and-low-sodium-diets', date: '2026-06-01',
    title: 'Cardiac and Low-Sodium Diets',
    metaTitle: 'Cardiac (Heart) and Low-Sodium Diets for Pets | PetFood.com',
    metaDesc:
      'How diet supports heart disease — sodium restriction by disease stage, protein and muscle preservation, taurine, omega-3s, and maintaining appetite.',
    category: 'Condition-Specific Diet', readTime: '10 min',
    hero:
      "Heart disease is common in older dogs and cats, and diet is a meaningful adjunct to medical management — chiefly through sodium control, but also protein preservation, taurine, and omega-3s. The right approach depends on the stage of disease, and the perennial challenge is keeping a cardiac patient eating. This page covers the principles of cardiac nutrition.",
    toc: [
      { label: 'Diet in Heart Disease', id: 'role' },
      { label: 'Sodium by Stage', id: 'sodium' },
      { label: 'Protein and Muscle', id: 'protein' },
      { label: 'Taurine and Carnitine', id: 'taurine' },
      { label: 'Omega-3 Fatty Acids', id: 'omega3' },
      { label: 'Keeping Them Eating', id: 'appetite' },
    ],
    body: [
      { p: "Cardiac disease — degenerative valve disease and dilated cardiomyopathy in dogs, and various conditions in cats — is managed primarily with medication, but diet supports management and helps counter the muscle loss (cardiac cachexia) that accompanies advanced heart failure. The classic dietary lever is sodium, but cardiac nutrition is more than salt restriction, and it must be staged to the disease and individualized. See [[Taurine and Amino Acids|/nutrition/taurine-and-amino-acids]]." },
      { h2: 'Diet in Heart Disease', id: 'role' },
      { p: "Diet in heart disease aims to reduce fluid-retention pressures (via sodium control), preserve lean muscle against cardiac cachexia, ensure adequate taurine and other heart-relevant nutrients, reduce inflammation with omega-3s, and above all maintain caloric intake. It complements, never replaces, cardiac medication and veterinary management. The plan changes as the disease progresses." },
      { h2: 'Sodium by Stage', id: 'sodium' },
      { p: "Sodium restriction reduces fluid retention in heart failure, but the degree of restriction is tied to disease stage. In early, asymptomatic heart disease, severe restriction is unnecessary and avoiding very high-sodium foods and treats suffices; in advanced congestive heart failure, more meaningful sodium restriction is used alongside medication. Over-restricting too early can backfire by reducing palatability and activating fluid-retaining hormones, so sodium targets are set by the veterinarian per stage. See [[Minerals in Pet Food|/nutrition/minerals-in-pet-food]]." },
      { h2: 'Protein and Muscle', id: 'protein' },
      { p: "Cardiac cachexia — the loss of lean muscle in heart failure — worsens outcomes, so adequate high-quality protein is important and protein should not be over-restricted in cardiac patients (unless concurrent kidney disease dictates otherwise). Preserving muscle supports strength and survival. This is a shift from older thinking and aligns with maintaining protein in most cardiac patients. See [[Dietary Protein Requirements|/nutrition/dietary-protein-requirements]]." },
      { h2: 'Taurine and Carnitine', id: 'taurine' },
      { p: "Taurine deficiency causes dilated cardiomyopathy in cats (an essential dietary nutrient for them) and in certain dog breeds, and taurine and L-carnitine supplementation are part of management when deficiency or a responsive cardiomyopathy is identified. The diet-associated DCM investigation in dogs has kept taurine status central to the cardiac work-up. Taurine and carnitine are used under veterinary direction based on testing and disease type. See [[Grain-Free and DCM Risk|/ingredients/grain-free-dcm-risk]]." },
      { h2: 'Omega-3 Fatty Acids', id: 'omega3' },
      { p: "Marine omega-3 fatty acids (EPA and DHA) have evidence in cardiac patients for reducing inflammation, helping counter cachexia, and supporting against arrhythmias, and cardiac therapeutic diets and fish-oil supplementation are commonly used. As elsewhere, the marine pre-formed forms matter, and dosing is set with the veterinarian. See [[Fish Oil and Omega-3 Supplements|/supplements/fish-oil-omega-3]]." },
      { h2: 'Keeping Them Eating', id: 'appetite' },
      { p: "Inappetence is a major challenge in heart failure, and a cardiac patient that stops eating loses muscle and misses medication often hidden in food. Palatability frequently trumps the theoretically ideal sodium target — a slightly higher-sodium food the animal will eat can be better than an ideal one it refuses. Maintaining intake, with warming, variety, and veterinary guidance, is a priority. See [[Senior Pet Diets|/diets/senior-pet-diets]]." },
    ],
    related: [
      { label: 'Taurine and Amino Acids', href: '/nutrition/taurine-and-amino-acids' },
      { label: 'Fish Oil and Omega-3 Supplements', href: '/supplements/fish-oil-omega-3' },
      { label: 'Grain-Free and DCM Risk', href: '/ingredients/grain-free-dcm-risk' },
    ],
    sources: [...STD, SRC.fdaDcm],
  },

  {
    dir: D, slug: 'hyperthyroid-cat-diets', date: '2026-06-01',
    title: 'Hyperthyroid Cat Diets',
    metaTitle: 'Hyperthyroidism Diet for Cats — Iodine Restriction | PetFood.com',
    metaDesc:
      'How iodine-restricted diets manage feline hyperthyroidism, how the diet works, its strict requirements, and where it fits among the treatment options.',
    category: 'Condition-Specific Diet', readTime: '9 min',
    hero:
      "Hyperthyroidism is one of the most common endocrine diseases of older cats, and dietary iodine restriction is one of several treatment options — a genuinely effective one, but with strict requirements that make it succeed or fail. This page explains how the iodine-restricted diet works, its demands, and where it fits alongside medication, radioiodine, and surgery.",
    toc: [
      { label: 'Feline Hyperthyroidism', id: 'disease' },
      { label: 'How Iodine Restriction Works', id: 'iodine' },
      { label: 'The Strict Requirement', id: 'strict' },
      { label: 'Multi-Cat Households', id: 'multicat' },
      { label: 'Comparing Treatment Options', id: 'options' },
      { label: 'Monitoring', id: 'monitoring' },
    ],
    body: [
      { p: "Hyperthyroidism — overproduction of thyroid hormone, usually from a benign thyroid tumor — is common in cats over about 10 years and causes weight loss despite a ravenous appetite, hyperactivity, and secondary effects on the heart and kidneys. Among the treatment options, an iodine-restricted therapeutic diet can control the disease by limiting the iodine the thyroid needs to make hormone, but only if fed strictly and exclusively. See [[Minerals in Pet Food|/nutrition/minerals-in-pet-food]]." },
      { h2: 'Feline Hyperthyroidism', id: 'disease' },
      { p: "The disease produces excess thyroid hormone, accelerating metabolism. Classic signs are weight loss with a strong appetite, increased thirst and urination, restlessness, and sometimes vomiting; untreated, it strains the heart and can mask or worsen kidney disease. Diagnosis is by blood thyroid-hormone testing. Treatment options include medication, radioiodine, surgery, and the iodine-restricted diet. See [[Senior Pet Diets|/diets/senior-pet-diets]]." },
      { h2: 'How Iodine Restriction Works', id: 'iodine' },
      { p: "Thyroid hormone is built from iodine, so a diet with iodine restricted to a very low level limits the raw material available, reducing hormone production and bringing thyroid levels toward normal in many cats. This is a targeted nutritional therapy that exploits a specific biochemical dependency. It works only because iodine is essential and rate-limiting for hormone synthesis." },
      { h2: 'The Strict Requirement', id: 'strict' },
      { p: "The iodine-restricted diet works only if it is the cat's sole source of food. Any other food, treats, table scraps, or even iodine in drinking water or hunted prey can supply enough iodine to undermine the diet. This all-or-nothing requirement is the main limitation: a cat that goes outdoors and hunts, or a household that cannot prevent the cat eating other food, cannot reliably use the diet. See [[Feeding Multiple Pets|/feeding/feeding-multiple-pets]]." },
      { h2: 'Multi-Cat Households', id: 'multicat' },
      { p: "In multi-cat homes the diet is challenging because the hyperthyroid cat must eat only the restricted diet while the others should not (it is not appropriate for cats without the disease). Strict mealtime separation, no free-choice food, and sometimes microchip feeders are required. The difficulty of guaranteeing exclusivity often steers multi-cat households toward other treatment options. See [[Feeding Multiple Pets|/feeding/feeding-multiple-pets]]." },
      { h2: 'Comparing Treatment Options', id: 'options' },
      { p: "The diet is one of four main approaches. Anti-thyroid medication is effective and adjustable but lifelong and not curative. Radioiodine therapy is curative in most cats and considered the gold standard but requires a specialized facility. Surgery removes the affected tissue. The iodine-restricted diet is non-invasive and avoids medication but demands strict exclusive feeding and does not cure the underlying tumor. The choice depends on the cat, the household, concurrent disease, and cost, and is made with the veterinarian." },
      { h2: 'Monitoring', id: 'monitoring' },
      { p: "Whichever treatment is used, hyperthyroid cats need monitoring of thyroid levels and kidney values, because controlling hyperthyroidism can unmask underlying kidney disease (the high thyroid state had been propping up apparent kidney function). Diet-managed cats need confirmation that thyroid levels have normalized and ongoing checks. This is a managed chronic disease, directed by the veterinarian. See [[Kidney Disease Diets|/diets/kidney-disease-diets]]." },
    ],
    related: [
      { label: 'Minerals in Pet Food', href: '/nutrition/minerals-in-pet-food' },
      { label: 'Feeding Multiple Pets', href: '/feeding/feeding-multiple-pets' },
      { label: 'Kidney Disease Diets', href: '/diets/kidney-disease-diets' },
    ],
    sources: [...STD, VET_SRC],
  },
]

export const DIETS = RAW.map((p) => ({ ...p, hubName: 'Diets' }))
