import { SRC, STD } from './_shared.mjs'

const D = 'feeding'

const RAW = [
  {
    dir: D, slug: 'how-much-to-feed-a-dog', date: '2026-06-01',
    title: 'How Much to Feed a Dog',
    metaTitle: 'How Much to Feed a Dog — Calorie Math | PetFood.com',
    metaDesc:
      'How to calculate a dog feeding amount from resting energy requirement and activity factors, why bag guidelines overfeed, and how to adjust to body condition.',
    category: 'Feeding Guide', readTime: '10 min',
    hero:
      "The feeding chart on the bag is a starting point that overfeeds most dogs, because it is built around ranges and around the manufacturer's interest in selling food. The accurate approach is a short calculation from the dog's energy requirement and the food's calorie density. This page shows the math, the activity factors, and how to adjust by body condition.",
    toc: [
      { label: 'Why Bag Guidelines Overfeed', id: 'bagguides' },
      { label: 'Resting Energy Requirement', id: 'rer' },
      { label: 'Activity Factors', id: 'activity' },
      { label: 'Converting to Cups', id: 'cups' },
      { label: 'Adjusting by Body Condition', id: 'adjust' },
      { label: 'Worked Example', id: 'example' },
    ],
    body: [
      { p: "How much to feed depends on the dog's energy requirement and the calorie density of the food — not on a one-size range printed on the bag. Energy needs vary widely with size, age, activity, neuter status, and metabolism, so two dogs of the same weight can have feeding amounts that differ by 50 percent. The reliable method is to estimate daily calories, then divide by the food's calories per cup. See [[Pet Food Calories and Energy Density|/nutrition/calories-and-energy-density]]." },
      { h2: 'Why Bag Guidelines Overfeed', id: 'bagguides' },
      { p: "Manufacturer feeding charts give a broad weight-based range and tend to target the high end, partly because they assume an active, intact, average-metabolism dog. Most pet dogs are neutered, moderately active, and prone to weight gain. Following the chart without adjusting is one of the most common causes of creeping weight gain. Treat the chart as an upper bound and refine from there." },
      { h2: 'Resting Energy Requirement', id: 'rer' },
      { p: "The foundation is the resting energy requirement (RER) — the calories needed at rest. A widely used formula is RER = 70 x (body weight in kilograms)^0.75. For a quick linear estimate in the 2 to 45 kilogram range, RER is approximately 30 x (weight in kilograms) + 70. RER is then multiplied by an activity factor to get the daily energy requirement (also called maintenance energy requirement)." },
      { h2: 'Activity Factors', id: 'activity' },
      { p: "Typical multipliers applied to RER: neutered adult dog roughly 1.6; intact adult roughly 1.8; weight loss roughly 1.0; weight gain or underweight roughly 1.2 to 1.4; light work roughly 2.0; heavy work 2.5 to 5.0; puppies up to four months roughly 3.0, four months to adult roughly 2.0. These are starting estimates from published guidelines; individual metabolism varies, so the number is adjusted based on how the dog's weight and body condition respond over time." },
      { h2: 'Converting to Cups', id: 'cups' },
      { p: "Once you have the daily energy requirement in kilocalories, divide it by the food's kilocalories per cup (from the calorie statement on the bag) to get cups per day, then split across meals. Because calorie density varies by food, the cups figure must be recalculated whenever the food changes. Weighing the portion on a kitchen scale is far more accurate than a measuring cup, which over-portions by roughly 20 percent on average. See the [[Food Cost Calculator|/tools/food-cost-calculator]]." },
      { h2: 'Adjusting by Body Condition', id: 'adjust' },
      { p: "The calculation gives a starting amount; the dog's body condition gives the correction. Assess body condition every few weeks. If the dog is gaining toward overweight, reduce the amount; if losing or too lean, increase it. Body condition score, not the scale alone, is the target. See [[Body Condition Scoring|/feeding/body-condition-scoring]]." },
      { h2: 'Worked Example', id: 'example' },
      { p: "A neutered 20-kilogram adult dog: RER = 30 x 20 + 70 = 670 kcal. Daily energy requirement = 670 x 1.6 = roughly 1072 kcal. If the food is 350 kcal per cup, that is about 3.06 cups per day, split into two meals of about 1.5 cups. Then watch body condition over a month and adjust. If the dog gains weight, the true maintenance factor is lower than 1.6, and the amount comes down." },
    ],
    related: [
      { label: 'Pet Food Calories and Energy Density', href: '/nutrition/calories-and-energy-density' },
      { label: 'Body Condition Scoring', href: '/feeding/body-condition-scoring' },
      { label: 'How Much to Feed a Cat', href: '/feeding/how-much-to-feed-a-cat' },
    ],
    sources: [...STD],
  },

  {
    dir: D, slug: 'how-much-to-feed-a-cat', date: '2026-06-01',
    title: 'How Much to Feed a Cat',
    metaTitle: 'How Much to Feed a Cat — Calorie Math | PetFood.com',
    metaDesc:
      'How to calculate cat feeding amounts from energy requirements, the indoor-cat obesity problem, meal feeding vs grazing, and adjusting to body condition.',
    category: 'Feeding Guide', readTime: '10 min',
    hero:
      "Cats are easy to overfeed: they are small, the calorie differences between foods are large in relative terms, and free-choice grazing on energy-dense kibble drives the high rate of feline obesity. This page shows the feeding-amount calculation for cats, the indoor-cat adjustment, and why meal feeding beats the perpetually full bowl.",
    toc: [
      { label: 'Cat Energy Requirements', id: 'energy' },
      { label: 'The Indoor-Cat Problem', id: 'indoor' },
      { label: 'Meal Feeding vs Grazing', id: 'mealfeeding' },
      { label: 'Wet, Dry, and Mixed', id: 'format' },
      { label: 'Adjusting by Body Condition', id: 'adjust' },
      { label: 'Worked Example', id: 'example' },
    ],
    body: [
      { p: "A cat's feeding amount, like a dog's, is best derived from its energy requirement and the food's calorie density rather than from the bag's range. Cats are obligate carnivores with relatively high protein needs and, when kept indoors and neutered, comparatively low energy needs — a combination that makes portion control essential. See [[Pet Food Calories and Energy Density|/nutrition/calories-and-energy-density]] and [[Dog vs Cat Nutrition|/species/dog-vs-cat-nutrition-overview]]." },
      { h2: 'Cat Energy Requirements', id: 'energy' },
      { p: "Resting energy requirement uses the same formula as for dogs: RER = 70 x (kg)^0.75, or approximately 30 x kg + 70 for typical cats. The daily energy requirement is RER times an activity factor. For cats the factors are lower than for dogs: neutered adult roughly 1.2; intact adult roughly 1.4; weight loss roughly 0.8; inactive or obese-prone roughly 1.0; kitten roughly 2.5. A typical lean 4-kilogram neutered indoor cat needs only on the order of 200 to 250 kcal per day." },
      { h2: 'The Indoor-Cat Problem', id: 'indoor' },
      { p: "Indoor neutered cats have low energy expenditure and ready access to food, and high-carbohydrate energy-dense kibble left out all day makes overconsumption easy. Feline obesity is widespread and drives diabetes, arthritis, and urinary disease. The low activity factor for indoor cats means their daily calorie allowance is small, and small overages add up quickly on a small animal. See [[Weight-Management Diets|/diets/weight-management-diets]]." },
      { h2: 'Meal Feeding vs Grazing', id: 'mealfeeding' },
      { p: "Free-choice grazing makes intake invisible and overfeeding likely; measured meals (or a measured daily allowance in a puzzle feeder) make calories countable and support a healthy weight. Multiple small measured meals suit feline physiology — cats naturally eat many small meals — while still controlling total intake. Puzzle and foraging feeders add activity and slow consumption." },
      { h2: 'Wet, Dry, and Mixed', id: 'format' },
      { p: "Many cats do well on canned food or a wet-plus-dry combination, which raises water intake and lowers calorie density per gram, supporting both hydration and weight control. When feeding a mix, the calories from each component must be summed against the daily allowance, not eyeballed by volume. See [[Wet vs Dry Food|/compare/wet-vs-dry-food]] and [[Water and Hydration|/nutrition/water-and-hydration]]." },
      { h2: 'Adjusting by Body Condition', id: 'adjust' },
      { p: "As with dogs, the calculation is a starting point and body condition is the correction. Reassess every few weeks. Because cats are small, weight changes of even half a kilogram are significant. Never crash-diet an overweight cat — rapid loss risks hepatic lipidosis — so reductions are gradual and monitored. See [[Body Condition Scoring|/feeding/body-condition-scoring]]." },
      { h2: 'Worked Example', id: 'example' },
      { p: "A neutered 4.5-kilogram indoor cat: RER = 30 x 4.5 + 70 = 205 kcal. Daily energy requirement = 205 x 1.2 = roughly 246 kcal. If a canned food provides 90 kcal per 85-gram can, that is about 2.7 cans per day; if dry food provides 350 kcal per cup, the full allowance would be about 0.7 cup. Most owners are surprised how little that is — which is precisely why measuring matters for cats." },
    ],
    related: [
      { label: 'Pet Food Calories and Energy Density', href: '/nutrition/calories-and-energy-density' },
      { label: 'Body Condition Scoring', href: '/feeding/body-condition-scoring' },
      { label: 'Wet vs Dry Food', href: '/compare/wet-vs-dry-food' },
    ],
    sources: [...STD],
  },

  {
    dir: D, slug: 'body-condition-scoring', date: '2026-06-01',
    title: 'Body Condition Scoring',
    metaTitle: 'Body Condition Score for Dogs and Cats Explained | PetFood.com',
    metaDesc:
      'How to use the 9-point body condition score, the rib-waist-tuck assessment, muscle condition scoring, and why BCS beats the scale for feeding decisions.',
    category: 'Feeding Guide', readTime: '9 min',
    hero:
      "Body condition score is the single most useful tool an owner has for feeding decisions, and it requires no equipment beyond your hands and eyes. It tells you whether the current feeding amount is right far better than the scale does, because it measures fat cover directly. This page explains the 9-point scale, how to assess it, and how to act on it.",
    toc: [
      { label: 'Why BCS Beats the Scale', id: 'whybcs' },
      { label: 'The 9-Point Scale', id: 'scale' },
      { label: 'How to Assess', id: 'assess' },
      { label: 'Muscle Condition Score', id: 'muscle' },
      { label: 'Acting on the Score', id: 'acting' },
      { label: 'Tracking Over Time', id: 'tracking' },
    ],
    body: [
      { p: "Body condition score (BCS) is a standardized hands-on assessment of an animal's fat cover, used by veterinarians worldwide. Unlike body weight, which means nothing without context (is 30 kilograms heavy or light? it depends on the dog), BCS directly answers whether the animal carries too much, too little, or the right amount of fat. It is the practical readout of whether feeding is on target." },
      { h2: 'Why BCS Beats the Scale', id: 'whybcs' },
      { p: "A number on the scale has no meaning without a frame of reference, and breed-average weight tables hide enormous individual variation. BCS normalizes for frame: a correctly-conditioned animal scores the same whether it is large or small. This is why feeding decisions should be anchored to BCS, with body weight used to track change once an ideal weight is established. See [[How Much to Feed a Dog|/feeding/how-much-to-feed-a-dog]]." },
      { h2: 'The 9-Point Scale', id: 'scale' },
      { p: "The widely used 9-point scale runs from 1 (emaciated) to 9 (grossly obese), with 4 to 5 as ideal. Each point above 5 corresponds to roughly 10 to 15 percent above ideal body weight. A 5/9 animal has easily felt ribs without excess fat, a visible waist from above, and an abdominal tuck from the side. A 4/9 is slightly leaner, also acceptable for many animals, especially athletic dogs." },
      { h2: 'How to Assess', id: 'assess' },
      { p: "Assess three things by hand and eye. Ribs: run your hands along the chest — at ideal condition the ribs are easily felt under a thin fat layer, like the back of your hand; if you must press to find them, the animal is overweight. Waist: viewed from above, there should be a visible inward curve behind the ribs. Tuck: viewed from the side, the belly should rise from the chest toward the hind legs rather than hang level or sag. Long or thick coats hide all three, so hands matter more than eyes." },
      { h2: 'Muscle Condition Score', id: 'muscle' },
      { p: "Body condition measures fat; muscle condition score (MCS) separately assesses muscle mass over the skull, shoulders, spine, and pelvis. The two are independent — an animal can be overweight (high BCS) yet muscle-wasted (low MCS), common in older animals and in disease. Muscle loss is an important sign and a reason adequate protein matters in older animals. See [[Senior Pet Diets|/diets/senior-pet-diets]]." },
      { h2: 'Acting on the Score', id: 'acting' },
      { p: "If BCS is above 5, reduce calories (ideally with a weight-management approach rather than simply less of a maintenance food) and increase activity, targeting gradual loss. If BCS is below 4, increase calories and rule out underlying disease with the veterinarian. If BCS is 4 to 5, the current feeding is on target — maintain and keep monitoring. See [[Weight-Management Diets|/diets/weight-management-diets]]." },
      { h2: 'Tracking Over Time', id: 'tracking' },
      { p: "Reassess BCS every two to four weeks during a weight program and at least every few months otherwise. Because owners see their animal daily, gradual change is easy to miss; periodic scoring and a recorded weight catch drift early. Photos from above and from the side, taken on a schedule, are a useful supplement. Establish the ideal weight once, then track the scale against it." },
    ],
    related: [
      { label: 'How Much to Feed a Dog', href: '/feeding/how-much-to-feed-a-dog' },
      { label: 'Weight-Management Diets', href: '/diets/weight-management-diets' },
      { label: 'Senior Pet Diets', href: '/diets/senior-pet-diets' },
    ],
    sources: [...STD],
  },

  {
    dir: D, slug: 'how-to-transition-pet-food', date: '2026-06-01',
    title: 'How to Transition Pet Food',
    metaTitle: 'How to Transition Your Pet to a New Food | PetFood.com',
    metaDesc:
      'The 7-to-10-day food transition schedule, why gradual change prevents GI upset, handling picky eaters, and when a faster or slower transition is appropriate.',
    category: 'Feeding Guide', readTime: '8 min',
    hero:
      "Switching foods abruptly is one of the most common causes of avoidable vomiting and diarrhea, because the gut and its microbiome need time to adapt to a new ingredient and nutrient profile. A gradual transition over a week or more prevents most upset. This page gives the schedule, the reasoning, and the exceptions.",
    toc: [
      { label: 'Why Transition Gradually', id: 'why' },
      { label: 'The Standard Schedule', id: 'schedule' },
      { label: 'Slower Transitions', id: 'slower' },
      { label: 'Picky Eaters', id: 'picky' },
      { label: 'When to Slow Down', id: 'slowdown' },
      { label: 'After the Switch', id: 'after' },
    ],
    body: [
      { p: "A new food differs from the old one in ingredients, fiber, fat, and nutrient profile, and the digestive system — including the gut microbiome that helps process food — adapts to those differences over days. An abrupt switch can outpace that adaptation, producing soft stool, gas, vomiting, or refusal. A gradual transition gives the gut time to adjust and is the standard recommendation for any food change in a healthy animal." },
      { h2: 'Why Transition Gradually', id: 'why' },
      { p: "The gut microbiome shifts its composition in response to diet, and abrupt dietary change disrupts it transiently, which is a common cause of diet-change diarrhea. Mixing increasing proportions of the new food with the old lets the microbiome and digestive enzymes adapt incrementally. The same logic applies whether switching brands, formulas, or formats. See [[Fiber and Digestive Health Diets|/diets/fiber-and-digestive-health]]." },
      { h2: 'The Standard Schedule', id: 'schedule' },
      { ol: [
        "Days 1 to 3: about 75 percent old food, 25 percent new food.",
        "Days 4 to 6: about 50 percent old, 50 percent new.",
        "Days 7 to 9: about 25 percent old, 75 percent new.",
        "Day 10 onward: 100 percent new food.",
        "Watch stool quality and appetite at each step; if signs of upset appear, hold at the current ratio until they resolve.",
      ]},
      { h2: 'Slower Transitions', id: 'slower' },
      { p: "Animals with sensitive stomachs, a history of GI disease, or those switching to a markedly different diet (for example, kibble to raw or fresh, or to a high-fat performance food) benefit from a slower transition over two to three weeks. Cats, who can be more diet-conservative than dogs, also often do better with a slower change. The schedule is a default, not a rule — extend it as needed." },
      { h2: 'Picky Eaters', id: 'picky' },
      { p: "For animals reluctant to accept a new food, a slower transition with smaller initial increments helps, as does warming wet food slightly to release aroma, ensuring the old and new are mixed rather than offered separately, and avoiding the trap of constantly switching foods to chase preference (which trains pickiness). Cats in particular can develop fixed texture and flavor preferences, so persistence and gradual change matter." },
      { h2: 'When to Slow Down or Stop', id: 'slowdown' },
      { p: "If the animal develops more than mild, transient soft stool, or vomits, or refuses to eat, pause the transition and hold at the last tolerated ratio. Persistent vomiting, diarrhea lasting more than a day or two, blood in the stool, or lethargy warrants veterinary attention rather than pushing the transition. A food change should never override signs of genuine illness." },
      { h2: 'After the Switch', id: 'after' },
      { p: "Once fully transitioned, recalculate the feeding amount for the new food's calorie density — a step owners frequently skip, leading to over- or underfeeding when the new food differs in calories per cup. Monitor body condition over the following weeks and adjust. See [[How Much to Feed a Dog|/feeding/how-much-to-feed-a-dog]] and [[Pet Food Calories and Energy Density|/nutrition/calories-and-energy-density]]." },
    ],
    related: [
      { label: 'How Much to Feed a Dog', href: '/feeding/how-much-to-feed-a-dog' },
      { label: 'Fiber and Digestive Health Diets', href: '/diets/fiber-and-digestive-health' },
      { label: 'Feeding Frequency and Schedules', href: '/feeding/feeding-frequency-and-schedules' },
    ],
    sources: [...STD],
  },

  {
    dir: D, slug: 'feeding-frequency-and-schedules', date: '2026-06-01',
    title: 'Feeding Frequency and Schedules',
    metaTitle: 'Feeding Frequency and Schedules for Dogs and Cats | PetFood.com',
    metaDesc:
      'How often to feed dogs and cats by life stage, meal feeding vs free choice, the bloat consideration in dogs, and timing around medication and activity.',
    category: 'Feeding Guide', readTime: '8 min',
    hero:
      "How often to feed is a real nutritional decision, not just routine. Frequency interacts with life stage, body weight management, the canine bloat risk, and medical conditions like diabetes. This page covers feeding frequency by life stage, the case for meal feeding over free choice, and the timing considerations that matter.",
    toc: [
      { label: 'Frequency by Life Stage', id: 'lifestage' },
      { label: 'Meal Feeding vs Free Choice', id: 'mealfeeding' },
      { label: 'The Bloat Consideration', id: 'bloat' },
      { label: 'Cats and Small Meals', id: 'cats' },
      { label: 'Timing and Medication', id: 'timing' },
      { label: 'Building a Schedule', id: 'schedule' },
    ],
    body: [
      { p: "Feeding frequency affects body weight control, digestive comfort, and the management of several conditions. While there is flexibility, some patterns are better supported than others: puppies and kittens need frequent meals, most adults do well on two meals a day, and free-choice feeding works against weight control in most pets. The right schedule balances physiology, the household routine, and any medical needs." },
      { h2: 'Frequency by Life Stage', id: 'lifestage' },
      { p: "Young puppies and kittens have small stomachs and high energy needs and should be fed three to four times daily, reducing to twice daily as they mature. Most adult dogs and cats do well on two meals a day. Some toy-breed puppies are prone to hypoglycemia and need frequent feeding. Pregnant and lactating animals need increased frequency and amount. See [[Puppy and Kitten Growth Diets|/diets/puppy-and-kitten-growth-diets]]." },
      { h2: 'Meal Feeding vs Free Choice', id: 'mealfeeding' },
      { p: "Free-choice (food left out continuously) makes intake invisible and overfeeding likely, and it prevents the appetite monitoring that often gives the first sign of illness. Measured meals let you count calories, notice when an animal goes off its food, and control weight. For multi-pet households, meal feeding also prevents one animal monopolizing the bowl. Meal feeding is preferred for most pets. See [[Body Condition Scoring|/feeding/body-condition-scoring]]." },
      { h2: 'The Bloat Consideration', id: 'bloat' },
      { p: "Gastric dilatation-volvulus (bloat) is a life-threatening emergency in large and giant deep-chested breeds. While the causes are multifactorial, risk-reduction recommendations include feeding two or more smaller meals rather than one large meal, avoiding vigorous exercise immediately around meals, and slowing fast eaters with a slow-feeder bowl. Elevated feeders were once recommended but evidence is mixed. These measures reduce but do not eliminate risk." },
      { h2: 'Cats and Small Meals', id: 'cats' },
      { p: "Cats are natural grazers that, in the wild, eat many small prey-sized meals across the day. Several measured small meals, or a measured daily portion delivered through puzzle feeders, suit feline physiology while still controlling total calories. Timed automatic feeders can deliver small measured meals for cats whose owners are away. See [[How Much to Feed a Cat|/feeding/how-much-to-feed-a-cat]]." },
      { h2: 'Timing and Medication', id: 'timing' },
      { p: "For diabetic animals, meals are timed to insulin injections so glucose load and insulin peak align — a fixed schedule is essential. Some medications must be given with food; others on an empty stomach. Animals prone to bilious vomiting (an empty-stomach nausea, often early morning) may benefit from a late-evening snack. Medical timing needs are set with the veterinarian. See [[Diabetic Diets|/diets/diabetic-diets]]." },
      { h2: 'Building a Schedule', id: 'schedule' },
      { p: "A practical default for a healthy adult is two measured meals roughly 10 to 12 hours apart, with treats counted within the daily calorie budget. Keep the schedule consistent day to day, which supports digestion and makes house-training and litter-box routines predictable. Adjust for life stage, medical needs, and the household, but keep meals measured and intake monitored. See [[Treats and the 10 Percent Rule|/feeding/treats-and-the-ten-percent-rule]]." },
    ],
    related: [
      { label: 'How Much to Feed a Cat', href: '/feeding/how-much-to-feed-a-cat' },
      { label: 'Treats and the 10 Percent Rule', href: '/feeding/treats-and-the-ten-percent-rule' },
      { label: 'Diabetic Diets for Dogs and Cats', href: '/diets/diabetic-diets' },
    ],
    sources: [...STD],
  },

  {
    dir: D, slug: 'treats-and-the-ten-percent-rule', date: '2026-06-01',
    title: 'Treats and the 10 Percent Rule',
    metaTitle: 'Pet Treats and the 10 Percent Rule | PetFood.com',
    metaDesc:
      'Why treats should stay under 10 percent of daily calories, how treat calories sabotage diets, training-treat strategies, and safe and unsafe human foods.',
    category: 'Feeding Guide', readTime: '8 min',
    hero:
      "Treats are where good feeding plans quietly fall apart. They are calorie-dense, easy to give without counting, and capable of unbalancing an otherwise complete diet. The widely used guideline is that treats should not exceed 10 percent of daily calories. This page explains the rule, the math, and how to treat without overfeeding.",
    toc: [
      { label: 'The 10 Percent Rule', id: 'rule' },
      { label: 'Why Treats Sabotage Diets', id: 'sabotage' },
      { label: 'Treat Calorie Math', id: 'math' },
      { label: 'Training-Treat Strategies', id: 'training' },
      { label: 'Human Foods — Safe and Unsafe', id: 'human' },
      { label: 'Dental and Functional Treats', id: 'functional' },
    ],
    body: [
      { p: "Treats serve real purposes — training, bonding, enrichment, medication delivery — but they are not nutritionally complete and they add calories. The standard veterinary guideline is that treats and table foods should make up no more than 10 percent of an animal's daily calorie intake, with the remaining 90 percent coming from a complete and balanced diet. This keeps the complete diet doing its job and prevents treat calories from driving weight gain." },
      { h2: 'The 10 Percent Rule', id: 'rule' },
      { p: "The 10 percent guideline exists for two reasons. First, treats are usually not complete and balanced, so a large share of treats dilutes the balanced nutrition of the main diet. Second, treats are calorie-dense, and even a few can represent a substantial fraction of a small animal's daily allowance. Keeping treats under 10 percent protects both the nutritional balance and the calorie budget." },
      { h2: 'Why Treats Sabotage Diets', id: 'sabotage' },
      { p: "Treat calories are the most commonly overlooked input in a weight problem. A single large dog biscuit can carry 100 or more calories — a meaningful fraction of a small dog's daily need — and households often give treats from multiple people without coordination. When a weight-loss plan stalls, untracked treats are the usual culprit. Counting treat calories against the daily budget is essential. See [[Weight-Management Diets|/diets/weight-management-diets]]." },
      { h2: 'Treat Calorie Math', id: 'math' },
      { p: "To apply the rule, calculate 10 percent of the daily energy requirement and keep treats within it, subtracting treat calories from the main-meal portion so total intake stays constant. For a dog needing 1000 kcal per day, treats should stay under about 100 kcal, and the meals should be reduced to make room. Many treat packages now list calories; for those that do not, the manufacturer can provide the figure. See [[Pet Food Calories and Energy Density|/nutrition/calories-and-energy-density]]." },
      { h2: 'Training-Treat Strategies', id: 'training' },
      { p: "Training requires many repetitions, which can blow the calorie budget if each reward is a full treat. Use very small pieces (a treat broken into ten), low-calorie options (a piece of the animal's own kibble counted from the daily ration, or small bits of approved vegetables), and reserve high-value treats for the hardest tasks. The reward value comes from frequency and timing, not size." },
      { h2: 'Human Foods — Safe and Unsafe', id: 'human' },
      { p: "Some human foods make reasonable low-calorie treats in moderation — plain cooked lean meat, certain vegetables like green beans and carrots, plain pumpkin. Others are toxic and must never be given: chocolate, xylitol (a sweetener in gum and some peanut butters), grapes and raisins, onions and garlic, macadamia nuts, and alcohol, among others. When in doubt, do not give it, and consult the veterinarian or a poison-control resource. See [[Pet Food Myths|/myths]]." },
      { h2: 'Dental and Functional Treats', id: 'functional' },
      { p: "Dental chews and functional treats carry calories like any other treat and must be counted within the 10 percent. Some dental products carry the Veterinary Oral Health Council (VOHC) seal, indicating they meet a standard for reducing plaque or tartar. Functional claims (joint, calming) on treats are generally less substantiated than on therapeutic diets; evaluate the active ingredient and dose rather than the marketing. See [[Glucosamine and Joint Supplements|/supplements/glucosamine-and-joint-support]]." },
    ],
    related: [
      { label: 'Pet Food Calories and Energy Density', href: '/nutrition/calories-and-energy-density' },
      { label: 'Weight-Management Diets', href: '/diets/weight-management-diets' },
      { label: 'Feeding Frequency and Schedules', href: '/feeding/feeding-frequency-and-schedules' },
    ],
    sources: [...STD],
  },

  {
    dir: D, slug: 'large-breed-puppy-nutrition', date: '2026-06-01',
    title: 'Large-Breed Puppy Nutrition',
    metaTitle: 'Large-Breed Puppy Nutrition and the Calcium Ceiling | PetFood.com',
    metaDesc:
      'Why large-breed puppies need a specific diet, the calcium ceiling and developmental orthopedic disease, controlled growth rate, and reading the AAFCO statement.',
    category: 'Feeding Guide', readTime: '10 min',
    hero:
      "Large- and giant-breed puppies are the one group where the wrong puppy food can cause lifelong skeletal disease. The culprit is excess calcium and over-rapid growth during the critical developmental window. This page explains the calcium ceiling, the case for controlled (not maximized) growth, and exactly what to check on the label.",
    toc: [
      { label: 'The Unique Risk', id: 'risk' },
      { label: 'Developmental Orthopedic Disease', id: 'dod' },
      { label: 'The Calcium Ceiling', id: 'calcium' },
      { label: 'Controlled Growth Rate', id: 'growth' },
      { label: 'Reading the Label', id: 'label' },
      { label: 'When to Switch to Adult', id: 'switch' },
    ],
    body: [
      { p: "Puppies expected to reach 70 pounds or more as adults grow over a longer window and are uniquely sensitive to dietary calcium and to over-rapid growth. Feeding them a standard puppy or all-life-stages food not validated for large-size growth, or over-supplementing calcium, raises the risk of developmental orthopedic disease — joint and bone abnormalities that can cause lifelong lameness. This is the clearest case in which the specific diet, and the feeding amount, materially affect long-term health." },
      { h2: 'The Unique Risk', id: 'risk' },
      { p: "Unlike small breeds, large-breed puppies cannot fully regulate calcium absorption when dietary calcium is high — excess calcium is absorbed and interferes with normal skeletal development. Combined with the long growth period of large breeds and the temptation to feed for maximum size, this creates a window of vulnerability that the right diet manages and the wrong diet aggravates. See [[Puppy and Kitten Growth Diets|/diets/puppy-and-kitten-growth-diets]]." },
      { h2: 'Developmental Orthopedic Disease', id: 'dod' },
      { p: "Developmental orthopedic diseases include osteochondrosis, hip and elbow dysplasia, and angular limb deformities. Excess calcium, excess energy (driving rapid growth and weight), and excess weight on developing joints all contribute. Genetics set the predisposition, but nutrition is a modifiable factor — which is why dietary management during growth is a genuine intervention, not just feeding preference." },
      { h2: 'The Calcium Ceiling', id: 'calcium' },
      { p: "AAFCO established a separate growth profile for large-size dogs with a tighter calcium maximum (the safe upper limit is lower than for small-breed growth). A diet labeled for growth including large-size growth has been formulated to stay under this ceiling. A standard growth or all-life-stages food not so validated can legally contain more calcium than is safe for a giant-breed puppy. See [[Minerals in Pet Food|/nutrition/minerals-in-pet-food]]." },
      { h2: 'Controlled Growth Rate', id: 'growth' },
      { p: "The goal for large-breed puppies is steady, moderate growth to a lean body condition — not the fastest or largest growth. Overfeeding to push size raises orthopedic-disease risk; a lean body condition during growth is protective. The adult size is determined by genetics regardless of how fast the puppy is grown, so feeding for maximum growth gains nothing and adds risk. Keep the puppy lean (body condition score 4 to 5) throughout growth. See [[Body Condition Scoring|/feeding/body-condition-scoring]]." },
      { h2: 'Reading the Label', id: 'label' },
      { p: "Check the AAFCO nutritional adequacy statement specifically for large-size growth wording: it should read, in substance, formulated for (or feeding tests substantiate) growth including growth of large size dogs (70 pounds or more as an adult), or all life stages including large-size growth. An all-life-stages food that omits the large-size growth wording has not been validated against the tighter calcium ceiling. See [[AAFCO Completeness Explained|/guides/aafco-completeness-explained]]." },
      { h2: 'When to Switch to Adult', id: 'switch' },
      { p: "Large-breed puppies grow for longer than small breeds and are typically kept on an appropriate large-breed growth (or validated all-life-stages) diet until they approach skeletal maturity, often 12 to 24 months depending on breed. The timing is individualized and best confirmed with the veterinarian, who can assess growth and body condition. Switching too early can shortchange growth nutrition; switching appropriately avoids prolonged excess energy intake." },
    ],
    related: [
      { label: 'Puppy and Kitten Growth Diets', href: '/diets/puppy-and-kitten-growth-diets' },
      { label: 'Minerals in Pet Food', href: '/nutrition/minerals-in-pet-food' },
      { label: 'AAFCO Completeness Explained', href: '/guides/aafco-completeness-explained' },
    ],
    sources: [...STD],
  },

  {
    dir: D, slug: 'feeding-multiple-pets', date: '2026-06-01',
    title: 'Feeding Multiple Pets in One Household',
    metaTitle: 'Feeding Multiple Pets in One Household | PetFood.com',
    metaDesc:
      'How to feed multi-pet households with different needs, preventing food stealing, feeding dogs and cats separately, and managing therapeutic diets in a group.',
    category: 'Feeding Guide', readTime: '8 min',
    hero:
      "Multi-pet households turn feeding into a logistics problem: different animals need different amounts, different foods, and sometimes a therapeutic diet that must not be eaten by the others. Free-feeding a group almost guarantees that someone is over- and someone under-fed. This page covers separation strategies, dog-and-cat dynamics, and managing prescription diets in a group.",
    toc: [
      { label: 'The Core Problem', id: 'problem' },
      { label: 'Separated Meal Feeding', id: 'separated' },
      { label: 'Dogs and Cats Together', id: 'dogscats' },
      { label: 'Therapeutic Diets in a Group', id: 'therapeutic' },
      { label: 'Microchip and Selective Feeders', id: 'feeders' },
      { label: 'Monitoring Each Animal', id: 'monitoring' },
    ],
    body: [
      { p: "When several animals share a home, free-choice feeding makes it impossible to know who ate what, and it lets the fastest or most food-motivated animal overeat while a slower or sicker one is crowded out. The solution is structured, separated feeding, with portions matched to each animal's needs. This matters most when animals differ in size, life stage, body condition, or medical needs." },
      { h2: 'The Core Problem', id: 'problem' },
      { p: "Different animals have different calorie needs, different life-stage diets, and sometimes a therapeutic diet that is harmful if eaten by the wrong animal. A shared bowl cannot meet these differing needs and obscures intake. The first principle of multi-pet feeding is that each animal's portion must be controllable and observable. See [[How Much to Feed a Dog|/feeding/how-much-to-feed-a-dog]]." },
      { h2: 'Separated Meal Feeding', id: 'separated' },
      { p: "The simplest reliable approach is scheduled meals with animals fed in separate locations — different rooms, crates, or sides of a barrier — for the duration of the meal, with bowls picked up afterward. This guarantees each animal gets its own portion and prevents stealing. It also lets you see exactly how much each animal eats, which is the earliest sign many illnesses give. See [[Feeding Frequency and Schedules|/feeding/feeding-frequency-and-schedules]]." },
      { h2: 'Dogs and Cats Together', id: 'dogscats' },
      { p: "Dogs frequently raid cat food, which is higher in protein and fat and can drive canine weight gain, and they raid litter boxes. Cat food is also nutritionally inappropriate as a dog's main diet and vice versa — a cat cannot live on dog food, which lacks adequate taurine, arachidonic acid, and pre-formed vitamin A. Feed cats on elevated surfaces or behind cat-sized barriers the dog cannot pass, and keep the species on their own species-appropriate diets. See [[Dog vs Cat Nutrition|/species/dog-vs-cat-nutrition-overview]]." },
      { h2: 'Therapeutic Diets in a Group', id: 'therapeutic' },
      { p: "When one animal needs a prescription diet, the others should not eat it (it may be inappropriate for them), and the patient must not eat the others' food (which defeats the therapeutic purpose, especially during an elimination-diet trial). Strict separation at mealtimes, no free-choice food anywhere, and household-wide discipline on treats are essential. An elimination-diet trial in a multi-pet home is only valid if the patient eats nothing but the trial diet. See [[Food Allergy and Elimination Diets|/diets/food-allergy-and-elimination-diets]]." },
      { h2: 'Microchip and Selective Feeders', id: 'feeders' },
      { p: "Microchip-activated feeders open only for the registered animal, allowing free-access feeding tailored to each pet — useful for cats that graze, for protecting a therapeutic diet, or for keeping one animal out of another's food. They are a practical tool in homes where strict mealtime separation is hard to maintain, though they work best for cats and small dogs and require the animals to accept them." },
      { h2: 'Monitoring Each Animal', id: 'monitoring' },
      { p: "Separated feeding makes individual monitoring possible: track each animal's intake, weigh and body-condition-score each one regularly, and watch for changes in appetite that a shared bowl would hide. In a multi-pet home, a drop in one animal's appetite is easy to miss without separation, yet it is often the first sign of illness. See [[Body Condition Scoring|/feeding/body-condition-scoring]]." },
    ],
    related: [
      { label: 'How Much to Feed a Dog', href: '/feeding/how-much-to-feed-a-dog' },
      { label: 'Dog vs Cat Nutrition', href: '/species/dog-vs-cat-nutrition-overview' },
      { label: 'Food Allergy and Elimination Diets', href: '/diets/food-allergy-and-elimination-diets' },
    ],
    sources: [...STD],
  },

  {
    dir: D, slug: 'food-storage-and-safety', date: '2026-06-01',
    title: 'Pet Food Storage and Safety',
    metaTitle: 'Pet Food Storage and Safety — Spoilage and Handling | PetFood.com',
    metaDesc:
      'How to store kibble and canned food to prevent rancidity and contamination, the case against decanting, handling raw and fresh food, and recall awareness.',
    category: 'Feeding Guide', readTime: '8 min',
    hero:
      "Good food can be spoiled by poor storage. Fat oxidation, moisture, pantry pests, and cross-contamination all degrade pet food after it leaves the bag, and improper handling of raw and fresh diets introduces pathogen risk to the household. This page covers storage best practice, the surprising case against decanting kibble, and recall awareness.",
    toc: [
      { label: 'How Pet Food Spoils', id: 'spoils' },
      { label: 'Storing Dry Food', id: 'dry' },
      { label: 'The Case Against Decanting', id: 'decanting' },
      { label: 'Storing Canned and Fresh', id: 'wet' },
      { label: 'Handling Raw Diets', id: 'raw' },
      { label: 'Recall Awareness', id: 'recall' },
    ],
    body: [
      { p: "Once a bag is opened, pet food begins to degrade through fat oxidation (rancidity), moisture uptake, and exposure to air, light, heat, and pests. Spoiled food loses palatability and nutritional value — oxidation destroys fat-soluble vitamins and essential fatty acids — and contaminated food poses a safety risk. Proper storage preserves quality through the best-by window, and proper handling prevents foodborne illness in pets and people. See [[Preservatives in Pet Food|/ingredients/preservatives-pet-food]]." },
      { h2: 'How Pet Food Spoils', id: 'spoils' },
      { p: "The main spoilage pathway for dry food is oxidation of the fats, which produces rancid off-flavors and destroys nutrients, accelerated by air, heat, and light. Foods preserved with natural antioxidants (mixed tocopherols, rosemary) oxidize faster than those with synthetic preservatives, so natural-preserved foods have shorter shelf lives once opened. Moisture uptake also promotes mold, and warmth invites pantry-moth and beetle infestation." },
      { h2: 'Storing Dry Food', id: 'dry' },
      { p: "Keep dry food in its original bag, sealed, in a cool, dry, dark place, and use it within the best-by date and ideally within a few weeks of opening. The original bag is engineered with a fat- and oxygen-barrier liner that an ordinary container lacks. Buy a bag size the household will finish before it goes stale rather than the largest bag for cost savings if that means months of open storage." },
      { h2: 'The Case Against Decanting', id: 'decanting' },
      { p: "A common practice is to dump kibble into a plastic storage bin and discard the bag. This is suboptimal for two reasons: the bin lacks the bag's oxygen barrier, accelerating oxidation, and residual fat and crumbs build up on the bin walls, going rancid and contaminating fresh food. If a container is used, keep the food inside its original bag within the container, and wash and fully dry the container between bags. Retaining the bag also preserves the lot number and best-by date needed for any recall." },
      { h2: 'Storing Canned and Fresh', id: 'wet' },
      { p: "Unopened cans are shelf-stable until their best-by date. Once opened, canned food must be refrigerated, covered, and used within a few days (commonly cited as up to about five to seven days, per manufacturer guidance). Do not leave wet food in the bowl for more than an hour or two at room temperature, as it spoils and grows bacteria. Fresh and gently cooked commercial diets follow refrigeration and use-by rules similar to human perishable food." },
      { h2: 'Handling Raw Diets', id: 'raw' },
      { p: "Raw diets carry the highest handling-safety burden because of pathogen risk (Salmonella, Listeria, Campylobacter) to both pets and the household. Handle raw pet food like raw meat for humans: keep it frozen until use, thaw in the refrigerator, prevent cross-contamination with human-food surfaces, wash hands and all contact surfaces and bowls thoroughly, and pick up uneaten food promptly. The major veterinary bodies caution against raw diets partly because of these risks. See [[Raw vs Cooked Diets|/compare/raw-vs-cooked-diets]] and the [[Raw Pet Food Evaluation|/guides/raw-pet-food-evaluation]]." },
      { h2: 'Recall Awareness', id: 'recall' },
      { p: "Pet food recalls happen — for pathogen contamination, formulation errors (such as toxic vitamin D levels), or foreign material. Keep the original bag or can with its lot number and best-by date so a recalled product can be identified, and check the FDA CVM Recalls and Withdrawals database periodically or sign up for alerts. If a food is recalled, stop feeding it and follow the manufacturer and FDA instructions. See [[Pet Food Recalls and the FDA|/guides/pet-food-recalls-and-fda]]." },
    ],
    related: [
      { label: 'Preservatives in Pet Food', href: '/ingredients/preservatives-pet-food' },
      { label: 'Raw vs Cooked Diets', href: '/compare/raw-vs-cooked-diets' },
      { label: 'Pet Food Recalls and the FDA', href: '/guides/pet-food-recalls-and-fda' },
    ],
    sources: [...STD, SRC.fdaPet],
  },

  {
    dir: D, slug: 'calorie-calculator-guide', date: '2026-06-01',
    title: 'Using a Pet Calorie Calculator',
    metaTitle: 'How to Use a Pet Calorie Calculator | PetFood.com',
    metaDesc:
      'How calorie calculators estimate daily energy needs, the inputs that matter, the limits of any formula, and how to translate the result into a real portion.',
    category: 'Feeding Guide', readTime: '8 min',
    hero:
      "A calorie calculator turns a few inputs — weight, body condition, life stage, activity — into an estimated daily energy requirement, and it is a useful starting point for portioning. But it is only an estimate, and the real correction comes from watching the animal. This page explains how the calculation works, its limits, and how to use the result well. It companions our food-cost tool.",
    toc: [
      { label: 'What a Calculator Computes', id: 'computes' },
      { label: 'The Inputs That Matter', id: 'inputs' },
      { label: 'The Underlying Formula', id: 'formula' },
      { label: 'Why It Is Only an Estimate', id: 'estimate' },
      { label: 'Turning Calories into a Portion', id: 'portion' },
      { label: 'Verifying with the Animal', id: 'verifying' },
    ],
    body: [
      { p: "A pet calorie calculator estimates how many kilocalories an animal needs per day, from which a feeding amount can be derived. It applies the same resting-energy and activity-factor math a veterinarian uses, packaged into a few inputs. The result is a starting estimate, not a precise prescription, and it should be combined with the food's calorie statement and ongoing body-condition monitoring. It pairs with the [[Food Cost Calculator|/tools/food-cost-calculator]]." },
      { h2: 'What a Calculator Computes', id: 'computes' },
      { p: "The calculator estimates the daily energy requirement (also called maintenance energy requirement) — the calories needed to maintain current weight given the animal's size, life stage, and activity. From that figure, and the calorie density of the chosen food, the daily portion follows. The calculator does the energy math; the portion still requires the food's kcal-per-cup. See [[Pet Food Calories and Energy Density|/nutrition/calories-and-energy-density]]." },
      { h2: 'The Inputs That Matter', id: 'inputs' },
      { p: "Key inputs are current body weight, body condition score (so a calculation for an overweight animal can target the ideal weight, not the current one), life stage (puppy, kitten, adult, senior), neuter status, and activity level. Some calculators also account for weight-loss versus maintenance goals. The body-condition input matters most: feeding to maintain an overweight animal's current weight just keeps it overweight. See [[Body Condition Scoring|/feeding/body-condition-scoring]]." },
      { h2: 'The Underlying Formula', id: 'formula' },
      { p: "Under the hood, the calculator computes resting energy requirement (RER), commonly 70 times body weight in kilograms to the 0.75 power, then multiplies by an activity factor for life stage, neuter status, and activity. For example, a neutered adult dog uses a factor around 1.6, an indoor neutered cat around 1.2, a puppy up to about 3.0. The result is the estimated daily calories. See [[How Much to Feed a Dog|/feeding/how-much-to-feed-a-dog]] and [[How Much to Feed a Cat|/feeding/how-much-to-feed-a-cat]]." },
      { h2: 'Why It Is Only an Estimate', id: 'estimate' },
      { p: "Individual metabolism varies by 20 percent or more around the average for reasons the formula cannot capture — breed, genetics, health, and individual variation. The activity factors are population averages, not personal measurements. So the calculator gives a reasonable opening number that will need adjustment for the specific animal. Treating its output as exact, rather than as a starting point, is the common mistake." },
      { h2: 'Turning Calories into a Portion', id: 'portion' },
      { p: "Once you have the estimated daily calories, divide by the food's kilocalories per cup (from the calorie statement on the bag) to get the daily volume, then split across meals and subtract treat calories (kept within the 10 percent rule). Because calorie density differs by food, recompute the portion when you change foods. Weigh the portion on a kitchen scale rather than scooping. See [[Treats and the 10 Percent Rule|/feeding/treats-and-the-ten-percent-rule]]." },
      { h2: 'Verifying with the Animal', id: 'verifying' },
      { p: "The calculator's estimate is confirmed or corrected by the animal: reassess body condition every few weeks and adjust the amount up or down. If a dog gains on the calculated portion, its true energy needs are lower than the average factor assumed, and the amount comes down. The formula starts the process; the body-condition feedback loop finishes it. See [[Body Condition Scoring|/feeding/body-condition-scoring]]." },
    ],
    related: [
      { label: 'How Much to Feed a Dog', href: '/feeding/how-much-to-feed-a-dog' },
      { label: 'Pet Food Calories and Energy Density', href: '/nutrition/calories-and-energy-density' },
      { label: 'Body Condition Scoring', href: '/feeding/body-condition-scoring' },
    ],
    sources: [...STD],
  },
]

export const FEEDING = RAW.map((p) => ({ ...p, hubName: 'Feeding' }))
