import { SRC, STD } from './_shared.mjs'

const D = 'nutrition'

const RAW = [
  {
    dir: D, slug: 'dietary-protein-requirements', date: '2026-05-30',
    title: 'Dietary Protein for Dogs and Cats',
    metaTitle: 'Dietary Protein Requirements — Dogs and Cats | PetFood.com',
    metaDesc:
      'How protein requirements differ between dogs and cats, what crude protein on the guaranteed analysis does and does not tell you, and how AAFCO sets the minima.',
    category: 'Nutrition Fundamentals', readTime: '11 min',
    hero:
      "Protein is the most-marketed and least-understood macronutrient on a pet food bag. Crude protein on the guaranteed analysis is a nitrogen estimate, not a quality measure, and the species difference between dogs and cats is larger than most owners realize. This page works through requirements, digestibility, amino-acid completeness, and the gap between the headline percentage and the biological value of the protein in the bowl.",
    toc: [
      { label: 'What Protein Does', id: 'function' },
      { label: 'Crude Protein vs Quality', id: 'crude' },
      { label: 'Cats — Obligate Carnivores', id: 'cats' },
      { label: 'Dogs — Facultative Omnivores', id: 'dogs' },
      { label: 'AAFCO Minimums', id: 'aafco' },
      { label: 'Reading the Label', id: 'label' },
    ],
    body: [
      { p: "Protein supplies the amino acids an animal uses to build and repair tissue, synthesize enzymes and hormones, and (when dietary energy is short) generate glucose. Eleven amino acids are essential for dogs and eleven for cats, meaning the animal cannot synthesize them fast enough to meet its needs and must obtain them from the diet. Cats add taurine to that essential list because their hepatic synthesis from cysteine and methionine is inadequate. The total quantity of protein matters, but the amino-acid distribution and the digestibility of the protein source matter just as much." },
      { h2: 'What Protein Does', id: 'function' },
      { p: "Unlike carbohydrate and fat, protein is not stored in a dedicated reserve. The body maintains a small labile amino-acid pool and otherwise draws on functional tissue (muscle) when intake is inadequate. A diet that is low in usable protein produces muscle loss, poor coat quality, depressed immune function, and slowed wound healing before it produces any obvious clinical sign. Conversely, protein consumed beyond requirement is deaminated and the carbon skeleton used for energy or stored as fat; the nitrogen is excreted as urea. Healthy kidneys handle that load without difficulty." },
      { h2: 'Crude Protein vs Protein Quality', id: 'crude' },
      { p: "The guaranteed analysis lists a crude protein minimum. Crude protein is calculated from total nitrogen multiplied by 6.25 — it measures nitrogen, not protein quality. Two foods can show identical crude protein and differ enormously in biological value. A diet built on highly digestible animal muscle delivers a complete, well-absorbed amino-acid profile; a diet padded with low-digestibility connective tissue or with a plant-protein isolate added to inflate the nitrogen number can hit the same crude-protein figure while delivering inferior amino-acid completeness. Digestibility — the fraction of ingested protein actually absorbed — typically ranges from roughly 75 percent for lower-grade ingredients to over 90 percent for high-quality animal protein. The label discloses none of this; the ingredient panel is the best available proxy. See [[Animal Protein Sources|/ingredients/animal-protein-sources]]." },
      { p: "Crude protein is also reported on an as-fed basis, which makes wet and dry foods look incomparable. A canned food at 10 percent crude protein as-fed and a kibble at 30 percent are far closer once converted to a dry-matter basis, because the canned food is roughly 78 percent water. Any cross-format protein comparison must be done on a dry-matter basis. See [[Dry-Matter Basis Explained|/nutrition/dry-matter-basis-explained]]." },
      { h2: 'Cats — Obligate Carnivores', id: 'cats' },
      { p: "Cats have a higher absolute protein requirement than dogs and a limited ability to downregulate the hepatic enzymes that catabolize protein. Even when dietary protein is scarce, a cat continues to use amino acids for gluconeogenesis at a high rate, which is why protein-restricted diets are riskier for cats than for dogs. The AAFCO Cat Food Nutrient Profile sets a minimum crude protein of 30 percent dry-matter for adult maintenance and 30 percent for growth and reproduction, against the dog figures below. Cats also have specific requirements — taurine, arginine, and the sulfur amino acids — at levels that animal protein meets readily and plant protein meets poorly. A cat fed a predominantly plant-protein diet requires careful supplementation. See [[Dog vs Cat Nutrition|/species/dog-vs-cat-nutrition-overview]]." },
      { h2: 'Dogs — Facultative Omnivores', id: 'dogs' },
      { p: "Dogs are metabolically more flexible. They can downregulate protein catabolism when intake is low, synthesize taurine adequately in most breeds, and derive usable nutrition from a broader ingredient base. The AAFCO Dog Food Nutrient Profile sets a minimum crude protein of 18 percent dry-matter for adult maintenance and 22.5 percent for growth and reproduction. These are minima for adequacy, not optima for every dog: working dogs, growing puppies, and pregnant or lactating dams benefit from intake well above the floor, while sedentary adults rarely need the very high protein levels marketed on some premium bags." },
      { h2: 'AAFCO Minimums', id: 'aafco' },
      { p: "The AAFCO profiles express requirements as minimums (and, for some nutrients, maximums) on a dry-matter basis, assuming a food of typical energy density. Because requirements scale with energy intake, AAFCO also publishes the profiles on a per-1000-kcal metabolizable-energy basis; a very energy-dense food must carry proportionally more protein per kilogram to deliver the same amount per calorie eaten. A label statement of complete and balanced for a life stage means the manufacturer attests the food meets these profiles via formulation or feeding trial. See [[AAFCO Completeness Explained|/guides/aafco-completeness-explained]]." },
      { h2: 'Reading the Protein Claim on a Label', id: 'label' },
      { ol: [
        "Read crude protein on the guaranteed analysis as a floor, not a quality grade. A high number is not automatically better.",
        "Look at the first five ingredients. Named animal proteins early in the list signal a higher-quality amino-acid base than plant-protein isolates added to lift the nitrogen figure.",
        "Convert to dry-matter before comparing a canned food with a kibble.",
        "For cats, confirm animal protein leads the ingredient panel; obligate-carnivore amino-acid needs are met poorly by plants alone.",
        "Check the AAFCO statement for the correct life stage — growth and reproduction carry higher protein minima than adult maintenance.",
      ]},
    ],
    related: [
      { label: 'Animal Protein Sources', href: '/ingredients/animal-protein-sources' },
      { label: 'Dry-Matter Basis Explained', href: '/nutrition/dry-matter-basis-explained' },
      { label: 'AAFCO Completeness Explained', href: '/guides/aafco-completeness-explained' },
    ],
    sources: [...STD],
  },

  {
    dir: D, slug: 'dietary-fat-and-fatty-acids', date: '2026-05-30',
    title: 'Dietary Fat and Essential Fatty Acids',
    metaTitle: 'Dietary Fat and Fatty Acids in Pet Food | PetFood.com',
    metaDesc:
      'The role of fat in pet diets, essential fatty acids (linoleic, alpha-linolenic, arachidonic, EPA, DHA), the omega-6 to omega-3 ratio, and AAFCO fat minima.',
    category: 'Nutrition Fundamentals', readTime: '11 min',
    hero:
      "Fat is the most energy-dense macronutrient, the carrier for fat-soluble vitamins, and the source of the essential fatty acids that drive skin, coat, and inflammatory-pathway health. It is also the macronutrient most often mismanaged, both by owners who fear it and by diets that supply the wrong fatty-acid balance. This page covers the essential fatty acids, the omega ratio, and what the guaranteed analysis fat figure means.",
    toc: [
      { label: 'Why Fat Matters', id: 'why' },
      { label: 'Essential Fatty Acids', id: 'efa' },
      { label: 'Omega-6 to Omega-3 Ratio', id: 'ratio' },
      { label: 'EPA and DHA', id: 'epadha' },
      { label: 'AAFCO Fat Minimums', id: 'aafco' },
      { label: 'Rancidity and Preservation', id: 'rancidity' },
    ],
    body: [
      { p: "Fat supplies roughly 8.5 kilocalories of metabolizable energy per gram — more than twice the energy density of protein or carbohydrate. Beyond energy, dietary fat carries the fat-soluble vitamins A, D, E, and K, improves diet palatability, and provides the essential fatty acids the body cannot synthesize. A diet too low in fat produces a dull, flaky coat and impaired fat-soluble vitamin status; a diet too high in fat, fed without matching energy expenditure, drives weight gain and, in predisposed dogs, can trigger pancreatitis." },
      { h2: 'Why Fat Matters', id: 'why' },
      { p: "Because fat is so energy-dense, the fat content of a food largely determines its caloric density. Two foods of identical protein can differ substantially in calories per cup driven by fat. This is why feeding guidelines and the energy math on the bag matter: a higher-fat performance food fed at the same volume as a maintenance food delivers more calories. See [[Pet Food Calories and Energy Density|/nutrition/calories-and-energy-density]]." },
      { h2: 'Essential Fatty Acids', id: 'efa' },
      { p: "Dogs require linoleic acid (an omega-6) and benefit from alpha-linolenic acid (an omega-3). Cats, lacking adequate delta-6-desaturase activity, additionally require pre-formed arachidonic acid (an omega-6) in the diet — a requirement met by animal fat and not by plant oils. This is one of the clearest biochemical reasons a cat cannot be maintained on a plant-only diet without specific supplementation. The AAFCO Cat Food Nutrient Profile lists arachidonic acid as a required nutrient; the Dog Food Nutrient Profile does not." },
      { h2: 'The Omega-6 to Omega-3 Ratio', id: 'ratio' },
      { p: "Omega-6 fatty acids tend to produce pro-inflammatory eicosanoids, while the long-chain omega-3s EPA and DHA produce less-inflammatory mediators. The dietary ratio of the two families influences the inflammatory tone of the body. Typical grain-and-poultry-fat kibble runs heavily omega-6. Many veterinary therapeutic skin and joint diets deliberately lower the ratio by adding fish oil. There is no single universally agreed optimal ratio, but most formulators and the NRC target a ratio well below the omega-6-dominant pattern of an unsupplemented commodity diet." },
      { h2: 'EPA and DHA', id: 'epadha' },
      { p: "Eicosapentaenoic acid (EPA) and docosahexaenoic acid (DHA) are the long-chain marine omega-3s with the strongest evidence base. DHA is important for neural and retinal development in puppies and kittens, which is why growth and reproduction diets are often DHA-supplemented. EPA and DHA together have evidence for supporting joint comfort in osteoarthritis and for skin and coat health. Dogs and cats convert alpha-linolenic acid to EPA and DHA inefficiently, so the marine-sourced pre-formed forms are more reliable than plant-oil precursors. See [[Fish Oil and Omega-3 Supplements|/supplements/fish-oil-omega-3]]." },
      { h2: 'AAFCO Fat Minimums', id: 'aafco' },
      { p: "The AAFCO Dog Food Nutrient Profile sets a minimum crude fat of 5.5 percent dry-matter for adult maintenance and 8.5 percent for growth and reproduction, with a linoleic-acid minimum. The Cat Food Nutrient Profile sets 9 percent crude fat dry-matter for both adult maintenance and growth, with linoleic and arachidonic acid minima. These are floors; many complete diets carry considerably more fat, which is appropriate as long as total energy intake is managed." },
      { h2: 'Rancidity and Preservation', id: 'rancidity' },
      { p: "Dietary fats oxidize over time, producing rancid off-flavors and destroying fat-soluble vitamins and essential fatty acids. This is why fat-containing foods require antioxidant preservation — either natural (mixed tocopherols, rosemary extract) or synthetic (BHA, BHT, ethoxyquin). Natural preservatives have a shorter effective window, which shortens shelf life. Storage matters: keep food sealed, cool, and used within the best-by window. See [[Preservatives in Pet Food|/ingredients/preservatives-pet-food]]." },
    ],
    related: [
      { label: 'Pet Food Calories and Energy Density', href: '/nutrition/calories-and-energy-density' },
      { label: 'Fish Oil and Omega-3 Supplements', href: '/supplements/fish-oil-omega-3' },
      { label: 'Preservatives in Pet Food', href: '/ingredients/preservatives-pet-food' },
    ],
    sources: [...STD],
  },

  {
    dir: D, slug: 'carbohydrates-in-pet-food', date: '2026-05-30',
    title: 'Carbohydrates in Pet Food',
    metaTitle: 'Carbohydrates in Pet Food — Are They Necessary? | PetFood.com',
    metaDesc:
      'Whether dogs and cats need dietary carbohydrate, how starch is used in extrusion, fiber types, glycemic considerations, and why "no carbohydrate minimum" is widely misread.',
    category: 'Nutrition Fundamentals', readTime: '11 min',
    hero:
      "Carbohydrate is the macronutrient with no AAFCO minimum, which marketing has converted into the claim that carbohydrate is unnecessary or harmful. The biochemistry is more nuanced: dogs and cats have no specific dietary carbohydrate requirement, but starch plays a real functional role in dry food, and fiber is genuinely beneficial. This page separates the formulation reality from the grain-free marketing narrative.",
    toc: [
      { label: 'Is Carbohydrate Required?', id: 'required' },
      { label: 'Starch and Extrusion', id: 'starch' },
      { label: 'Fiber — Soluble and Insoluble', id: 'fiber' },
      { label: 'Glycemic Considerations', id: 'glycemic' },
      { label: 'Cats and Carbohydrate', id: 'cats' },
      { label: 'Reading Carbohydrate on a Label', id: 'label' },
    ],
    body: [
      { p: "Carbohydrate is the only macronutrient for which AAFCO sets no minimum, because dogs and cats can meet their glucose needs through gluconeogenesis from protein and glycerol. That fact is correct and is the kernel of truth inside grain-free marketing. It does not follow that dietary carbohydrate is harmful, nor that a low-carbohydrate diet is automatically superior. Carbohydrate is a digestible energy source, and starch is functionally necessary to manufacture extruded kibble." },
      { h2: 'Is Carbohydrate Required?', id: 'required' },
      { p: "There is no established essential dietary carbohydrate requirement for healthy adult dogs or cats. The brain and certain tissues need glucose, but the body can supply it from non-carbohydrate precursors. The one well-documented exception is reproduction: pregnant and lactating dams (and to some extent kittens) appear to benefit from dietary carbohydrate or face metabolic stress on near-zero-carbohydrate diets. For the general adult population, carbohydrate is best understood as a usable, inexpensive energy source rather than a required nutrient." },
      { h2: 'Starch and Extrusion', id: 'starch' },
      { p: "Dry kibble is manufactured by extrusion, a process that requires gelatinized starch to bind the kibble and create its texture. This is why even grain-free dry foods contain substantial carbohydrate — they substitute potato, pea, lentil, or tapioca starch for cereal grains, but the total starch load is often similar. Grain-free is not the same as low-carbohydrate. A genuinely low-carbohydrate diet is far easier to achieve in a canned format, which does not depend on starch for structure. See [[Grain-Free vs Grain-Inclusive|/compare/grain-free-vs-grain-inclusive]]." },
      { h2: 'Fiber — Soluble and Insoluble', id: 'fiber' },
      { p: "Fiber is a carbohydrate fraction the animal does not digest directly. Insoluble fiber (cellulose, many vegetable fibers) adds bulk and supports stool quality and intestinal transit. Soluble and fermentable fibers (beet pulp, inulin, psyllium, fructooligosaccharides) are fermented by colonic bacteria into short-chain fatty acids that nourish the colonic lining and support a favorable microbiome. Therapeutic gastrointestinal and weight-management diets manipulate fiber type and quantity deliberately. See [[Fiber and Digestive Health Diets|/diets/fiber-and-digestive-health]]." },
      { h2: 'Glycemic Considerations', id: 'glycemic' },
      { p: "Different carbohydrate sources produce different post-meal blood-glucose responses. This matters most for diabetic cats and dogs, where diets are formulated to blunt glycemic spikes — for cats, typically by lowering carbohydrate sharply, and for dogs, often by emphasizing complex carbohydrate and fiber. For healthy animals, the glycemic index of the carbohydrate source is a minor consideration relative to total energy balance and body condition. See [[Diabetic Diets for Dogs and Cats|/diets/diabetic-diets]]." },
      { h2: 'Cats and Carbohydrate', id: 'cats' },
      { p: "Cats, as obligate carnivores, have a metabolism oriented toward protein and fat and a limited capacity for certain carbohydrate-handling enzymes (notably low salivary amylase and reduced intestinal disaccharidase activity relative to dogs). They tolerate moderate dietary carbohydrate but do best on protein-forward diets, and high-carbohydrate diets are one factor implicated in feline obesity and diabetes risk. This is the strongest species-specific argument for limiting carbohydrate — and it applies to cats far more than to dogs." },
      { h2: 'Reading Carbohydrate on a Label', id: 'label' },
      { p: "Carbohydrate is not listed on the guaranteed analysis. It is estimated by difference: subtract the guaranteed protein, fat, moisture, ash, and crude fiber percentages from 100. The remainder, called nitrogen-free extract, approximates the digestible carbohydrate. Because the guaranteed analysis lists minima and maxima rather than typical values, this estimate is rough; for a precise figure, request the typical (as-fed or dry-matter) analysis from the manufacturer. See [[Reading a Pet Food Label|/guides/reading-pet-food-labels]]." },
    ],
    related: [
      { label: 'Grain-Free vs Grain-Inclusive', href: '/compare/grain-free-vs-grain-inclusive' },
      { label: 'Diabetic Diets for Dogs and Cats', href: '/diets/diabetic-diets' },
      { label: 'Fiber and Digestive Health Diets', href: '/diets/fiber-and-digestive-health' },
    ],
    sources: [...STD, SRC.fdaDcm],
  },

  {
    dir: D, slug: 'calories-and-energy-density', date: '2026-05-31',
    title: 'Pet Food Calories and Energy Density',
    metaTitle: 'Pet Food Calories and Energy Density Explained | PetFood.com',
    metaDesc:
      'How metabolizable energy is calculated, what kcal/cup and kcal/kg mean, how to read the calorie statement, and why energy density drives portion size.',
    category: 'Nutrition Fundamentals', readTime: '10 min',
    hero:
      "Every weight problem and every feeding-guide error traces back to one number most owners never check: the caloric density of the food. Since 2017, AAFCO has required a calorie statement on pet food labels, but it is buried, expressed in unfamiliar units, and rarely used. This page explains metabolizable energy, the kcal/cup and kcal/kg figures, and how to turn them into a correct portion.",
    toc: [
      { label: 'Metabolizable Energy', id: 'me' },
      { label: 'The Calorie Statement', id: 'statement' },
      { label: 'kcal/cup vs kcal/kg', id: 'units' },
      { label: 'Energy Density and Portion Size', id: 'portion' },
      { label: 'Wet vs Dry Energy Density', id: 'wetdry' },
      { label: 'Using the Number', id: 'using' },
    ],
    body: [
      { p: "A calorie in nutrition is actually a kilocalorie (kcal) — the energy to raise one kilogram of water one degree Celsius. The number that matters for feeding is metabolizable energy: the energy the animal can actually extract from the food after losses to feces and urine. AAFCO and the NRC define how metabolizable energy is calculated and how it must be disclosed." },
      { h2: 'Metabolizable Energy', id: 'me' },
      { p: "Metabolizable energy (ME) is gross energy minus the energy lost in feces, urine, and (for ruminants, not relevant here) gas. For dogs and cats, ME is estimated from the protein, fat, and carbohydrate content using modified Atwater factors — approximately 3.5 kcal/g for protein, 8.5 kcal/g for fat, and 3.5 kcal/g for carbohydrate (lower than the human Atwater factors because pet diets are less digestible on average). Manufacturers may also determine ME directly by feeding trial, which is more accurate than calculation." },
      { h2: 'The Calorie Statement', id: 'statement' },
      { p: "Since the 2017 model regulation update, every complete-and-balanced pet food sold in adopting states must carry a calorie content statement expressed as kilocalories of metabolizable energy per kilogram, and per a common household unit (per cup, per can, or per treat). The statement appears in a defined format near the guaranteed analysis. Whether the ME was calculated or measured may be indicated; measured values are generally more reliable." },
      { h2: 'kcal/cup vs kcal/kg', id: 'units' },
      { p: "Two foods can differ by 30 percent or more in kcal/cup. A dense, high-fat performance kibble might run 480 kcal/cup while a weight-management kibble runs 290 kcal/cup. Feeding the same volume of each delivers very different energy. The kcal/kg figure standardizes across products by weight, which is the fairer comparison; the kcal/cup figure is the practical one for daily feeding, because owners measure by volume. Always read the calorie statement on the specific bag — calorie density varies by formula even within one brand." },
      { h2: 'Energy Density and Portion Size', id: 'portion' },
      { p: "The single most common feeding error is using the same cup count when switching foods of different density. If a dog was eating 2 cups of a 350 kcal/cup food (700 kcal/day) and switches to a 480 kcal/cup food at the same 2 cups, intake jumps to 960 kcal/day — a 37 percent increase that produces steady weight gain. To switch foods correctly, calculate the dog's daily energy requirement, then divide by the new food's kcal/cup. See [[How Much to Feed Your Dog|/feeding/how-much-to-feed-a-dog]] and the [[Food Cost Calculator|/tools/food-cost-calculator]]." },
      { h2: 'Wet vs Dry Energy Density', id: 'wetdry' },
      { p: "Canned food is roughly 75 to 80 percent water, so its energy density per gram is far lower than kibble — but its energy density per dry gram can be high, because canned diets are often fat- and protein-rich. This is why a small can may carry more calories than its size suggests, and why mixed feeding (kibble plus canned) requires summing the calories from both, not eyeballing volumes. See [[Wet vs Dry Food|/compare/wet-vs-dry-food]]." },
      { h2: 'Using the Calorie Number', id: 'using' },
      { ol: [
        "Find the calorie statement on the bag (kcal/kg and kcal/cup or kcal/can).",
        "Estimate the animal's daily energy requirement from body weight, body condition, and life stage.",
        "Divide daily energy requirement by kcal/cup to get the daily volume; split across meals.",
        "Re-measure with a kitchen scale rather than a scoop — volumetric measuring overfeeds by 20 percent or more on average.",
        "Recalculate any time you change foods, because density changes.",
      ]},
    ],
    related: [
      { label: 'How Much to Feed Your Dog', href: '/feeding/how-much-to-feed-a-dog' },
      { label: 'Wet vs Dry Food', href: '/compare/wet-vs-dry-food' },
      { label: 'Dietary Fat and Essential Fatty Acids', href: '/nutrition/dietary-fat-and-fatty-acids' },
    ],
    sources: [...STD, SRC.fdaPet],
  },

  {
    dir: D, slug: 'dry-matter-basis-explained', date: '2026-05-31',
    title: 'Dry-Matter Basis Explained',
    metaTitle: 'Dry-Matter Basis — Comparing Wet and Dry Pet Food | PetFood.com',
    metaDesc:
      'Why guaranteed-analysis percentages mislead across formats, how to convert as-fed to dry-matter, and worked examples comparing canned and kibble protein.',
    category: 'Nutrition Fundamentals', readTime: '9 min',
    hero:
      "The single most useful piece of pet food math is the dry-matter conversion. Without it, the guaranteed analysis makes a 78-percent-water canned food look like it has a quarter the protein of a kibble, when in fact they may be nearly identical. This page shows the conversion, works two examples, and explains when it matters.",
    toc: [
      { label: 'The As-Fed Problem', id: 'asfed' },
      { label: 'The Conversion', id: 'conversion' },
      { label: 'Worked Example — Protein', id: 'example' },
      { label: 'When It Matters', id: 'matters' },
      { label: 'Comparing Across Brands', id: 'brands' },
    ],
    body: [
      { p: "The guaranteed analysis on every pet food bag reports nutrients on an as-fed basis — that is, including the water in the food. Because canned food is mostly water and kibble is mostly dry, the as-fed percentages are not comparable between the two. Dry-matter basis removes water from both sides of the comparison so the nutrient content can be compared honestly. This is standard practice in animal nutrition and the only correct way to compare formats." },
      { h2: 'The As-Fed Problem', id: 'asfed' },
      { p: "A typical canned cat food might guarantee 10 percent crude protein. A typical dry cat food might guarantee 34 percent. At first glance the kibble has more than three times the protein. But the canned food is about 78 percent water, so only 22 percent of it is actual food; the dry food is about 10 percent moisture, so 90 percent of it is food. Comparing the two as-fed is comparing a number that includes a lot of water against one that includes very little." },
      { h2: 'The Conversion', id: 'conversion' },
      { p: "To convert any guaranteed-analysis percentage to a dry-matter basis, first find the dry-matter percentage: 100 minus the guaranteed moisture percentage. Then divide the nutrient percentage by the dry-matter percentage and multiply by 100. The formula is: dry-matter nutrient = (as-fed nutrient / (100 - moisture)) x 100. If moisture is not listed, the AAFCO default maximum is 78 percent for canned and 12 percent for dry, but use the actual guaranteed figure where available." },
      { h2: 'Worked Example — Protein', id: 'example' },
      { p: "Canned food: 10 percent crude protein, 78 percent moisture. Dry matter = 100 - 78 = 22 percent. Dry-matter protein = (10 / 22) x 100 = 45.5 percent. Dry food: 34 percent crude protein, 10 percent moisture. Dry matter = 90 percent. Dry-matter protein = (34 / 90) x 100 = 37.8 percent. On a dry-matter basis the canned food actually carries more protein than the kibble — the opposite of the as-fed impression. The same conversion applies to fat, fiber, and any other guaranteed nutrient." },
      { h2: 'When It Matters', id: 'matters' },
      { p: "Dry-matter conversion matters whenever you compare a wet food to a dry food, compare two foods of different moisture, or evaluate whether a diet meets a target nutrient level (AAFCO profiles are stated on a dry-matter basis). It matters less when comparing two dry foods of similar moisture, where the as-fed figures are close enough to rank directly. For carbohydrate, remember the figure is estimated by difference and is not on the label. See [[Carbohydrates in Pet Food|/nutrition/carbohydrates-in-pet-food]]." },
      { h2: 'Comparing Across Brands', id: 'brands' },
      { p: "When evaluating brands and formulas on this site, nutrient comparisons are normalized to a dry-matter basis precisely so that wet and dry products are judged on equal footing. The AAFCO nutrient profiles that define complete-and-balanced are themselves expressed on a dry-matter basis, which is another reason the conversion is foundational. See [[AAFCO Completeness Explained|/guides/aafco-completeness-explained]] and our [[Scoring Methodology|/guides/methodology]]." },
    ],
    related: [
      { label: 'Carbohydrates in Pet Food', href: '/nutrition/carbohydrates-in-pet-food' },
      { label: 'Reading a Pet Food Label', href: '/guides/reading-pet-food-labels' },
      { label: 'Wet vs Dry Food', href: '/compare/wet-vs-dry-food' },
    ],
    sources: [...STD],
  },

  {
    dir: D, slug: 'vitamins-in-pet-food', date: '2026-05-31',
    title: 'Vitamins in Pet Food',
    metaTitle: 'Vitamins in Pet Food — Fat- and Water-Soluble | PetFood.com',
    metaDesc:
      'The fat-soluble (A, D, E, K) and water-soluble (B-complex, C) vitamins in dog and cat diets, deficiency and toxicity signs, and why cats need pre-formed vitamin A.',
    category: 'Nutrition Fundamentals', readTime: '11 min',
    hero:
      "Vitamins are required in tiny quantities and supplied in a complete diet through ingredients plus a premix added at the mixer. They are also where some of the most important species differences live — cats cannot make vitamin A from beta-carotene, and both species are vulnerable to over-supplementation of the fat-soluble vitamins. This page covers each vitamin group, the AAFCO requirements, and the deficiency and toxicity picture.",
    toc: [
      { label: 'How Vitamins Are Supplied', id: 'supplied' },
      { label: 'Fat-Soluble — A, D, E, K', id: 'fatsoluble' },
      { label: 'Water-Soluble — B and C', id: 'watersoluble' },
      { label: 'Species Differences', id: 'species' },
      { label: 'Toxicity Risk', id: 'toxicity' },
      { label: 'Supplementing — When and When Not', id: 'supplement' },
    ],
    body: [
      { p: "Vitamins are organic micronutrients required for metabolism, growth, and maintenance. They divide into two groups by solubility: fat-soluble (A, D, E, K), which are stored in the body and can accumulate to toxic levels, and water-soluble (the B-complex and vitamin C), which are largely excreted in excess and must be supplied more regularly. A complete-and-balanced diet supplies all required vitamins; the AAFCO profiles set minima and, for the fat-soluble vitamins, maxima." },
      { h2: 'How Vitamins Are Supplied', id: 'supplied' },
      { p: "Raw ingredients contribute some vitamins, but processing — particularly the heat of extrusion and retort canning — degrades several of them. To guarantee the finished food meets profile, manufacturers add a vitamin premix at the mixing stage, formulated to account for processing losses and shelf-life decay. This is why the ingredient panel lists a string of vitamin names near the end. Their presence is normal and necessary, not a red flag." },
      { h2: 'Fat-Soluble Vitamins — A, D, E, K', id: 'fatsoluble' },
      { p: "Vitamin A supports vision, skin, and immune function; deficiency causes night blindness and skin disease, while excess causes skeletal abnormalities. Vitamin D regulates calcium and phosphorus; dogs and cats, unlike many species, cannot synthesize meaningful vitamin D in skin and depend entirely on dietary intake. Vitamin E is the principal lipid-phase antioxidant, protecting cell membranes and dietary fats from oxidation. Vitamin K supports blood clotting and is partly supplied by intestinal bacteria. Because these vitamins are stored, both deficiency and toxicity are clinically relevant." },
      { h2: 'Water-Soluble Vitamins — B and C', id: 'watersoluble' },
      { p: "The B-complex vitamins (thiamine B1, riboflavin B2, niacin B3, pantothenic acid B5, pyridoxine B6, biotin B7, folate B9, cobalamin B12) function as coenzymes across energy and protein metabolism. Thiamine deserves special mention: it is heat-labile and is destroyed by thiaminases present in some raw fish, and thiamine-deficiency cases have been linked to certain canned cat foods and to all-fish diets. Vitamin C is synthesized by both dogs and cats, so it is not a required dietary nutrient, though it is sometimes added as an antioxidant." },
      { h2: 'Species Differences', id: 'species' },
      { p: "The defining feline difference is vitamin A: cats cannot convert beta-carotene (the plant precursor) to retinol and therefore require pre-formed vitamin A from animal sources. They also require dietary niacin, because their conversion of tryptophan to niacin is inadequate. These requirements are met by animal tissue and by the vitamin premix; they are part of why a cat cannot thrive on a dog food or a plant-only diet. See [[Dog vs Cat Nutrition|/species/dog-vs-cat-nutrition-overview]]." },
      { h2: 'Toxicity Risk', id: 'toxicity' },
      { p: "Fat-soluble vitamins accumulate, so over-supplementation is a real hazard. Excess vitamin D is among the more dangerous, and several pet food recalls have been driven by formulation errors that produced toxic vitamin D concentrations. Excess vitamin A, classically from feeding large amounts of liver, causes painful skeletal lesions in cats. Because a complete diet already meets requirements, adding a multivitamin on top can push fat-soluble vitamins toward the toxic range without benefit." },
      { h2: 'Supplementing — When and When Not', id: 'supplement' },
      { p: "A healthy animal eating a complete-and-balanced diet does not need vitamin supplementation, and routine multivitamins carry a real over-supplementation risk for the fat-soluble vitamins. Supplementation has a defined place — under veterinary direction — for animals on home-prepared diets, with specific malabsorption conditions, or with documented deficiencies. Home-prepared diets in particular almost always require a balancing supplement to be complete. See [[Multivitamins for Pets|/supplements/multivitamins-for-pets]] and [[Home-Cooked Diets|/compare/home-cooked-vs-commercial]]." },
    ],
    related: [
      { label: 'Minerals in Pet Food', href: '/nutrition/minerals-in-pet-food' },
      { label: 'Multivitamins for Pets', href: '/supplements/multivitamins-for-pets' },
      { label: 'Dog vs Cat Nutrition', href: '/species/dog-vs-cat-nutrition-overview' },
    ],
    sources: [...STD, SRC.fdaPet],
  },

  {
    dir: D, slug: 'minerals-in-pet-food', date: '2026-06-01',
    title: 'Minerals in Pet Food',
    metaTitle: 'Minerals in Pet Food — Macro and Trace | PetFood.com',
    metaDesc:
      'Calcium, phosphorus, and the Ca:P ratio, the trace minerals (zinc, copper, iron, selenium), chelated vs inorganic forms, and large-breed-puppy calcium ceilings.',
    category: 'Nutrition Fundamentals', readTime: '11 min',
    hero:
      "Minerals are inorganic nutrients that must be supplied in correct amounts and correct ratios — get the calcium-to-phosphorus ratio wrong in a growing large-breed puppy and you risk lifelong skeletal disease. This page covers the macrominerals, the trace minerals, the chelated-vs-inorganic question, and the AAFCO maxima that exist specifically to prevent harm.",
    toc: [
      { label: 'Macro vs Trace', id: 'macrotrace' },
      { label: 'Calcium and Phosphorus', id: 'caphos' },
      { label: 'The Ca:P Ratio', id: 'ratio' },
      { label: 'Trace Minerals', id: 'trace' },
      { label: 'Chelated vs Inorganic', id: 'chelated' },
      { label: 'Large-Breed Puppy Ceilings', id: 'largebreed' },
    ],
    body: [
      { p: "Minerals are required in defined amounts, and several of them interact — an excess of one can induce deficiency of another. The AAFCO profiles set minima for the essential minerals and, importantly, maxima for several, because over-supply is as harmful as under-supply. A complete diet meets these targets through ingredients plus a mineral premix; the balance and ratio matter as much as the absolute amounts." },
      { h2: 'Macrominerals vs Trace Minerals', id: 'macrotrace' },
      { p: "Macrominerals (calcium, phosphorus, magnesium, sodium, potassium, chloride) are needed in gram quantities and form the structural and electrolyte backbone of the body. Trace minerals (zinc, copper, iron, manganese, selenium, iodine) are needed in milligram or microgram quantities and act largely as enzyme cofactors. Both groups are essential; the difference is quantity, not importance." },
      { h2: 'Calcium and Phosphorus', id: 'caphos' },
      { p: "Calcium and phosphorus together build bone and teeth and run countless cellular processes. Their dietary balance is one of the most carefully regulated aspects of pet nutrition. The AAFCO Dog Food Nutrient Profile sets calcium at a minimum of 0.5 percent dry-matter for adult maintenance (1.2 percent for growth) and phosphorus at a minimum of 0.4 percent (1.0 percent for growth), with maxima on both for growth diets. Excess phosphorus is a particular concern in chronic kidney disease, where phosphorus-restricted diets are a cornerstone of management. See [[Kidney Disease Diets|/diets/kidney-disease-diets]]." },
      { h2: 'The Calcium-to-Phosphorus Ratio', id: 'ratio' },
      { p: "Beyond absolute amounts, the calcium-to-phosphorus ratio matters. AAFCO targets a ratio between roughly 1:1 and 2:1 for dogs. A ratio skewed too far toward phosphorus — common in all-meat homemade diets, which are calcium-poor and phosphorus-rich — drives the body to pull calcium from bone, producing nutritional secondary hyperparathyroidism and pathological fractures. This is one of the classic harms of an unbalanced home-prepared diet. See [[Home-Cooked Diets|/compare/home-cooked-vs-commercial]]." },
      { h2: 'Trace Minerals', id: 'trace' },
      { p: "Zinc supports skin, coat, and immune function; deficiency produces a characteristic dermatosis, and certain northern-breed dogs have a genetic zinc-absorption defect. Copper and iron support blood and connective tissue, though excess copper is hepatotoxic and some breeds (notably Bedlington Terriers and Labrador Retrievers) are predisposed to copper-associated liver disease, prompting recent attention to dietary copper levels. Selenium and vitamin E work together as antioxidants. Iodine is required for thyroid hormone, and both deficiency and excess affect thyroid function — relevant in cats given the high rate of feline hyperthyroidism." },
      { h2: 'Chelated vs Inorganic Minerals', id: 'chelated' },
      { p: "Minerals are added either as inorganic salts (oxides, sulfates, carbonates) or as organic chelates and proteinates, in which the mineral is bound to an amino acid or peptide. Chelated forms are generally more bioavailable, which means a lower inclusion rate achieves the same absorbed amount and reduces the unabsorbed mineral load reaching the colon. Many premium diets use chelated trace minerals, often listed as a proteinate or amino-acid complex on the panel. The benefit is real but incremental; a diet using inorganic minerals at adequate levels is still complete." },
      { h2: 'Large-Breed Puppy Calcium Ceilings', id: 'largebreed' },
      { p: "Large- and giant-breed puppies are uniquely sensitive to excess calcium during growth, which is linked to developmental orthopedic diseases including osteochondrosis and hip dysplasia. For this reason AAFCO created a separate growth profile for large-size dogs (adult weight 70 pounds or more) with a tighter calcium maximum. An all-life-stages food not validated for large-size growth can legally exceed this ceiling, which is why owners of large-breed puppies must confirm the food is labeled for growth including large-size growth. See [[Large-Breed Puppy Nutrition|/feeding/large-breed-puppy-nutrition]] and [[AAFCO Completeness Explained|/guides/aafco-completeness-explained]]." },
    ],
    related: [
      { label: 'Vitamins in Pet Food', href: '/nutrition/vitamins-in-pet-food' },
      { label: 'Kidney Disease Diets', href: '/diets/kidney-disease-diets' },
      { label: 'Large-Breed Puppy Nutrition', href: '/feeding/large-breed-puppy-nutrition' },
    ],
    sources: [...STD],
  },

  {
    dir: D, slug: 'taurine-and-amino-acids', date: '2026-06-01',
    title: 'Taurine and Essential Amino Acids',
    metaTitle: 'Taurine and Essential Amino Acids in Pet Food | PetFood.com',
    metaDesc:
      'Why taurine is essential for cats, the amino-acid profile that defines protein quality, taurine and DCM in dogs, and the AAFCO amino-acid requirements.',
    category: 'Nutrition Fundamentals', readTime: '10 min',
    hero:
      "Amino acids are the reason crude protein on a label tells you so little. The body does not need protein per se; it needs the specific amino acids that protein delivers, in the right proportions. Taurine sits at the center of this story — essential for cats, implicated in canine heart disease, and a clean illustration of why protein source matters more than protein quantity.",
    toc: [
      { label: 'Amino Acids and Protein Quality', id: 'quality' },
      { label: 'Essential vs Non-Essential', id: 'essential' },
      { label: 'Taurine in Cats', id: 'cats' },
      { label: 'Taurine and Canine DCM', id: 'dcm' },
      { label: 'Other Key Amino Acids', id: 'others' },
      { label: 'AAFCO Requirements', id: 'aafco' },
    ],
    body: [
      { p: "Protein is a delivery vehicle for amino acids. The biological value of a protein source depends on whether it supplies all the essential amino acids in proportions matching the animal's needs. A protein missing or short in one essential amino acid limits the use of all the others — the limiting-amino-acid principle. This is why protein quality, not just quantity, determines how well a diet supports the animal." },
      { h2: 'Amino Acids and Protein Quality', id: 'quality' },
      { p: "Of the twenty-odd amino acids, a subset are essential — the animal cannot synthesize them quickly enough and must obtain them from diet. Animal proteins generally provide a complete, well-balanced essential amino-acid profile; many plant proteins are short in one or more (for example, methionine or lysine), which is why plant-heavy diets require complementary protein blending or synthetic amino-acid supplementation to be complete. Crude protein on the guaranteed analysis captures none of this. See [[Dietary Protein Requirements|/nutrition/dietary-protein-requirements]]." },
      { h2: 'Essential vs Non-Essential', id: 'essential' },
      { p: "Dogs require ten essential amino acids; cats require eleven, the additional one being taurine. Non-essential amino acids can be synthesized internally from other building blocks, so they need not be supplied directly. The line between essential and conditionally essential can shift with life stage and health status — arginine, for example, is critically essential in cats because a single arginine-deficient meal can precipitate dangerous hyperammonemia." },
      { h2: 'Taurine in Cats', id: 'cats' },
      { p: "Cats cannot synthesize adequate taurine because they have low activity of the enzymes that make it and because they obligately use taurine (not glycine) to conjugate bile acids, continuously depleting their supply. Dietary taurine deficiency in cats causes feline central retinal degeneration (leading to blindness), dilated cardiomyopathy, and reproductive failure. The discovery of taurine-deficiency DCM in cats in the late 1980s led to mandatory taurine supplementation of cat foods and is one of the great successes of veterinary nutrition. Taurine is found in animal tissue and is destroyed or lost by some processing, so it is supplemented to guarantee adequacy." },
      { h2: 'Taurine and Canine DCM', id: 'dcm' },
      { p: "Dogs synthesize taurine from cysteine and methionine and do not have a dietary taurine requirement under the AAFCO profile. However, certain breeds (Cocker Spaniels, Golden Retrievers, Newfoundlands, and others) appear prone to taurine-deficiency dilated cardiomyopathy, and taurine status became central to the FDA CVM investigation into diet-associated DCM in dogs eating grain-free, legume-heavy diets. The mechanism is not fully resolved — not all affected dogs are taurine-deficient — but taurine measurement and supplementation are part of the clinical work-up. See [[Grain-Free and DCM Risk|/ingredients/grain-free-dcm-risk]]." },
      { h2: 'Other Key Amino Acids', id: 'others' },
      { p: "Methionine and cysteine (the sulfur amino acids) support taurine synthesis in dogs, coat keratin, and urinary acidification. Lysine is often the first limiting amino acid in cereal-based diets. Arginine is critical for the urea cycle in both species and acutely critical in cats. Tryptophan is a precursor to serotonin and, in cats, to niacin. The interplay of these amino acids is why formulators evaluate the full amino-acid profile, not just total protein." },
      { h2: 'AAFCO Amino-Acid Requirements', id: 'aafco' },
      { p: "The AAFCO Dog and Cat Food Nutrient Profiles list minimum dry-matter requirements for each essential amino acid, with the cat profile including a taurine minimum (higher for canned than dry food, reflecting differing bioavailability and processing losses). Meeting the crude-protein minimum does not guarantee meeting every amino-acid minimum, which is why a complete diet is formulated to the amino-acid profile, not merely to a protein percentage. See [[AAFCO Completeness Explained|/guides/aafco-completeness-explained]]." },
    ],
    related: [
      { label: 'Dietary Protein Requirements', href: '/nutrition/dietary-protein-requirements' },
      { label: 'Grain-Free and DCM Risk', href: '/ingredients/grain-free-dcm-risk' },
      { label: 'Dog vs Cat Nutrition', href: '/species/dog-vs-cat-nutrition-overview' },
    ],
    sources: [...STD, SRC.fdaDcm],
  },

  {
    dir: D, slug: 'water-and-hydration', date: '2026-06-01',
    title: 'Water and Hydration in Pet Nutrition',
    metaTitle: 'Water and Hydration for Dogs and Cats | PetFood.com',
    metaDesc:
      'Why water is the most important nutrient, the feline thirst-drive problem, moisture content of wet vs dry diets, and hydration in urinary and kidney disease.',
    category: 'Nutrition Fundamentals', readTime: '9 min',
    hero:
      "Water is the nutrient most easily overlooked and the one an animal can least afford to lack. For cats in particular, the way a diet delivers water has clinical consequences — the feline weak thirst drive, evolved for a desert carnivore eating moist prey, interacts badly with dry food and contributes to urinary disease. This page covers hydration physiology, dietary moisture, and the conditions where it matters most.",
    toc: [
      { label: 'The Most Important Nutrient', id: 'important' },
      { label: 'The Feline Thirst Problem', id: 'feline' },
      { label: 'Dietary Moisture', id: 'moisture' },
      { label: 'Urinary Health', id: 'urinary' },
      { label: 'Kidney Disease', id: 'kidney' },
      { label: 'Practical Hydration', id: 'practical' },
    ],
    body: [
      { p: "Water makes up roughly 60 to 70 percent of an adult animal's body and is involved in every physiological process. An animal can lose nearly all its fat and half its protein and survive, but a loss of 10 to 15 percent of body water is life-threatening. Water is not on the AAFCO nutrient profile in the usual sense, but it is correctly described as the most important nutrient, and the way a diet supplies it has real clinical weight, especially for cats." },
      { h2: 'The Most Important Nutrient', id: 'important' },
      { p: "Water sources are drinking water, the moisture in food, and metabolic water produced by oxidizing nutrients. A healthy animal self-regulates total intake well when fresh water is freely available and when no medical condition impairs thirst or increases losses. Requirements rise with heat, exercise, lactation, and any disease causing increased urination, vomiting, or diarrhea." },
      { h2: 'The Feline Thirst Problem', id: 'feline' },
      { p: "Cats evolved from desert-dwelling ancestors that obtained most of their water from prey (which is roughly 70 percent water). As a result, cats have a comparatively weak thirst drive and do not voluntarily drink enough to fully compensate for a dry diet. A cat on dry food alone often runs at a lower total water intake and produces more concentrated urine than a cat eating canned food. This chronic mild under-hydration is one reason canned diets are frequently recommended for feline urinary and kidney patients." },
      { h2: 'Dietary Moisture', id: 'moisture' },
      { p: "Canned and pouch foods are roughly 75 to 82 percent water; fresh and gently cooked diets are similar; dry kibble is about 6 to 12 percent. A cat eating canned food can obtain the majority of its water from the diet, while a cat on dry food must make up the deficit by drinking. This is the practical core of the wet-versus-dry hydration argument. See [[Wet vs Dry Food|/compare/wet-vs-dry-food]]." },
      { h2: 'Urinary Health', id: 'urinary' },
      { p: "Dilute urine reduces the concentration of the minerals that form struvite and calcium-oxalate crystals and uroliths, and increased urine volume flushes the lower urinary tract. Increasing water intake — most reliably through a canned or moisture-rich diet — is a first-line strategy for cats with feline lower urinary tract disease and for stone-forming cats and dogs. Therapeutic urinary diets combine increased moisture with mineral and pH targets. See [[Urinary and Bladder Stone Diets|/diets/urinary-tract-diets]]." },
      { h2: 'Kidney Disease', id: 'kidney' },
      { p: "Animals with chronic kidney disease lose the ability to concentrate urine and are prone to dehydration. Maintaining hydration is central to management, and a moisture-rich diet helps. This is one reason renal therapeutic diets are commonly offered in canned form and why owners are encouraged to maximize water intake. See [[Kidney Disease Diets|/diets/kidney-disease-diets]]." },
      { h2: 'Practical Hydration Strategies', id: 'practical' },
      { ol: [
        "Provide multiple clean, fresh water sources away from food and litter; many cats prefer water at a distance from the bowl.",
        "Consider a pet water fountain — moving water increases voluntary intake in many cats.",
        "Add water or low-sodium broth to meals, or feed a canned or rehydrated diet, to raise dietary moisture.",
        "Watch for clinical signs of inadequate intake: tacky gums, reduced skin elasticity, lethargy, concentrated urine.",
        "For any animal with urinary or kidney disease, treat hydration as a managed part of the diet plan with your veterinarian.",
      ]},
    ],
    related: [
      { label: 'Wet vs Dry Food', href: '/compare/wet-vs-dry-food' },
      { label: 'Urinary and Bladder Stone Diets', href: '/diets/urinary-tract-diets' },
      { label: 'Kidney Disease Diets', href: '/diets/kidney-disease-diets' },
    ],
    sources: [...STD],
  },

  {
    dir: D, slug: 'guaranteed-analysis-explained', date: '2026-06-01',
    title: 'The Guaranteed Analysis Explained',
    metaTitle: 'Guaranteed Analysis on Pet Food Labels Explained | PetFood.com',
    metaDesc:
      'What the guaranteed analysis discloses, the minimum-maximum framing, why it is not a typical analysis, and how to use it without being misled.',
    category: 'Nutrition Fundamentals', readTime: '9 min',
    hero:
      "The guaranteed analysis is the small box of percentages on every pet food bag, and it is one of the most frequently misread label elements. It is a regulatory guarantee of minima and maxima, not a statement of what the food actually contains. This page explains what it discloses, what it hides, and how to extract real information from it.",
    toc: [
      { label: 'What It Is', id: 'whatis' },
      { label: 'Minimums and Maximums', id: 'minmax' },
      { label: 'The Required Four', id: 'requiredfour' },
      { label: 'Guaranteed vs Typical Analysis', id: 'typical' },
      { label: 'Voluntary Guarantees', id: 'voluntary' },
      { label: 'Using It Well', id: 'using' },
    ],
    body: [
      { p: "The guaranteed analysis is required on every pet food label under AAFCO model regulations. It states the manufacturer's guarantee for certain nutrients, expressed as minimum or maximum percentages on an as-fed basis. The word guarantee is the key: the food will contain at least the stated minimum of protein and fat, and no more than the stated maximum of fiber and moisture. The actual content is usually somewhat different from the guarantee." },
      { h2: 'What It Is', id: 'whatis' },
      { p: "The guaranteed analysis exists for regulatory enforcement. A state feed-control official can pull a sample and test whether the food meets its own guarantees; a food that falls below its guaranteed protein minimum or above its guaranteed fiber maximum is misbranded. The guarantee is therefore a floor-and-ceiling commitment, not a description of the average batch." },
      { h2: 'Minimums and Maximums', id: 'minmax' },
      { p: "Crude protein and crude fat are guaranteed as minima — the food contains at least that much. Crude fiber and moisture are guaranteed as maxima — the food contains no more than that. This framing means the real protein is usually a bit above the stated minimum and the real moisture usually a bit below the stated maximum. It also means two foods with the same guaranteed protein minimum can differ in actual protein, and that the guaranteed analysis is a coarse instrument for comparison." },
      { h2: 'The Required Four', id: 'requiredfour' },
      { p: "Four guarantees are mandatory on every label: crude protein minimum, crude fat minimum, crude fiber maximum, and moisture maximum. The word crude refers to the analytical method (it estimates the nutrient rather than measuring it precisely), not to ingredient quality. Crude protein, as noted elsewhere, is nitrogen times 6.25 and says nothing about amino-acid quality. See [[Dietary Protein Requirements|/nutrition/dietary-protein-requirements]]." },
      { h2: 'Guaranteed vs Typical Analysis', id: 'typical' },
      { p: "The guaranteed analysis is not the typical analysis. The typical (or average) analysis is the manufacturer's measured average nutrient content across production, and it is the figure you actually want for comparison and for dry-matter math. Manufacturers will usually provide the typical analysis on request, often including amino acids, the full mineral panel, and a measured metabolizable-energy value. For careful comparison, request the typical analysis rather than relying on the guarantee. See [[Dry-Matter Basis Explained|/nutrition/dry-matter-basis-explained]]." },
      { h2: 'Voluntary Guarantees', id: 'voluntary' },
      { p: "Beyond the required four, manufacturers may add voluntary guarantees — taurine, omega-3 and omega-6 fatty acids, glucosamine, calcium, phosphorus, and others. Any voluntary guarantee, once printed, becomes enforceable. Voluntary guarantees are useful when they disclose a nutrient relevant to a buying decision (for example, taurine in a cat food, or EPA/DHA in a joint diet), but their absence does not mean the nutrient is absent — only that it is not guaranteed." },
      { h2: 'Using the Guaranteed Analysis Well', id: 'using' },
      { ol: [
        "Read protein and fat as floors, fiber and moisture as ceilings — not as the actual content.",
        "Convert to a dry-matter basis before comparing wet and dry, or before checking against an AAFCO profile.",
        "Do not rank protein quality by the guaranteed minimum; use the ingredient panel for that.",
        "Request the typical analysis from the manufacturer when you need accurate numbers.",
        "Treat voluntary guarantees (taurine, omega-3) as a transparency signal, not a completeness check.",
      ]},
    ],
    related: [
      { label: 'Reading a Pet Food Label', href: '/guides/reading-pet-food-labels' },
      { label: 'Dry-Matter Basis Explained', href: '/nutrition/dry-matter-basis-explained' },
      { label: 'Dietary Protein Requirements', href: '/nutrition/dietary-protein-requirements' },
    ],
    sources: [...STD, SRC.fdaPet],
  },

  {
    dir: D, slug: 'antioxidants-and-functional-nutrients', date: '2026-06-01',
    title: 'Antioxidants and Functional Nutrients',
    metaTitle: 'Antioxidants and Functional Nutrients in Pet Food | PetFood.com',
    metaDesc:
      'What antioxidants, postbiotics, and functional nutrients do in pet diets, the evidence for vitamin E, selenium, and carotenoids, and how to read functional claims.',
    category: 'Nutrition Fundamentals', readTime: '9 min',
    hero:
      "Beyond the essential nutrients, pet diets increasingly market functional ingredients — antioxidants, nutraceuticals, and additives claimed to support immunity, cognition, or aging. Some have genuine evidence; many are marketing. This page covers the antioxidants with real roles and how to judge functional claims against the evidence.",
    toc: [
      { label: 'What Antioxidants Do', id: 'antioxidants' },
      { label: 'Vitamin E and Selenium', id: 'vitamineselenium' },
      { label: 'Carotenoids and Polyphenols', id: 'carotenoids' },
      { label: 'Functional Claims', id: 'functional' },
      { label: 'Cognitive Support', id: 'cognitive' },
      { label: 'Judging the Evidence', id: 'judging' },
    ],
    body: [
      { p: "Oxidative stress — damage from reactive oxygen species — contributes to aging and disease, and antioxidants are nutrients and compounds that neutralize it. Several antioxidants are essential nutrients with established roles in pet diets, while a growing class of functional ingredients makes broader claims with variable evidence. Separating the established from the speculative is the goal here. See [[Vitamins in Pet Food|/nutrition/vitamins-in-pet-food]]." },
      { h2: 'What Antioxidants Do', id: 'antioxidants' },
      { p: "Antioxidants protect cells and dietary fats from oxidative damage, and the body uses a network of them — some made internally, some dietary. In pet food they serve two purposes: protecting the food itself from rancidity (as preservatives) and supporting the animal's own antioxidant defenses. The most important dietary antioxidants are vitamin E, selenium, vitamin C, and a range of plant compounds. See [[Preservatives in Pet Food|/ingredients/preservatives-pet-food]]." },
      { h2: 'Vitamin E and Selenium', id: 'vitamineselenium' },
      { p: "Vitamin E is the principal lipid-phase antioxidant and an essential nutrient with an AAFCO minimum; it protects cell membranes and dietary fats, and works synergistically with selenium, a trace mineral cofactor for antioxidant enzymes. Both are established essential nutrients, not optional add-ons, and a complete diet supplies them. Their antioxidant role is well-founded, unlike many marketed functional claims. See [[Minerals in Pet Food|/nutrition/minerals-in-pet-food]]." },
      { h2: 'Carotenoids and Polyphenols', id: 'carotenoids' },
      { p: "Plant-derived antioxidants — carotenoids (beta-carotene, lutein), polyphenols, and flavonoids from fruits and vegetables — are added to many diets for antioxidant support. They have plausible benefits and some supporting research, though the evidence for specific health outcomes in dogs and cats is generally less robust than for the essential antioxidants. Note that cats cannot convert beta-carotene to vitamin A. These are reasonable inclusions but not proven cures. See [[Dog vs Cat Nutrition|/species/dog-vs-cat-nutrition-overview]]." },
      { h2: 'Functional Claims', id: 'functional' },
      { p: "Functional or nutraceutical claims — immune support, joint support, calming, skin and coat, cognitive — vary enormously in evidence. Some, like marine omega-3s for joints and skin, are well-supported; others rest on preliminary or marketing-driven evidence. The presence of a functional ingredient on the label does not guarantee an effective dose or a proven benefit. Evaluate the specific active ingredient and dose. See [[Glucosamine and Joint Supplements|/supplements/glucosamine-and-joint-support]]." },
      { h2: 'Cognitive Support', id: 'cognitive' },
      { p: "Diets for canine cognitive dysfunction (an age-related decline resembling dementia) have some of the better functional-nutrient evidence: antioxidant-enriched diets and those with medium-chain triglycerides (an alternative brain energy source) have shown benefit in studies for older dogs. This is a case where a functional dietary approach is supported for a defined condition, used under veterinary guidance. See [[Senior Pet Diets|/diets/senior-pet-diets]]." },
      { h2: 'Judging the Evidence', id: 'judging' },
      { p: "To judge functional claims: prefer ingredients with published, ideally independent, evidence in dogs or cats for the specific claim (omega-3s, certain cognitive diets); be skeptical of proprietary blends that obscure the dose; recognize that a complete diet already supplies the essential antioxidants; and discuss functional-diet choices for a medical condition with the veterinarian. Established essential nutrients are the foundation; functional add-ons are evaluated case by case. See [[Multivitamins for Pets|/supplements/multivitamins-for-pets]]." },
    ],
    related: [
      { label: 'Vitamins in Pet Food', href: '/nutrition/vitamins-in-pet-food' },
      { label: 'Senior Pet Diets', href: '/diets/senior-pet-diets' },
      { label: 'Glucosamine and Joint Supplements', href: '/supplements/glucosamine-and-joint-support' },
    ],
    sources: [...STD],
  },
]

export const NUTRITION = RAW.map((p) => ({ ...p, hubName: 'Nutrition' }))
