/**
 * Dog.com — Breed-specific health deep-dive data.
 *
 * Source-of-truth for /breeds/[slug]/health pages. Records are cited from:
 *   - OFA (Orthopedic Foundation for Animals) — ofa.org statistics & CHIC panels
 *   - CHIC (Canine Health Information Center) — breed-specific recommended panels
 *   - AVMA breed health surveys
 *   - Breed-club (AKC parent-club) Health Committee statements
 *   - Peer-reviewed veterinary literature where called out by citedRef
 *
 * RULES (QC §1):
 *   - Frequency is "common" | "occasional" | "rare" — NEVER fabricated %.
 *   - No DVM byline. Author is "Dog.com Editorial — sourced from cited references".
 *   - No specific dosing or guaranteed outcomes anywhere.
 *   - Every health issue MUST have a real source listed in Sources (Sources are
 *     rendered from a per-breed sourceCitations array at the template level).
 *
 * Cross-link to /reviews/best-pet-insurance is generated by the template, not here.
 */

export type IssueFrequency = 'common' | 'occasional' | 'rare'

export interface HealthIssue {
  /** Human-readable condition name */
  name: string
  /** Population-level frequency in this breed — qualitative bucket only */
  frequency: IssueFrequency
  /** 2–4 sentences describing the condition and its breed-specific relevance */
  summary: string
  /** When owners typically first see it (e.g., "Puppyhood (4–12 months)") */
  ageOfOnset: string
  /** Name of the diagnostic/screening test, if applicable */
  screeningTest?: string
  /** Inline citation tag — matches an entry in the per-breed sourceCitations list */
  citedRef?: string
}

export interface ScreeningRecommendation {
  /** Test or exam name */
  name: string
  /** Age at which the screening should begin */
  ageRecommended: string
  /** How often to repeat */
  frequency: string
}

export interface FAQ {
  question: string
  answer: string
}

export interface SourceCitation {
  /** Short tag used by HealthIssue.citedRef */
  ref: string
  /** Long-form citation text */
  label: string
  /** Optional URL */
  url?: string
}

export interface BreedHealthRecord {
  slug: string
  breedName: string
  /** Display like "10–12 years" */
  lifespanRange: string
  /** Editorial 2–3 sentence overview of the breed's overall health profile */
  overview: string
  knownHealthIssues: HealthIssue[]
  recommendedScreenings: ScreeningRecommendation[]
  /** Vaccines or vaccine considerations specific to this breed (or undefined) */
  breedSpecificVaccinations?: string[]
  /** Signs that warrant an emergency vet visit */
  emergencySigns: string[]
  /** Owner-actionable preventive care tips */
  preventiveCareTips: string[]
  /** Editorial paragraph on lifetime insurance cost reality */
  typicalInsuranceCostImplications: string
  faqs: FAQ[]
  /** Full citation list — rendered as a Sources section at end of page */
  sourceCitations: SourceCitation[]
}

// ─────────────────────────────────────────────────────────────────────────────
// LABRADOR RETRIEVER
// ─────────────────────────────────────────────────────────────────────────────
const labradorRetriever: BreedHealthRecord = {
  slug: 'labrador-retriever',
  breedName: 'Labrador Retriever',
  lifespanRange: '10–12 years',
  overview:
    'Labradors are a large sporting breed with well-documented predispositions to ' +
    'joint disease (hip and elbow dysplasia), exercise-induced collapse, and obesity ' +
    'linked in part to a documented POMC gene variant. The Labrador Retriever Club ' +
    'CHIC panel reflects these priorities and offers a meaningful baseline when ' +
    'evaluating a breeder.',
  knownHealthIssues: [
    {
      name: 'Hip dysplasia',
      frequency: 'common',
      summary:
        'Abnormal hip-socket development leading to laxity, secondary arthritis, and ' +
        'mobility loss. Labradors rank among the most-affected large breeds in OFA ' +
        'submissions, and the AKC parent-club Health Committee lists hip evaluation ' +
        'as a required CHIC test.',
      ageOfOnset: 'Signs typically appear from 6 months to early adulthood; arthritis often progresses with age',
      screeningTest: 'OFA hip evaluation or PennHIP',
      citedRef: 'ofa-stats',
    },
    {
      name: 'Elbow dysplasia',
      frequency: 'common',
      summary:
        'Umbrella term for fragmented coronoid process, ununited anconeal process, ' +
        'and osteochondrosis of the elbow. Labradors are among the most-affected ' +
        'breeds in OFA elbow data — an OFA elbow clearance on both parents is part ' +
        'of the breed CHIC panel.',
      ageOfOnset: 'Lameness often appears 4–10 months of age',
      screeningTest: 'OFA elbow evaluation',
      citedRef: 'ofa-stats',
    },
    {
      name: 'Exercise-Induced Collapse (EIC)',
      frequency: 'occasional',
      summary:
        'Inherited (DNM1) genetic mutation causing weakness and collapse after ' +
        'intense exercise. A DNA test is available and is part of the LRC CHIC ' +
        'panel; carriers can be bred responsibly when paired with clear partners.',
      ageOfOnset: 'Typically observed between 5 months and 3 years',
      screeningTest: 'DNA test for DNM1 mutation',
      citedRef: 'chic-lab',
    },
    {
      name: 'Progressive Retinal Atrophy (prcd-PRA)',
      frequency: 'occasional',
      summary:
        'Inherited retinal degeneration leading to progressive vision loss and ' +
        'eventual blindness. CHIC-recommended DNA test (prcd) plus annual eye exam ' +
        'allows responsible breeding decisions and early owner awareness.',
      ageOfOnset: 'Adult onset (3–8 years for most affected dogs)',
      screeningTest: 'OFA Eye Certification (CAER) + prcd-PRA DNA test',
      citedRef: 'chic-lab',
    },
    {
      name: 'Obesity (POMC-linked food drive)',
      frequency: 'common',
      summary:
        'A documented POMC gene variant is associated with stronger food motivation ' +
        'and higher obesity risk in Labradors. Obesity worsens joint disease, ' +
        'shortens lifespan, and is the single most modifiable health risk for the breed.',
      ageOfOnset: 'Any age; weight gain often accelerates after neutering and middle age',
      citedRef: 'pomc-study',
    },
    {
      name: 'Laryngeal paralysis',
      frequency: 'occasional',
      summary:
        'Older-adult Labradors are commonly affected by laryngeal paralysis, often ' +
        'as part of a broader polyneuropathy. Hallmark signs include loud panting, ' +
        'voice change, and heat or exercise intolerance.',
      ageOfOnset: 'Senior years (typically 9+)',
    },
  ],
  recommendedScreenings: [
    { name: 'OFA hip & elbow radiographs (offspring of tested parents)', ageRecommended: 'After 24 months for final certification', frequency: 'Once' },
    { name: 'Annual eye exam (CAER)', ageRecommended: 'From 12 months', frequency: 'Annually' },
    { name: 'Body condition scoring at every vet visit', ageRecommended: 'Lifelong', frequency: 'Every visit' },
    { name: 'Senior wellness bloodwork & thyroid panel', ageRecommended: 'From 7 years', frequency: 'Annually' },
  ],
  breedSpecificVaccinations: [
    'No Labrador-specific vaccine schedule; follow AAHA canine vaccination guidelines for core vaccines',
    'Consider leptospirosis given the breed\'s strong affinity for water and outdoor exposure',
  ],
  emergencySigns: [
    'Sudden hindlimb weakness, dragging, or collapse',
    'Acute lameness after exercise with rapid swelling',
    'Loud, raspy breathing or cyanotic (blue/purple) gums',
    'Bloated abdomen with unproductive retching',
    'Repeated vomiting or known foreign-body ingestion (the breed is notorious for indiscriminate eating)',
  ],
  preventiveCareTips: [
    'Keep lean — body condition score 4–5 of 9. Weigh food, do not free-feed.',
    'Swim instead of running on hard surfaces to protect joints.',
    'Limit forced exercise during growth (under 12–18 months) to protect growth plates.',
    'Brush teeth daily — dental disease compounds with age in Labradors.',
    'Use a slow-feeder bowl to reduce the bloat-risk profile of fast eating.',
    'Lock up trash, medications, and chocolate — counter-surfing and indiscriminate ingestion are characteristic.',
  ],
  typicalInsuranceCostImplications:
    'Owners commonly cite orthopedic costs as the dominant long-term medical line ' +
    'item: hip or elbow surgery, lifelong arthritis management, NSAIDs and joint ' +
    'injections, and rehabilitation. Pet insurance enrolled before any joint or eye ' +
    'diagnosis (typically before 12–18 months of age) is the simplest way to avoid ' +
    'breed-specific pre-existing-condition exclusions.',
  faqs: [
    {
      question: 'How common is hip dysplasia in Labradors?',
      answer:
        'OFA places Labradors among the most-evaluated and most-affected large breeds for hip dysplasia. ' +
        'The exact prevalence varies by population, but it is common enough that the Labrador Retriever Club ' +
        'requires an OFA or PennHIP evaluation as part of the CHIC panel for breeding dogs.',
    },
    {
      question: 'Is pet insurance worth it for a Labrador?',
      answer:
        'For most Labrador owners the answer is yes, because the dominant lifetime costs (joint surgery, ' +
        'arthritis management, gastrointestinal foreign-body episodes) are exactly the kinds of expensive, ' +
        'unpredictable claims insurance is designed for. Enroll before any joint or eye finding to keep ' +
        'orthopedic and ophthalmic coverage in scope.',
    },
    {
      question: 'What is the POMC gene and why does it matter?',
      answer:
        'A 2016 study in Cell Metabolism identified a POMC deletion in Labradors and Flat-Coated Retrievers ' +
        'associated with stronger food-seeking behavior and higher body weight. It is not the only cause of ' +
        'obesity, but it explains why measured meals, treat budgeting, and no free-feeding matter so much for ' +
        'this breed in particular.',
    },
  ],
  sourceCitations: [
    { ref: 'ofa-stats', label: 'Orthopedic Foundation for Animals — Hip and Elbow Statistics by Breed', url: 'https://ofa.org/diseases/breed-statistics/' },
    { ref: 'chic-lab', label: 'OFA CHIC — Labrador Retriever Club Required Panel', url: 'https://ofa.org/chic-programs/' },
    { ref: 'pomc-study', label: 'Raffan E. et al., "A Deletion in the Canine POMC Gene Is Associated With Weight and Appetite in Obesity-Prone Labrador Retriever Dogs," Cell Metabolism (2016)', url: 'https://www.cell.com/cell-metabolism/fulltext/S1550-4131(16)30163-2' },
    { ref: 'akc-lab', label: 'American Kennel Club — Labrador Retriever Breed Standard', url: 'https://www.akc.org/dog-breeds/labrador-retriever/' },
  ],
}

// ─────────────────────────────────────────────────────────────────────────────
// GOLDEN RETRIEVER
// ─────────────────────────────────────────────────────────────────────────────
const goldenRetriever: BreedHealthRecord = {
  slug: 'golden-retriever',
  breedName: 'Golden Retriever',
  lifespanRange: '10–12 years',
  overview:
    'Golden Retrievers carry meaningful cancer risk (hemangiosarcoma, lymphoma, mast ' +
    'cell tumors) and orthopedic predispositions. The Morris Animal Foundation Golden ' +
    'Retriever Lifetime Study and the Golden Retriever Club of America CHIC panel ' +
    'frame the breed\'s screening priorities.',
  knownHealthIssues: [
    {
      name: 'Cancer (hemangiosarcoma, lymphoma, mast cell tumor)',
      frequency: 'common',
      summary:
        'Golden Retrievers experience higher lifetime cancer rates than most breeds. ' +
        'Hemangiosarcoma (a malignancy of blood-vessel lining) and lymphoma are ' +
        'particularly emphasized by the GRCA Health Committee. The Morris Animal ' +
        'Foundation Golden Retriever Lifetime Study is following thousands of Goldens ' +
        'to better characterize incidence and risk factors.',
      ageOfOnset: 'Most diagnoses in middle to senior years (6+)',
      citedRef: 'mafl-golden',
    },
    {
      name: 'Hip dysplasia',
      frequency: 'common',
      summary:
        'A required CHIC test for the breed. Goldens consistently rank among the ' +
        'most-evaluated breeds in OFA hip data. Lean weight, joint-friendly exercise, ' +
        'and OFA-cleared parents are the standard prevention stack.',
      ageOfOnset: 'Lameness can begin from 6 months onward',
      screeningTest: 'OFA hip evaluation or PennHIP',
      citedRef: 'chic-golden',
    },
    {
      name: 'Elbow dysplasia',
      frequency: 'common',
      summary:
        'Also part of the GRCA CHIC panel. Forelimb lameness in a young Golden is a ' +
        'standard reason to image elbows in addition to hips.',
      ageOfOnset: '4–12 months for most clinical cases',
      screeningTest: 'OFA elbow evaluation',
      citedRef: 'chic-golden',
    },
    {
      name: 'Subaortic stenosis (SAS)',
      frequency: 'occasional',
      summary:
        'A congenital narrowing below the aortic valve that can be detected on ' +
        'cardiac auscultation and confirmed by echocardiogram. CHIC requires a ' +
        'cardiac evaluation by a board-certified cardiologist for breeding dogs.',
      ageOfOnset: 'Detectable from puppyhood with cardiac exam',
      screeningTest: 'Cardiologist exam + echocardiogram (OFA cardiac)',
      citedRef: 'chic-golden',
    },
    {
      name: 'Inherited eye disease (pigmentary uveitis, cataracts, PRA)',
      frequency: 'occasional',
      summary:
        'Golden Retriever pigmentary uveitis (GRPU) is a breed-characteristic ' +
        'condition with progressive vision risk; annual ophthalmologist exam is ' +
        'CHIC-recommended.',
      ageOfOnset: 'Adult onset; GRPU often diagnosed in middle age',
      screeningTest: 'Annual OFA Eye Certification (CAER)',
      citedRef: 'chic-golden',
    },
    {
      name: 'Hypothyroidism',
      frequency: 'occasional',
      summary:
        'Adult-onset thyroid disease occurs more often in Goldens than the canine ' +
        'average. Signs include weight gain despite normal intake, dull coat, lethargy, ' +
        'and heat-seeking behavior.',
      ageOfOnset: 'Middle age (4+ years)',
      screeningTest: 'Thyroid panel (T4, free T4, TSH)',
    },
  ],
  recommendedScreenings: [
    { name: 'OFA hip & elbow radiographs', ageRecommended: 'After 24 months', frequency: 'Once' },
    { name: 'Cardiologist exam (auscultation, +/- echo)', ageRecommended: 'From 12 months', frequency: 'Once for clearance; repeat on clinical signs' },
    { name: 'Annual ophthalmologist exam (CAER)', ageRecommended: 'From 12 months', frequency: 'Annually' },
    { name: 'Senior bloodwork incl. thyroid panel', ageRecommended: 'From 7 years', frequency: 'Annually' },
    { name: 'Body-cavity ultrasound for senior screening (heart, spleen)', ageRecommended: 'From 8 years', frequency: 'Discuss with vet' },
  ],
  breedSpecificVaccinations: [
    'No Golden-specific vaccine schedule; follow AAHA canine vaccination guidelines for core vaccines',
    'Discuss leptospirosis with your vet given the breed\'s outdoor and water exposure',
  ],
  emergencySigns: [
    'Sudden collapse, pale gums, or distended abdomen (possible hemangiosarcoma bleed)',
    'New limp that does not improve with rest',
    'Eye redness with squinting, cloudiness, or vision change',
    'Persistent or rapidly enlarging skin lump',
    'Repeated vomiting, melena (black/tarry stool), or sudden weakness',
  ],
  preventiveCareTips: [
    'Maintain lean body condition — overweight Goldens see joint and metabolic issues earlier.',
    'Annual eye exam by a veterinary ophthalmologist starting at 12 months.',
    'Palpate the dog weekly during grooming — early lump detection matters.',
    'Discuss cancer screening (bloodwork, abdominal ultrasound) with your vet from middle age.',
    'Brush coat 2–3 times per week to reduce ear infections and skin issues from trapped moisture.',
  ],
  typicalInsuranceCostImplications:
    'Cancer care is the dominant long-term cost line for many Golden owners — ' +
    'staging, surgery, chemotherapy, and palliative care. Hip and elbow surgery and ' +
    'cardiology workups stack on top. Pet insurance enrolled before any cancer, ' +
    'cardiac, or orthopedic finding keeps the largest claim categories in scope.',
  faqs: [
    {
      question: 'Why do Golden Retrievers get so much cancer?',
      answer:
        'A combination of genetic predisposition and a relatively small founding gene pool concentrated cancer risk in the breed. ' +
        'The Morris Animal Foundation Golden Retriever Lifetime Study is following thousands of dogs to better understand ' +
        'genetic, environmental, and dietary contributors. Owners cannot fully prevent it, but lean body condition, ' +
        'avoidance of secondhand smoke, and prompt evaluation of lumps and unexplained signs are reasonable steps.',
    },
    {
      question: 'How often should a Golden Retriever see a cardiologist?',
      answer:
        'GRCA CHIC requires a cardiac evaluation (by a board-certified veterinary cardiologist where possible) for breeding dogs. ' +
        'For pet owners, an auscultation at every annual exam and a referral if a murmur is heard is the practical baseline. ' +
        'Discuss with your veterinarian based on family history.',
    },
    {
      question: 'Is pet insurance worth it for a Golden Retriever?',
      answer:
        'For most Golden owners, yes — cancer treatment, orthopedic surgery, and ophthalmologic care are the kinds of ' +
        'large, unpredictable bills insurance is designed for. Enroll before any cancer, cardiac, or joint finding.',
    },
  ],
  sourceCitations: [
    { ref: 'mafl-golden', label: 'Morris Animal Foundation — Golden Retriever Lifetime Study', url: 'https://www.morrisanimalfoundation.org/golden-retriever-lifetime-study' },
    { ref: 'chic-golden', label: 'OFA CHIC — Golden Retriever Club of America Required Panel', url: 'https://ofa.org/chic-programs/' },
    { ref: 'grca-health', label: 'Golden Retriever Club of America — Health Committee', url: 'https://www.grca.org/health/' },
    { ref: 'akc-golden', label: 'American Kennel Club — Golden Retriever Breed Standard', url: 'https://www.akc.org/dog-breeds/golden-retriever/' },
  ],
}

// ─────────────────────────────────────────────────────────────────────────────
// GERMAN SHEPHERD
// ─────────────────────────────────────────────────────────────────────────────
const germanShepherd: BreedHealthRecord = {
  slug: 'german-shepherd',
  breedName: 'German Shepherd',
  lifespanRange: '9–13 years',
  overview:
    'German Shepherds carry meaningful risk for hip and elbow dysplasia, ' +
    'degenerative myelopathy, bloat (GDV), and exocrine pancreatic insufficiency. ' +
    'The German Shepherd Dog Club of America CHIC panel is the appropriate ' +
    'screening baseline.',
  knownHealthIssues: [
    {
      name: 'Hip dysplasia',
      frequency: 'common',
      summary:
        'German Shepherds are one of the historically most-affected breeds for hip ' +
        'dysplasia in OFA submissions, with steady screening pressure improving ' +
        'pedigrees. The GSDCA-recommended CHIC panel requires an OFA or PennHIP ' +
        'evaluation.',
      ageOfOnset: 'Lameness can start in late puppyhood; arthritis advances with age',
      screeningTest: 'OFA hip evaluation or PennHIP',
      citedRef: 'ofa-stats',
    },
    {
      name: 'Elbow dysplasia',
      frequency: 'common',
      summary:
        'Forelimb developmental disease is also common in the breed. OFA elbow ' +
        'evaluation is part of the GSDCA CHIC panel.',
      ageOfOnset: '4–12 months for most clinical cases',
      screeningTest: 'OFA elbow evaluation',
      citedRef: 'ofa-stats',
    },
    {
      name: 'Degenerative myelopathy (DM)',
      frequency: 'occasional',
      summary:
        'Adult-onset progressive spinal-cord disease. A SOD1 DNA test identifies ' +
        'genetic risk; not every at-risk dog clinically progresses, but the test ' +
        'is a CHIC-recommended option for the breed.',
      ageOfOnset: 'Typically 8+ years',
      screeningTest: 'SOD1 DNA test',
      citedRef: 'chic-gsd',
    },
    {
      name: 'Gastric Dilatation–Volvulus (GDV / bloat)',
      frequency: 'occasional',
      summary:
        'Deep-chested breeds, including German Shepherds, carry elevated GDV risk. ' +
        'Owners should learn the warning signs and discuss prophylactic gastropexy ' +
        '(often at the time of spay/neuter) with their veterinarian.',
      ageOfOnset: 'Adulthood; risk increases with age',
    },
    {
      name: 'Exocrine pancreatic insufficiency (EPI)',
      frequency: 'occasional',
      summary:
        'German Shepherds are over-represented in EPI populations. Hallmark signs ' +
        'are weight loss despite a strong appetite, voluminous pale stool, and ' +
        'flatulence. Diagnosed by serum TLI test; managed lifelong with enzyme ' +
        'supplementation.',
      ageOfOnset: 'Young adulthood is typical (1–4 years)',
      screeningTest: 'Trypsin-like immunoreactivity (TLI) blood test',
    },
    {
      name: 'Allergic skin disease and recurrent pyoderma',
      frequency: 'common',
      summary:
        'Atopic dermatitis, food sensitivity, and secondary bacterial skin ' +
        'infections are commonly reported in the breed. Long-term management ' +
        'with a dermatology-informed plan is often required.',
      ageOfOnset: 'Often begins 6 months to 3 years',
    },
  ],
  recommendedScreenings: [
    { name: 'OFA hip & elbow radiographs', ageRecommended: 'After 24 months', frequency: 'Once' },
    { name: 'SOD1 DNA test (degenerative myelopathy)', ageRecommended: 'Any age', frequency: 'Once' },
    { name: 'GDV (bloat) counseling & gastropexy discussion', ageRecommended: 'Before adulthood', frequency: 'Once' },
    { name: 'Annual derm exam if recurrent skin or ear infections', ageRecommended: 'As needed', frequency: 'Annually if affected' },
    { name: 'Senior bloodwork and urinalysis', ageRecommended: 'From 7 years', frequency: 'Annually' },
  ],
  breedSpecificVaccinations: [
    'No GSD-specific schedule; follow AAHA canine vaccination guidelines for core vaccines',
    'Discuss leptospirosis where regional exposure warrants it',
  ],
  emergencySigns: [
    'Distended, drum-like abdomen with unproductive retching (suspected GDV — go now)',
    'Sudden hindlimb weakness or knuckling that does not resolve',
    'Acute collapse or pale gums',
    'Repeated vomiting and weakness in a young dog (consider EPI complications)',
    'Severe self-trauma from skin disease with open lesions',
  ],
  preventiveCareTips: [
    'Discuss prophylactic gastropexy with your vet — feed measured meals from a slow-feeder bowl and avoid heavy exercise around mealtimes.',
    'Use OFA-evaluated parents and keep growing dogs lean to limit hip/elbow arthritis trajectory.',
    'Treat skin infections early and aggressively to prevent chronic resistance.',
    'Track stool quality monthly; investigate weight loss with strong appetite (EPI) promptly.',
    'Provide daily mental work — a bored Shepherd self-injures and chews destructively.',
  ],
  typicalInsuranceCostImplications:
    'Lifetime costs cluster around orthopedic surgery, chronic skin and ear disease, ' +
    'EPI management, and emergency GDV care. Pet insurance enrolled in puppyhood ' +
    'keeps each of these categories in scope before any pre-existing diagnosis.',
  faqs: [
    {
      question: 'Should I get a prophylactic gastropexy for my German Shepherd?',
      answer:
        'Deep-chested breeds carry elevated GDV risk. Many veterinarians discuss prophylactic gastropexy ' +
        '(often at the time of spay/neuter) for German Shepherds, Great Danes, and similar deep-chested dogs. ' +
        'The decision is individual — review the risks, benefits, and your dog\'s anatomy with your veterinarian.',
    },
    {
      question: 'What is degenerative myelopathy and is it preventable?',
      answer:
        'Degenerative myelopathy (DM) is a progressive, adult-onset spinal-cord disease. A SOD1 DNA test identifies ' +
        'genetic risk. There is no proven prevention or cure, but physiotherapy, supportive aids, and good general ' +
        'health can preserve quality of life. Not every at-risk dog clinically progresses, which is why the test is ' +
        'used for breeding decisions rather than diagnosis.',
    },
    {
      question: 'Are German Shepherds harder to insure than other breeds?',
      answer:
        'Premiums for German Shepherds are typically higher than the canine average because of the breed\'s claim ' +
        'profile (joints, skin, GI). Enroll in puppyhood before any joint, skin, or GI finding to keep the most ' +
        'common claim categories covered.',
    },
  ],
  sourceCitations: [
    { ref: 'ofa-stats', label: 'Orthopedic Foundation for Animals — Breed Statistics', url: 'https://ofa.org/diseases/breed-statistics/' },
    { ref: 'chic-gsd', label: 'OFA CHIC — German Shepherd Dog Club of America Required Panel', url: 'https://ofa.org/chic-programs/' },
    { ref: 'gsdca-health', label: 'German Shepherd Dog Club of America — Health Committee', url: 'https://www.gsdca.org/health/' },
    { ref: 'akc-gsd', label: 'American Kennel Club — German Shepherd Breed Standard', url: 'https://www.akc.org/dog-breeds/german-shepherd-dog/' },
  ],
}

// ─────────────────────────────────────────────────────────────────────────────
// FRENCH BULLDOG
// ─────────────────────────────────────────────────────────────────────────────
const frenchBulldog: BreedHealthRecord = {
  slug: 'french-bulldog',
  breedName: 'French Bulldog',
  lifespanRange: '10–12 years',
  overview:
    'French Bulldogs are one of the most medically complex breeds in companion dog ' +
    'medicine. Brachycephalic Obstructive Airway Syndrome (BOAS), intervertebral ' +
    'disc disease (IVDD), and dermatologic issues drive most of the lifetime cost. ' +
    'The French Bull Dog Club of America CHIC panel is the appropriate baseline.',
  knownHealthIssues: [
    {
      name: 'Brachycephalic Obstructive Airway Syndrome (BOAS)',
      frequency: 'common',
      summary:
        'A constellation of stenotic nares, elongated soft palate, hypoplastic ' +
        'trachea, and laryngeal collapse. Most Frenchies show some grade of BOAS; ' +
        'specialist functional grading (e.g., RFG / Cambridge BOAS scheme) is ' +
        'increasingly used for breeding and surgical decisions.',
      ageOfOnset: 'Signs present from puppyhood; worsen with age and weight',
      screeningTest: 'BOAS functional grading by a veterinary surgeon',
      citedRef: 'chic-frenchie',
    },
    {
      name: 'Intervertebral disc disease (IVDD)',
      frequency: 'common',
      summary:
        'Chondrodystrophic anatomy and frequent hemivertebrae create high IVDD risk. ' +
        'Presentations range from neck or back pain to sudden hindlimb paralysis, ' +
        'which is a surgical emergency.',
      ageOfOnset: 'Often 2–6 years',
      screeningTest: 'Spinal radiographs; MRI/CT for symptomatic dogs',
    },
    {
      name: 'Allergic skin disease and skin-fold dermatitis',
      frequency: 'common',
      summary:
        'Atopic dermatitis is highly prevalent in the breed. Facial skin folds, ' +
        'tail-pocket folds, and intertriginous areas trap moisture and bacteria, ' +
        'producing chronic dermatitis without daily hygiene.',
      ageOfOnset: 'Often begins under 3 years',
    },
    {
      name: 'Heat intolerance / heatstroke',
      frequency: 'common',
      summary:
        'Compromised upper-airway anatomy severely limits panting, the dog\'s ' +
        'primary thermoregulatory mechanism. Heatstroke can develop at temperatures ' +
        'comfortable to humans and is a leading cause of preventable death in the breed.',
      ageOfOnset: 'Any age',
    },
    {
      name: 'Patellar luxation',
      frequency: 'occasional',
      summary:
        'Medial patellar luxation is common across small breeds and is part of the ' +
        'CHIC panel. Mild luxation is managed conservatively; higher grades may ' +
        'require surgical correction.',
      ageOfOnset: 'Often identified during puppy exams or early adulthood',
      screeningTest: 'OFA patella evaluation',
      citedRef: 'chic-frenchie',
    },
    {
      name: 'Ophthalmic disease (cherry eye, corneal ulcers, KCS)',
      frequency: 'occasional',
      summary:
        'Shallow orbits and prominent eyes increase corneal injury risk. Annual ' +
        'OFA Eye Certification is CHIC-recommended.',
      ageOfOnset: 'Any age; cherry eye often in puppyhood',
      screeningTest: 'Annual OFA Eye Certification (CAER)',
      citedRef: 'chic-frenchie',
    },
  ],
  recommendedScreenings: [
    { name: 'BOAS functional grading by a veterinary surgeon', ageRecommended: 'From 12 months', frequency: 'Once; re-evaluate if signs change' },
    { name: 'Spinal exam and discussion of IVDD risk reduction', ageRecommended: 'Adulthood and ongoing', frequency: 'At each annual exam' },
    { name: 'OFA Eye Certification (CAER)', ageRecommended: 'From 12 months', frequency: 'Annually' },
    { name: 'OFA patella evaluation', ageRecommended: 'From 12 months', frequency: 'Once' },
    { name: 'Skin and ear exam', ageRecommended: 'Any age', frequency: 'At least annually' },
  ],
  breedSpecificVaccinations: [
    'No Frenchie-specific schedule; follow AAHA canine vaccination guidelines for core vaccines',
    'Discuss timing carefully — vaccinate when the dog is well, not during a flare of skin or airway disease',
  ],
  emergencySigns: [
    'Heavy panting, blue/purple gums, collapse — suspected heatstroke or BOAS crisis',
    'Sudden inability to use hindlimbs — suspected IVDD',
    'Acute eye injury, persistent squinting, or cloudiness',
    'Severe vomiting, choking, or aspiration',
    'Bloody or copious nasal discharge in a dog with known airway disease',
  ],
  preventiveCareTips: [
    'Keep slim. Even modest weight gain measurably worsens BOAS and IVDD risk.',
    'Use a harness, never a neck collar — leash pressure on a compromised airway is dangerous.',
    'Stairs and jumping off furniture stress the spine — use ramps and gates.',
    'Daily face-fold and tail-pocket hygiene with vet-recommended products.',
    'Never leave the dog in a warm car, even briefly. Limit summer activity to cool morning/evening hours.',
    'Choose a veterinarian comfortable with brachycephalic anesthesia for any surgery.',
  ],
  typicalInsuranceCostImplications:
    'BOAS surgery, IVDD management or surgery, and chronic dermatology drive the ' +
    'majority of lifetime medical costs for Frenchies. Many owners report total ' +
    'lifetime out-of-pocket costs running into the five figures without insurance. ' +
    'Enroll before any airway, spinal, or dermatologic diagnosis — the breed\'s ' +
    'profile makes coverage exclusions especially costly.',
  faqs: [
    {
      question: 'Should every French Bulldog have BOAS surgery?',
      answer:
        'No. BOAS exists on a functional spectrum. A veterinary surgeon\'s functional grading guides whether airway ' +
        'surgery (stenotic nares correction, soft-palate resection, sacculectomy) is appropriate. Many Grade 2–3 dogs ' +
        'benefit substantially from early surgery; mildly affected dogs may be managed conservatively.',
    },
    {
      question: 'How can I reduce IVDD risk in my Frenchie?',
      answer:
        'You cannot eliminate it — the breed\'s anatomy is the underlying driver. But maintaining a lean body condition, ' +
        'using ramps instead of jumping, harness (not neck collar) walking, and avoiding high-impact play all reduce ' +
        'mechanical load on the spine. Discuss your dog\'s specific risk profile with your veterinarian.',
    },
    {
      question: 'Is pet insurance worth it for a French Bulldog?',
      answer:
        'For most Frenchie owners, yes — the breed\'s claim profile (airway, spine, skin) generates expensive, ' +
        'unpredictable bills that insurance is designed to cover. Compare policies specifically for BOAS, spinal disease, ' +
        'and chronic dermatology coverage, and enroll before any related diagnosis.',
    },
  ],
  sourceCitations: [
    { ref: 'chic-frenchie', label: 'OFA CHIC — French Bull Dog Club of America Required Panel', url: 'https://ofa.org/chic-programs/' },
    { ref: 'cambridge-boas', label: 'University of Cambridge — BOAS Research and Functional Grading Scheme', url: 'https://www.vet.cam.ac.uk/research/boas' },
    { ref: 'fbdca-health', label: 'French Bull Dog Club of America — Health & Genetics', url: 'https://frenchbulldogclub.org/health/' },
    { ref: 'akc-frenchie', label: 'American Kennel Club — French Bulldog Breed Standard', url: 'https://www.akc.org/dog-breeds/french-bulldog/' },
  ],
}

// ─────────────────────────────────────────────────────────────────────────────
// POODLE (Standard, with notes on Miniature/Toy where relevant)
// ─────────────────────────────────────────────────────────────────────────────
const poodle: BreedHealthRecord = {
  slug: 'poodle',
  breedName: 'Poodle',
  lifespanRange: '10–18 years (varies by variety: Standard 10–14, Mini & Toy 14–18)',
  overview:
    'The Poodle is divided into Standard, Miniature, and Toy varieties, each with ' +
    'a slightly different health profile. The Poodle Club of America CHIC panel ' +
    'separates required tests by variety; Standards focus on hip dysplasia and ' +
    'sebaceous adenitis, Minis and Toys emphasize patellar luxation and eye disease.',
  knownHealthIssues: [
    {
      name: 'Hip dysplasia (especially Standard)',
      frequency: 'occasional',
      summary:
        'Standard Poodles are evaluated at meaningful rates in OFA hip data. ' +
        'OFA hip clearance on both parents is part of the PCA CHIC panel for ' +
        'Standards.',
      ageOfOnset: 'Lameness can begin in late puppyhood',
      screeningTest: 'OFA hip evaluation (Standards)',
      citedRef: 'chic-poodle',
    },
    {
      name: 'Patellar luxation (especially Miniature & Toy)',
      frequency: 'common',
      summary:
        'Common in the smaller varieties. OFA patella evaluation is CHIC-required ' +
        'for Miniature and Toy Poodles.',
      ageOfOnset: 'Often diagnosed during puppy exams or early adulthood',
      screeningTest: 'OFA patella evaluation (Mini, Toy)',
      citedRef: 'chic-poodle',
    },
    {
      name: 'Progressive retinal atrophy (prcd-PRA)',
      frequency: 'occasional',
      summary:
        'Adult-onset retinal degeneration with progressive vision loss. The ' +
        'CHIC panel for the smaller varieties recommends both DNA testing and ' +
        'annual ophthalmologist exam.',
      ageOfOnset: 'Adult onset (3–8 years for many affected dogs)',
      screeningTest: 'prcd-PRA DNA test + annual OFA Eye Certification (CAER)',
      citedRef: 'chic-poodle',
    },
    {
      name: 'Sebaceous adenitis (Standards)',
      frequency: 'occasional',
      summary:
        'Inflammatory destruction of the sebaceous glands, producing dry, scaling ' +
        'skin and patchy hair loss. CHIC-recommended skin punch biopsy screening ' +
        'is offered for breeding Standards.',
      ageOfOnset: 'Young adulthood',
      screeningTest: 'Skin punch biopsy',
      citedRef: 'chic-poodle',
    },
    {
      name: 'Addison\'s disease (hypoadrenocorticism)',
      frequency: 'occasional',
      summary:
        'Standards are over-represented in Addison\'s populations. Vague signs ' +
        '(lethargy, intermittent vomiting, weakness) can delay diagnosis; an ' +
        'Addisonian crisis is a true emergency.',
      ageOfOnset: 'Young to middle adulthood (2–7 years typical)',
      screeningTest: 'Basal cortisol; ACTH stimulation test',
    },
    {
      name: 'Gastric dilatation–volvulus (Standards)',
      frequency: 'occasional',
      summary:
        'Standards are deep-chested and carry elevated GDV risk. Owners should ' +
        'learn the warning signs and discuss prophylactic gastropexy with their ' +
        'veterinarian.',
      ageOfOnset: 'Adulthood; risk increases with age',
    },
  ],
  recommendedScreenings: [
    { name: 'OFA hip radiograph (Standards)', ageRecommended: 'After 24 months', frequency: 'Once' },
    { name: 'OFA patella evaluation (Mini, Toy)', ageRecommended: 'From 12 months', frequency: 'Once' },
    { name: 'Annual eye exam (CAER)', ageRecommended: 'From 12 months', frequency: 'Annually' },
    { name: 'prcd-PRA DNA test', ageRecommended: 'Any age', frequency: 'Once' },
    { name: 'Sebaceous adenitis biopsy (Standards, optional for pets)', ageRecommended: 'Adulthood', frequency: 'As advised by vet' },
  ],
  breedSpecificVaccinations: [
    'No Poodle-specific schedule; follow AAHA canine vaccination guidelines for core vaccines',
  ],
  emergencySigns: [
    'Distended abdomen with unproductive retching (suspected GDV — Standards)',
    'Sudden collapse with weakness and vomiting (possible Addisonian crisis)',
    'Acute lameness or non-weight-bearing limp (patellar luxation flare)',
    'Sudden vision changes',
    'Severe skin disease with secondary infection',
  ],
  preventiveCareTips: [
    'Regular professional grooming every 4–6 weeks plus weekly brushing — Poodle coat tangles fast.',
    'Maintain lean body condition lifelong.',
    'Standards: discuss prophylactic gastropexy with your veterinarian.',
    'Schedule the OFA Eye Certification annually with a veterinary ophthalmologist.',
    'Brush teeth daily — small-variety Poodles are particularly prone to dental disease.',
  ],
  typicalInsuranceCostImplications:
    'Lifetime cost depends heavily on variety. Standards see higher orthopedic, ' +
    'Addison\'s, and emergency GDV exposure; Miniatures and Toys see more dental, ' +
    'patellar, and eye-disease spend. Insurance enrolled before any joint, eye, ' +
    'or endocrine diagnosis keeps the largest claim categories in scope.',
  faqs: [
    {
      question: 'Are Poodles really hypoallergenic?',
      answer:
        'No breed is truly hypoallergenic. Poodles shed less hair into the environment than many breeds because of their ' +
        'curly, continuously-growing coat, which can mean less dander accumulation. People with allergies should still ' +
        'spend significant time with the specific dog before committing — individual tolerance varies widely.',
    },
    {
      question: 'Which Poodle variety is healthiest?',
      answer:
        'Each variety has its own profile. Miniatures and Toys tend to live longer on average but see more dental, ' +
        'patellar, and eye disease. Standards have higher orthopedic, Addison\'s, and GDV exposure. The Poodle Club of ' +
        'America CHIC panel reflects these differences.',
    },
    {
      question: 'Is pet insurance worth it for a Poodle?',
      answer:
        'For most Poodle owners, yes — the breed lives long enough that chronic-condition coverage adds meaningful ' +
        'value, and the variety-specific risks (GDV in Standards; dental and patellar surgery in smaller varieties) ' +
        'are exactly the bills insurance is designed for.',
    },
  ],
  sourceCitations: [
    { ref: 'chic-poodle', label: 'OFA CHIC — Poodle Club of America Required Panels (Standard, Miniature, Toy)', url: 'https://ofa.org/chic-programs/' },
    { ref: 'pca-health', label: 'Poodle Club of America — Health Information', url: 'https://poodleclubofamerica.org/health/' },
    { ref: 'akc-poodle', label: 'American Kennel Club — Poodle Breed Standard', url: 'https://www.akc.org/dog-breeds/poodle-standard/' },
  ],
}

// ─────────────────────────────────────────────────────────────────────────────
// BULLDOG (English Bulldog)
// ─────────────────────────────────────────────────────────────────────────────
const bulldog: BreedHealthRecord = {
  slug: 'bulldog',
  breedName: 'Bulldog',
  lifespanRange: '8–10 years',
  overview:
    'The Bulldog is one of the most medically complex breeds and one of the ' +
    'shorter-lived large-headed companion breeds. BOAS, dermatologic disease, ' +
    'orthopedic problems, and dystocia (most litters require Cesarean) shape ' +
    'breed care. The Bulldog Club of America CHIC panel reflects these priorities.',
  knownHealthIssues: [
    {
      name: 'Brachycephalic Obstructive Airway Syndrome (BOAS)',
      frequency: 'common',
      summary:
        'Stenotic nares, elongated soft palate, hypoplastic trachea, and ' +
        'laryngeal collapse are very common. Most Bulldogs benefit from a BOAS ' +
        'functional assessment; early airway surgery in moderate-to-severe dogs ' +
        'meaningfully improves quality of life.',
      ageOfOnset: 'Signs present from puppyhood; worsen with age and weight',
      screeningTest: 'BOAS functional grading by a veterinary surgeon',
      citedRef: 'chic-bulldog',
    },
    {
      name: 'Skin-fold dermatitis and allergic skin disease',
      frequency: 'common',
      summary:
        'Facial folds, tail pockets, and intertriginous body folds trap moisture ' +
        'and bacteria. Daily hygiene is required. Concurrent atopic dermatitis is ' +
        'common and often needs dermatology-directed care.',
      ageOfOnset: 'Any age; signs often present by 1–3 years',
    },
    {
      name: 'Hip dysplasia',
      frequency: 'common',
      summary:
        'OFA submissions show Bulldogs among the most affected breeds for hip ' +
        'dysplasia. Many affected dogs adapt because of their structure and low ' +
        'activity level, but arthritis still progresses.',
      ageOfOnset: 'Late puppyhood to early adulthood',
      screeningTest: 'OFA hip evaluation',
      citedRef: 'ofa-stats',
    },
    {
      name: 'Heat intolerance / heatstroke',
      frequency: 'common',
      summary:
        'Compromised upper-airway anatomy and dense body composition severely ' +
        'limit thermoregulation. Heatstroke can develop at temperatures ' +
        'comfortable for humans.',
      ageOfOnset: 'Any age',
    },
    {
      name: 'Cherry eye and other ophthalmic conditions',
      frequency: 'common',
      summary:
        'Prolapse of the third-eyelid gland (cherry eye) is common in young ' +
        'Bulldogs and is corrected surgically. Entropion and dry eye (KCS) also ' +
        'occur. Annual OFA Eye Certification is CHIC-recommended.',
      ageOfOnset: 'Often puppyhood for cherry eye',
      screeningTest: 'Annual OFA Eye Certification (CAER)',
      citedRef: 'chic-bulldog',
    },
    {
      name: 'Dental disease and crowded jaw',
      frequency: 'common',
      summary:
        'Brachycephalic jaw structure crowds teeth and accelerates periodontal ' +
        'disease. Daily brushing and routine professional dental cleanings are ' +
        'standard care.',
      ageOfOnset: 'Worsens through middle age',
    },
  ],
  recommendedScreenings: [
    { name: 'BOAS functional grading by a veterinary surgeon', ageRecommended: 'From 12 months', frequency: 'Once; re-evaluate if signs change' },
    { name: 'OFA Eye Certification (CAER)', ageRecommended: 'From 12 months', frequency: 'Annually' },
    { name: 'OFA hip evaluation', ageRecommended: 'After 24 months', frequency: 'Once' },
    { name: 'Cardiac auscultation (and echo if murmur detected)', ageRecommended: 'From 12 months', frequency: 'Annually' },
    { name: 'Skin and ear exam', ageRecommended: 'Any age', frequency: 'At least annually' },
  ],
  breedSpecificVaccinations: [
    'No Bulldog-specific schedule; follow AAHA canine vaccination guidelines for core vaccines',
    'Time vaccines when the dog is well, not during a skin or airway flare',
  ],
  emergencySigns: [
    'Heavy panting, blue/purple gums, collapse — suspected heatstroke or BOAS crisis',
    'Acute eye injury, redness with squinting, or sudden vision change',
    'Difficulty whelping (Bulldog litters typically require Cesarean section — plan with a vet)',
    'Severe vomiting with airway distress (high aspiration risk)',
    'Open or rapidly worsening skin lesions',
  ],
  preventiveCareTips: [
    'Keep lean — Bulldogs gain weight quickly and weight worsens both BOAS and joint disease.',
    'Walk in cool morning/evening hours; never leave the dog in a warm car.',
    'Use a harness, never a neck collar.',
    'Clean facial folds and tail pocket daily with vet-recommended products.',
    'Brush teeth daily; book professional dental cleanings as advised by your veterinarian.',
    'Choose a veterinarian comfortable with brachycephalic anesthesia for any surgery.',
  ],
  typicalInsuranceCostImplications:
    'Bulldogs are among the most expensive breeds to insure because the lifetime ' +
    'claim profile (airway surgery, chronic dermatology, dental, eye surgery, ' +
    'reproductive care) is heavy and predictable. Enroll before any airway, skin, ' +
    'or eye diagnosis. Compare policies specifically for BOAS, dermatology, and ' +
    'orthopedic coverage.',
  faqs: [
    {
      question: 'Why do Bulldogs have such short lifespans?',
      answer:
        'Brachycephalic anatomy, chronic dermatologic and orthopedic disease, and historically narrow gene pools ' +
        'all contribute. Lean body condition, early BOAS assessment, daily skin hygiene, and routine veterinary care ' +
        'meaningfully extend healthspan, but the breed\'s baseline lifespan is genuinely shorter than most.',
    },
    {
      question: 'Can a Bulldog be born without a Cesarean section?',
      answer:
        'It happens occasionally, but the breed\'s pelvic and fetal-head anatomy means the vast majority of litters ' +
        'are delivered by planned C-section. Reputable breeders plan this with their veterinarian; pet owners should ' +
        'understand it as a real risk if their dog is intact.',
    },
    {
      question: 'Is pet insurance worth it for a Bulldog?',
      answer:
        'For most Bulldog owners, yes — the breed\'s claim profile is heavy and predictable enough that insurance ' +
        'is often economically rational. Enroll before any airway, skin, or eye diagnosis to keep the largest claim ' +
        'categories in scope.',
    },
  ],
  sourceCitations: [
    { ref: 'chic-bulldog', label: 'OFA CHIC — Bulldog Club of America Required Panel', url: 'https://ofa.org/chic-programs/' },
    { ref: 'ofa-stats', label: 'Orthopedic Foundation for Animals — Breed Statistics', url: 'https://ofa.org/diseases/breed-statistics/' },
    { ref: 'bca-health', label: 'Bulldog Club of America — Health Committee', url: 'https://www.bulldogclubofamerica.org/health/' },
    { ref: 'akc-bulldog', label: 'American Kennel Club — Bulldog Breed Standard', url: 'https://www.akc.org/dog-breeds/bulldog/' },
  ],
}

// ─────────────────────────────────────────────────────────────────────────────
// BEAGLE
// ─────────────────────────────────────────────────────────────────────────────
const beagle: BreedHealthRecord = {
  slug: 'beagle',
  breedName: 'Beagle',
  lifespanRange: '12–15 years',
  overview:
    'Beagles are a generally healthy hound breed with a few well-characterized ' +
    'predispositions: intervertebral disc disease, primary glaucoma, epilepsy, ' +
    'hypothyroidism, and obesity from a strong food drive. The National Beagle Club ' +
    'CHIC panel reflects these priorities.',
  knownHealthIssues: [
    {
      name: 'Intervertebral disc disease (IVDD)',
      frequency: 'occasional',
      summary:
        'Beagles are chondrodystrophic and carry meaningful IVDD risk. Presentations ' +
        'range from neck or back pain to sudden hindlimb paralysis, which is a ' +
        'surgical emergency.',
      ageOfOnset: '3–7 years for many cases',
    },
    {
      name: 'Primary glaucoma',
      frequency: 'occasional',
      summary:
        'Beagles are an over-represented breed for primary closed-angle glaucoma. ' +
        'Sudden eye redness, squinting, and a fixed dilated pupil are emergencies — ' +
        'untreated glaucoma rapidly causes blindness.',
      ageOfOnset: 'Often middle age (3–7 years)',
      screeningTest: 'OFA Eye Certification (CAER); gonioscopy in lines with known glaucoma',
      citedRef: 'chic-beagle',
    },
    {
      name: 'Idiopathic epilepsy',
      frequency: 'occasional',
      summary:
        'Inherited seizure disorder presenting in young-adult dogs. Diagnosis is ' +
        'by exclusion; many dogs control well on long-term anticonvulsants.',
      ageOfOnset: 'Most cases between 1 and 5 years',
    },
    {
      name: 'Hypothyroidism',
      frequency: 'occasional',
      summary:
        'Adult-onset thyroid disease occurs at meaningful rates in Beagles. Signs ' +
        'include weight gain despite normal intake, dull coat, lethargy, and ' +
        'heat-seeking behavior.',
      ageOfOnset: 'Middle age (4+ years)',
      screeningTest: 'Thyroid panel (T4, free T4, TSH)',
      citedRef: 'chic-beagle',
    },
    {
      name: 'Obesity',
      frequency: 'common',
      summary:
        'Beagles are highly food-motivated and gain weight quickly. Obesity worsens ' +
        'joint disease and shortens lifespan and is the single most modifiable risk ' +
        'for the breed.',
      ageOfOnset: 'Any age; often accelerates after spay/neuter and middle age',
    },
    {
      name: 'Otitis externa (ear infections)',
      frequency: 'common',
      summary:
        'Heavy, low-set ears reduce air flow into the canal and predispose to ' +
        'recurrent yeast and bacterial otitis. Routine ear care reduces flare ' +
        'frequency.',
      ageOfOnset: 'Any age',
    },
  ],
  recommendedScreenings: [
    { name: 'Annual eye exam (CAER); gonioscopy where indicated', ageRecommended: 'From 12 months', frequency: 'Annually' },
    { name: 'Thyroid panel', ageRecommended: 'From 4 years', frequency: 'Periodically; sooner if signs' },
    { name: 'Body condition scoring', ageRecommended: 'Lifelong', frequency: 'Every visit' },
    { name: 'Ear exam', ageRecommended: 'Any age', frequency: 'At least annually; sooner if recurrent infection' },
    { name: 'Senior bloodwork', ageRecommended: 'From 8 years', frequency: 'Annually' },
  ],
  breedSpecificVaccinations: [
    'No Beagle-specific schedule; follow AAHA canine vaccination guidelines for core vaccines',
    'Discuss leptospirosis given the breed\'s outdoor sniffing and wildlife exposure',
  ],
  emergencySigns: [
    'Acute eye redness with squinting and a fixed pupil (possible glaucoma — go now)',
    'Sudden hindlimb weakness or knuckling (possible IVDD)',
    'First-time seizure or cluster of seizures',
    'Repeated vomiting or known foreign-body ingestion',
    'Severe head-shaking, ear pain, or sudden hearing change',
  ],
  preventiveCareTips: [
    'Measure meals and count treats against the daily calorie target — Beagles will eat far past satiety.',
    'Annual eye exam with a veterinary ophthalmologist starting at 12 months.',
    'Clean ears weekly with a vet-approved cleaner; dry thoroughly after baths and swims.',
    'Secure trash, medications, chocolate, and xylitol products — the breed is notorious for indiscriminate ingestion.',
    'Use a harness and a long line for off-property exploration; the breed will follow a scent and disregard recall.',
  ],
  typicalInsuranceCostImplications:
    'Beagles live long enough that chronic-disease management often dominates ' +
    'lifetime cost: epilepsy medications, thyroid supplementation, ophthalmic ' +
    'workups, and recurrent dermatologic or otic disease. Insurance enrolled in ' +
    'puppyhood keeps these chronic conditions in scope.',
  faqs: [
    {
      question: 'Do Beagles really need an eye exam every year?',
      answer:
        'Annual OFA Eye Certification (CAER) is CHIC-recommended for Beagles because of the breed\'s elevated ' +
        'primary glaucoma risk. Early identification matters — glaucoma can cause permanent vision loss in hours.',
    },
    {
      question: 'My Beagle is always hungry — what should I do?',
      answer:
        'That is breed-typical and does not mean the dog is underfed. Weigh meals on a kitchen scale, count treats ' +
        'against the daily calorie budget, avoid free-feeding, and use slow-feeders or food puzzles to slow intake. ' +
        'Discuss target body condition score with your vet at each visit.',
    },
    {
      question: 'Is pet insurance worth it for a Beagle?',
      answer:
        'For many Beagle owners, yes — long lifespan plus chronic conditions (epilepsy, thyroid, ophthalmic, ' +
        'recurrent ear disease) make insurance economically rational. Enroll before any of these conditions is ' +
        'documented.',
    },
  ],
  sourceCitations: [
    { ref: 'chic-beagle', label: 'OFA CHIC — National Beagle Club Required Panel', url: 'https://ofa.org/chic-programs/' },
    { ref: 'nbc-health', label: 'National Beagle Club of America — Health Information', url: 'https://nationalbeagleclub.org/health/' },
    { ref: 'akc-beagle', label: 'American Kennel Club — Beagle Breed Standard', url: 'https://www.akc.org/dog-breeds/beagle/' },
  ],
}

// ─────────────────────────────────────────────────────────────────────────────
// YORKSHIRE TERRIER
// ─────────────────────────────────────────────────────────────────────────────
const yorkshireTerrier: BreedHealthRecord = {
  slug: 'yorkshire-terrier',
  breedName: 'Yorkshire Terrier',
  lifespanRange: '12–15 years',
  overview:
    'Yorkshire Terriers are a long-lived toy breed with breed-characteristic ' +
    'predispositions: portosystemic shunts (liver shunt), tracheal collapse, ' +
    'patellar luxation, Legg-Calvé-Perthes, dental disease, and hypoglycemia in ' +
    'puppies. The Yorkshire Terrier Club of America CHIC panel reflects these.',
  knownHealthIssues: [
    {
      name: 'Portosystemic shunt (liver shunt)',
      frequency: 'occasional',
      summary:
        'Yorkies are one of the most over-represented breeds for congenital ' +
        'portosystemic shunts, in which blood bypasses the liver. Hallmark signs ' +
        'include poor growth, neurological signs after meals, and unexplained ' +
        'small body size.',
      ageOfOnset: 'Puppyhood',
      screeningTest: 'Bile acids assay; abdominal imaging',
      citedRef: 'chic-yorkie',
    },
    {
      name: 'Tracheal collapse',
      frequency: 'common',
      summary:
        'Weakened tracheal cartilage causes a classic "goose honk" cough and ' +
        'exercise or excitement-related coughing. Many dogs are managed medically; ' +
        'severe cases may need stenting.',
      ageOfOnset: 'Often middle age (5+)',
      screeningTest: 'Radiographs / fluoroscopy',
    },
    {
      name: 'Patellar luxation',
      frequency: 'common',
      summary:
        'Medial patellar luxation is common across toy breeds. Mild luxation is ' +
        'managed conservatively; higher grades may require surgical correction.',
      ageOfOnset: 'Often identified during puppy exams',
      screeningTest: 'OFA patella evaluation',
      citedRef: 'chic-yorkie',
    },
    {
      name: 'Legg-Calvé-Perthes disease',
      frequency: 'occasional',
      summary:
        'Idiopathic avascular necrosis of the femoral head in toy breeds, ' +
        'presenting as hindlimb lameness in juvenile dogs. Treated surgically ' +
        '(femoral head osteotomy) in most cases.',
      ageOfOnset: '5–8 months typically',
      screeningTest: 'Hip radiographs',
    },
    {
      name: 'Dental disease (periodontal disease, retained deciduous teeth)',
      frequency: 'common',
      summary:
        'Toy-breed jaws crowd teeth and accelerate periodontal disease. Retained ' +
        'baby teeth are common and should be extracted at the spay/neuter to prevent ' +
        'crowding and decay.',
      ageOfOnset: 'Worsens through middle age',
    },
    {
      name: 'Juvenile hypoglycemia',
      frequency: 'common',
      summary:
        'Toy-breed puppies are at risk of clinically significant hypoglycemia, ' +
        'especially when stressed, not eating, or chilled. Owners should know how ' +
        'to recognize it and have a vet-recommended sugar-source plan.',
      ageOfOnset: 'First 4–6 months of life',
    },
  ],
  recommendedScreenings: [
    { name: 'Bile acids assay if growth or neurological concerns', ageRecommended: 'Puppyhood, as advised by vet', frequency: 'As needed' },
    { name: 'OFA patella evaluation', ageRecommended: 'From 12 months', frequency: 'Once' },
    { name: 'Annual eye exam (CAER)', ageRecommended: 'From 12 months', frequency: 'Annually' },
    { name: 'Dental exam and prophylactic cleaning', ageRecommended: 'From 3 years', frequency: 'Annually or as advised' },
    { name: 'Senior bloodwork', ageRecommended: 'From 8 years', frequency: 'Annually' },
  ],
  breedSpecificVaccinations: [
    'No Yorkie-specific schedule; follow AAHA canine vaccination guidelines for core vaccines',
    'Discuss spacing vaccines and avoiding excessive concurrent vaccines in a toy puppy with your vet',
  ],
  emergencySigns: [
    'Sudden weakness, wobbling, or seizure in a puppy (possible hypoglycemia)',
    'Severe coughing fit with collapse (possible tracheal collapse crisis)',
    'Neurological signs after eating in a puppy (possible liver shunt episode)',
    'Acute non-weight-bearing lameness',
    'Vomiting with weakness in a small or stressed puppy',
  ],
  preventiveCareTips: [
    'Daily tooth brushing — toy-breed dental disease is largely preventable.',
    'Harness, never neck collar — protect the trachea from leash pressure.',
    'Feed small puppies frequent measured meals to maintain blood glucose.',
    'Use ramps and avoid jumps from furniture — patella and back protection.',
    'Monitor for cough patterns and breathing changes as the dog ages.',
  ],
  typicalInsuranceCostImplications:
    'Yorkies live long enough that chronic conditions (dental, tracheal collapse, ' +
    'cardiac) dominate lifetime cost. Liver-shunt surgery, patellar surgery, and ' +
    'dental disease can each generate large unexpected bills. Insurance enrolled in ' +
    'puppyhood keeps these in scope.',
  faqs: [
    {
      question: 'How do I know if my Yorkie puppy has a liver shunt?',
      answer:
        'Hallmark signs include poor growth, unexplained small body size, neurological signs after meals ' +
        '(disorientation, head pressing, seizures), and slow recovery from anesthesia. A bile acids assay is ' +
        'the standard screening blood test; abdominal imaging confirms anatomic shunts.',
    },
    {
      question: 'Does my Yorkie really need a harness instead of a collar?',
      answer:
        'For most Yorkies, yes. Tracheal collapse is common in the breed, and leash pressure on a small, fragile ' +
        'trachea can trigger or worsen coughing episodes. A well-fitted harness distributes leash pressure across ' +
        'the chest instead.',
    },
    {
      question: 'Is pet insurance worth it for a Yorkshire Terrier?',
      answer:
        'For most Yorkie owners, yes — long lifespan plus toy-breed risks (liver shunt, tracheal collapse, ' +
        'dental, patellar) make insurance economically rational. Enroll in puppyhood before any of these ' +
        'conditions is documented.',
    },
  ],
  sourceCitations: [
    { ref: 'chic-yorkie', label: 'OFA CHIC — Yorkshire Terrier Club of America Required Panel', url: 'https://ofa.org/chic-programs/' },
    { ref: 'ytca-health', label: 'Yorkshire Terrier Club of America — Health Information', url: 'https://ytca.org/health/' },
    { ref: 'akc-yorkie', label: 'American Kennel Club — Yorkshire Terrier Breed Standard', url: 'https://www.akc.org/dog-breeds/yorkshire-terrier/' },
  ],
}

// ─────────────────────────────────────────────────────────────────────────────
// COLLECTION
// ─────────────────────────────────────────────────────────────────────────────
export const BreedHealthRecords: ReadonlyArray<BreedHealthRecord> = [
  labradorRetriever,
  goldenRetriever,
  germanShepherd,
  frenchBulldog,
  poodle,
  bulldog,
  beagle,
  yorkshireTerrier,
]

export function getBreedHealthBySlug(slug: string): BreedHealthRecord | undefined {
  return BreedHealthRecords.find((r) => r.slug === slug)
}
