import type { Metadata } from 'next'
import { buildMetadata, ArticleLayout, EmailCapture, RelatedLinks, FAQAccordion } from '@carloOS/ui'
import { buildArticleSchema, buildMedicalWebPageSchema, buildFAQSchema, combineSchemas, SchemaScript } from '@carloOS/ui'

export const metadata: Metadata = buildMetadata({ siteId: 'lizard-com', title: 'Hypocalcemia in Reptiles — Tremors, Tetany | Lizard.com', description: 'Acute hypocalcemia (low blood calcium) in reptiles causes tremors, tetany, and seizures. Emergency calcium gluconate by injection. How to distinguish from MBD.', path: '/health/hypocalcemia', type: 'article' })

const articleSchema = buildArticleSchema({ siteId: 'lizard-com', title: 'Hypocalcemia in Reptiles', description: 'Emergency recognition, distinction from chronic MBD, treatment, and prevention of acute hypocalcemia in captive reptiles.', url: 'https://lizard.com/health/hypocalcemia', imageUrl: '', authorName: 'Lizard.com Editorial', publishedAt: '2025-05-01T00:00:00Z', modifiedAt: '2026-05-28T00:00:00Z' })

const medSchema = buildMedicalWebPageSchema({ name: 'Hypocalcemia in Reptiles', description: 'Acute hypocalcemia in reptiles — recognition, distinction from MBD, emergency treatment, and prevention.', url: 'https://lizard.com/health/hypocalcemia', authorName: 'Lizard.com Editorial', lastReviewed: '2026-05-28' })

const FAQS = [
  { question: 'Is hypocalcemia the same as metabolic bone disease (MBD)?', answer: 'No, but they are closely related. Metabolic bone disease (nutritional secondary hyperparathyroidism) describes the chronic skeletal demineralization that happens over weeks to months when dietary calcium, vitamin D3, or both are inadequate. Hypocalcemia describes an acutely low circulating blood calcium concentration, which is a neuromuscular emergency. A reptile can have advanced MBD without acute hypocalcemia — the body is busy mobilizing skeletal calcium to keep blood values within range, at the cost of the bones. Acute hypocalcemia is what happens when that buffering capacity is exceeded, most often during sudden high demand such as egg production or rapid growth.' },
  { question: 'Can I treat hypocalcemia at home with oral calcium?', answer: 'Oral calcium carbonate (such as a few drops of liquid calcium) is a reasonable supportive measure while you are arranging veterinary care, and it is appropriate as part of long-term prevention. It is not adequate as the sole treatment for a reptile that is actively tremoring, tetanic, or seizing. Oral calcium absorbs over hours and requires functional gut motility and adequate vitamin D3 status. A reptile in acute neuromuscular crisis needs parenteral (injectable) calcium administered by a veterinarian, where blood calcium can be raised within minutes. Treating tetany at home with only oral calcium risks death or permanent neurological injury.' },
  { question: 'Why are gravid female reptiles so prone to acute hypocalcemia?', answer: 'Eggshell formation places extraordinary calcium demand on the female. A female bearded dragon or veiled chameleon producing a clutch of 20 to 40 eggs is mobilizing calcium at a rate that quickly exceeds what current dietary intake plus skeletal reserves can sustain — particularly if she was already calcium-deficient before becoming gravid. Females that produce infertile clutches without male contact (common in veiled chameleons) are not exempt; the metabolic demand is the same. Supplementation must increase during follicular development and active egg production: daily calcium dusting is appropriate during this window.' },
  { question: 'How does UVB lighting prevent hypocalcemia?', answer: 'Dietary calcium can only be absorbed across the intestinal wall in the presence of activated vitamin D3 (calcitriol). Diurnal reptiles synthesize the precursor vitamin D3 in their skin under UVB radiation (specifically the 290 to 315 nanometer band). Without adequate UVB or a reliable dietary D3 source, the calcium you are dusting onto feeders is largely excreted unabsorbed. The result is a slowly-falling calcium balance that eventually exceeds the skeletal buffering capacity and produces hypocalcemia. UVB bulbs lose output well before they visually fail; verify with a Solarmeter 6.5 UV radiometer reading and replace T5 tubes on a 12-month schedule by default.' },
  { question: 'What is the difference between calcium with D3 and calcium without D3?', answer: 'Calcium with D3 supplements supply both elemental calcium and supplemental vitamin D3. They are appropriate when the animal does not receive adequate UVB (for example, nocturnal species without UVB, or as backup for diurnal species during the winter when UVB output is reduced). Calcium without D3 supplies calcium only and is the correct daily supplement for diurnal species that receive proper UVB. Over-supplementing D3 in a UVB-housed animal can cause hypervitaminosis D3 and soft-tissue mineralization; this is why the two products exist as separate SKUs and why most well-established schedules use calcium-without-D3 daily plus a small amount of multivitamin (which contains D3) once or twice weekly.' },
  { question: 'How fast should I expect a response to a calcium injection?', answer: 'In true hypocalcemia, response to appropriately administered parenteral calcium is often visible within 15 to 30 minutes — tremors reduce, the animal can right itself, voluntary movement returns. Failure to respond, or response followed by relapse, indicates either an underlying complication (renal disease, severe nutritional secondary hyperparathyroidism with little skeletal reserve, intercurrent illness) or that the neuromuscular signs were not in fact caused by hypocalcemia. Either situation requires further veterinary workup including bloodwork (ionized calcium, ionized magnesium, phosphorus, BUN, creatinine, uric acid) and radiographs to assess bone density and identify retained eggs.' },
]

const faqSchema = buildFAQSchema({ questions: FAQS.map(f => ({ question: f.question, answer: f.answer })) })
const combinedSchema = combineSchemas(articleSchema, medSchema, faqSchema)

export default function HypocalcemiaPage() {
  return (
    <>
      <SchemaScript schema={combinedSchema} />
      <ArticleLayout
        siteId="lizard-com"
        contentType="health"
        hero={{ title: 'Hypocalcemia in Reptiles', subtitle: 'Hypocalcemia — abnormally low blood calcium — is an acute neuromuscular emergency distinct from the chronic skeletal changes of MBD. When circulating calcium falls below the threshold required for normal nerve and muscle function, tremors, tetany, and seizures follow. Parenteral calcium administered by a veterinarian is the only reliable rescue. This page explains the distinction from MBD, the causes, the clinical course, and a prevention protocol you can build into routine husbandry.', category: 'Reptile Health', authorName: 'Lizard.com Editorial', authorAvatar: '🦎', publishedAt: 'May 2025', readTime: '12 min' }}
        breadcrumbs={[{ name: 'Home', href: '/' }, { name: 'Reptile Health', href: '/health/sick-reptile-signs' }, { name: 'Hypocalcemia', href: '/health/hypocalcemia' }]}
        sidebar={<>
          <div style={{ background: 'rgba(220,38,38,0.08)', border: '1px solid rgba(220,38,38,0.25)', borderRadius: '12px', padding: '16px' }}>
            <div style={{ fontSize: '11px', fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: '#ef4444', marginBottom: '8px' }}>Emergency Signs</div>
            {['Tremors — muscle twitching or shaking', 'Tetany — rigid muscle contractions', 'Inability to walk normally', 'Jerky, uncontrolled movements', 'Seizure-like episodes', 'Collapse and inability to right itself'].map(s => (
              <div key={s} style={{ padding: '4px 0', fontSize: '12px', color: 'rgba(238,240,228,0.7)', borderBottom: '1px solid rgba(220,38,38,0.15)' }}>{s}</div>
            ))}
          </div>
          <RelatedLinks title="Related Guides" links={[{ label: 'Metabolic Bone Disease', href: '/health/metabolic-bone-disease' }, { label: 'UVB Lighting Guide', href: '/setup/uvb-lighting-guide' }, { label: 'Egg Binding', href: '/health/egg-binding' }, { label: 'Vitamin A Deficiency', href: '/health/vitamin-a-deficiency' }, { label: 'Leopard Gecko Care', href: '/species/leopard-gecko' }, { label: 'Veiled Chameleon Care', href: '/species/veiled-chameleon' }]} />
          <EmailCapture variant="sidebar" siteId="lizard-com" title="Free Care Sheets" subtitle="Species guides for subscribers." source="health-hypocalcemia" ctaText="Download Free" />
        </>}
      >
        <div className="carloOS-article">
          <h2>What Hypocalcemia Is</h2>
          <p>Calcium in the blood exists in three forms: ionized (the biologically active fraction, roughly half of the total), protein-bound (mostly to albumin), and complexed with anions such as citrate and bicarbonate. It is the ionized fraction that determines neuromuscular function. When ionized calcium falls below the species-specific threshold, voltage-gated sodium channels in nerve membranes become hyperexcitable — nerves fire spontaneously, muscles contract without voluntary input, and the syndrome of tremor, tetany, and seizure begins. This is what veterinarians and herpetologists mean by acute hypocalcemia.</p>
          <p>The body defends ionized calcium aggressively. Parathyroid hormone (PTH) is released from the parathyroid glands the moment blood calcium drops, and PTH mobilizes calcium from bone, increases renal calcium retention, and (via activation of vitamin D3) increases intestinal calcium absorption. The skeleton acts as a calcium reservoir that the body draws on for years before the reservoir is exhausted. <a href="/health/metabolic-bone-disease">Metabolic bone disease</a> is what that reservoir depletion looks like on radiographs and physical exam: thin cortices, soft jaw, pathological fractures, deformity. Acute hypocalcemia is what happens when even this aggressive buffering is overwhelmed — usually because demand spikes (gravidity, rapid growth) or because the buffering machinery itself fails (severe long-standing deficiency, renal disease).</p>

          <h2>Hypocalcemia vs MBD — Why the Distinction Matters</h2>
          <p>MBD and hypocalcemia are points on the same disease spectrum, not separate conditions. The distinction matters because the response is different.</p>
          <ul>
            <li><strong>MBD (chronic):</strong> the animal is not in immediate neuromuscular crisis. Treatment is correction of the underlying husbandry deficits — UVB, calcium supplementation, dietary calcium-to-phosphorus ratio — over weeks. Oral calcium and dietary correction are sufficient. Severe cases may benefit from outpatient injectable calcium courses and supportive feeding.</li>
            <li><strong>Acute hypocalcemia (emergency):</strong> the animal is tremoring, tetanic, or seizing. The window for intervention is measured in hours. Oral calcium alone is too slow. Parenteral calcium administered by a veterinarian (calcium gluconate by the subcutaneous, intramuscular, or carefully-administered intravenous route depending on severity and species) is the only reliable rescue.</li>
          </ul>
          <p>A reptile in active tetany is not a candidate for trial-and-error home management. Get to a reptile-experienced veterinarian — see the Association of Reptilian and Amphibian Veterinarians (ARAV) directory at arav.org — the same day.</p>

          <h2>Causes</h2>

          <h3>UVB Deficiency</h3>
          <p>The most common contributor in diurnal lizards. Dietary calcium cannot be absorbed without activated vitamin D3, and diurnal species synthesize D3 from cutaneous exposure to UVB radiation (290 to 315 nanometers). A bearded dragon, uromastyx, or chameleon kept without UVB — or with a UVB tube that has degraded below useful output — will slowly fall behind on calcium balance regardless of how much calcium powder you dust onto feeders. The classic clinical narrative is months of inadequate UVB, increasing skeletal weakness (early MBD), and then an abrupt presentation with tremors when a stressor (gravidity, rapid growth, intercurrent illness) drives the system over the edge.</p>
          <p>UVB output degrades on a curve that is steeper than the bulb&apos;s visible behavior suggests. A T5 high-output tube that still looks bright may be producing a fraction of its original UVB output by month 12. The only reliable check is a UV radiometer reading at the basking surface (Solarmeter 6.5 is the field-standard instrument used by veterinary herpetologists; see published guidance from Frances Baines and the UV Tool used in evidence-based UV husbandry references). Replace tubes on a default 12-month schedule and verify with a meter — do not rely on visible brightness.</p>

          <h3>Calcium-to-Phosphorus Ratio</h3>
          <p>Feeder insects are naturally inverted in their calcium-to-phosphorus ratio — crickets, mealworms, dubia roaches, and superworms all contain more phosphorus than calcium, often dramatically so. Excess dietary phosphorus binds calcium in the gut and reduces net absorption. The compensating tools are (1) dusting feeders with calcium carbonate immediately before offering, (2) gut-loading feeders for at least 24 hours on a high-calcium diet (commercial gut-load, leafy greens such as collard or dandelion), and (3) selecting naturally higher-calcium feeders such as black-soldier-fly larvae (phoenix worms) as part of the rotation. Without correction, the calcium-to-phosphorus ratio in the gut is unfavorable enough that even adequate dietary calcium quantity does not translate into adequate calcium absorbed.</p>

          <h3>Vitamin D3 Metabolism Failures</h3>
          <p>Even with adequate UVB or dietary D3, the vitamin must be processed by the liver (to 25-hydroxyvitamin D3) and then activated by the kidney (to 1,25-dihydroxyvitamin D3, the hormonally active form, calcitriol). Liver disease, kidney disease (common in older reptiles, particularly those with a history of chronic dehydration or inappropriate diet), and certain medications interfere with this activation. A reptile with chronic kidney disease can develop hypocalcemia despite normal UVB and normal dietary calcium — the absorption machinery is intact but the activated D3 the gut needs is not being produced. This is uncommon in young animals and more common in geriatric chronic-disease cases.</p>

          <h3>Reproductive Demand</h3>
          <p>Eggshell formation pulls calcium out of circulation rapidly. A gravid female bearded dragon, leopard gecko, or veiled chameleon producing a large clutch can develop hypocalcemia within hours of crossing the depletion threshold. Veiled chameleon females are particularly vulnerable because they produce infertile clutches throughout their lives, without male contact, with no signal to the keeper that calcium demand is about to spike. Read the matching section in our <a href="/species/veiled-chameleon">veiled chameleon care guide</a>. The same physiology applies to gravid females of any oviparous species; daily calcium supplementation is appropriate during follicular development and active egg production.</p>

          <h3>Rapid Growth</h3>
          <p>Juveniles building skeleton are operating at the upper limit of what dietary calcium can supply. A juvenile bearded dragon doubling its body length in a few months requires calcium at a rate that does not tolerate any supplementation gaps. Juveniles should receive calcium at every feeding without exception. This is the population in which we most often see hypocalcemia presenting before clear radiographic MBD has developed — the demand simply outran the supply faster than the skeleton could buffer.</p>

          <h2>Clinical Signs by Severity</h2>
          <ul>
            <li><strong>Subclinical / early:</strong> no overt neuromuscular signs. Bloodwork may show ionized calcium at the low end of the reference range. The animal may have early MBD findings (slightly soft jaw on palpation, decreased grip strength) without obvious tremor. This is the population in which proactive husbandry correction prevents progression.</li>
            <li><strong>Mild:</strong> fine muscle tremors of the limbs at rest, twitching of individual toes or eyelids, reduced grip strength, generalized weakness. The animal can still walk but may be unsteady. Bloodwork shows low ionized calcium. Outpatient veterinary management is generally appropriate at this stage.</li>
            <li><strong>Moderate:</strong> sustained tremors, intermittent tetany (rigid muscle contractions of a limb or the body), difficulty righting from being placed on its back, inability to climb. The animal is in active neuromuscular distress. Same-day veterinary care, parenteral calcium.</li>
            <li><strong>Severe:</strong> generalized tetany, seizure-like episodes (paddling movements, opisthotonos — head and neck arching backward), inability to right itself, sometimes accompanied by respiratory difficulty if respiratory muscles are involved. Emergency referral. Parenteral calcium, often combined with hospitalization and supportive care.</li>
          </ul>

          <h2>Emergency Treatment — What the Vet Will Do</h2>
          <p>The veterinary protocol for acute hypocalcemia is well-described in the standard reference works of reptile medicine — Mader&apos;s <em>Reptile Medicine and Surgery</em> (Elsevier) and Divers and Stahl&apos;s <em>Reptile Medicine and Surgery in Clinical Practice</em> (Wiley) are the texts most commonly consulted by clinicians, and the ARAV peer journal (Journal of Herpetological Medicine and Surgery) publishes ongoing case reports and clinical reviews on the topic. The core protocol:</p>
          <ol>
            <li><strong>Confirm with bloodwork where possible:</strong> ionized calcium is the clinically meaningful measurement. Total calcium can be misleading in reptiles, particularly in gravid females, because of high circulating protein-bound calcium. Magnesium and phosphorus are commonly measured alongside, and albumin helps interpret the result.</li>
            <li><strong>Parenteral calcium:</strong> calcium gluconate is the standard preparation. Subcutaneous or intramuscular routes are used for mild-to-moderate cases. Intravenous administration is reserved for severe presentations and requires slow infusion — rapid IV calcium can produce cardiac arrhythmia.</li>
            <li><strong>Supportive care:</strong> warming to the species-appropriate preferred body temperature, subcutaneous fluids for hydration, minimal handling to avoid worsening tetanic contractions, a dark and quiet enclosure to reduce sensory stimulation. Pain management if fractures are present.</li>
            <li><strong>Address underlying drivers:</strong> in gravid females, the question of whether to support oviposition (calcium plus oxytocin under veterinary direction) or surgically remove retained eggs (salpingotomy) is decided based on clinical presentation, radiographs, and the timeline. Calcium injections alone do not resolve dystocia.</li>
            <li><strong>Transition to oral calcium:</strong> once the acute crisis is controlled, oral calcium supplementation continues at therapeutic doses while the husbandry corrections are implemented (UVB replacement, supplementation review, dietary adjustment). This phase runs for weeks to months depending on the depth of the original deficit.</li>
          </ol>
          <p>While arranging transport to the veterinary clinic: keep the animal warm at its species preferred temperature, handle minimally (handling during tetanic episodes risks worsening contractions and causing fractures in demineralized bone), keep the environment dark and quiet. Liquid calcium carbonate by mouth (one or two drops of an infant calcium preparation, gently delivered) is a reasonable supportive bridge but is not a substitute for the veterinary injection.</p>

          <h2>Prevention Protocol</h2>
          <p>Prevention is straightforward, and the protocol generalizes across most diurnal pet lizard species with species-specific adjustments to UVB intensity.</p>
          <ul>
            <li><strong>UVB:</strong> appropriate-strength T5 high-output linear bulb (Arcadia or Zoo Med ReptiSun product lines are the field-tested options most commonly cited in evidence-based husbandry references). Mount at the species-appropriate distance to deliver the target UV index at the basking surface — desert species typically need a UVI of 3 to 5, forest and crepuscular species 1 to 2. Verify with a Solarmeter 6.5 UV radiometer reading at the basking surface. Replace on a 12-month schedule by default.</li>
            <li><strong>Calcium supplementation:</strong> calcium carbonate without D3, lightly dusted on every feeder for juveniles and gravid females, every second feeder for stable non-breeding adults with reliable UVB. A multivitamin (containing D3) once or twice weekly. A free-choice calcium dish in the enclosure is appropriate for species that will use it.</li>
            <li><strong>Dietary calcium-to-phosphorus ratio:</strong> gut-load feeders for at least 24 hours before offering on a high-calcium diet. Rotate higher-calcium feeders (black-soldier-fly larvae) into the schedule. For herbivorous species, prioritize low-oxalate, high-calcium greens (collard, mustard, dandelion); avoid spinach, chard, and beet greens as staples because their oxalate content binds calcium.</li>
            <li><strong>Reproductive management:</strong> in females, provide an appropriate laying site at all times, increase supplementation during follicular development, and seek veterinary evaluation if signs of dystocia (straining without passing eggs, lethargy, abdominal distension) develop. See our <a href="/health/egg-binding">egg binding</a> page.</li>
            <li><strong>Routine bloodwork:</strong> for adult and senior reptiles, an annual or biannual workup including ionized calcium, phosphorus, and renal values identifies subclinical depletion and renal compromise before they progress to acute presentation.</li>
            <li><strong>Veterinary relationship:</strong> establish care with an ARAV-affiliated reptile veterinarian before you need one. Search the member directory at arav.org. A clinic that does not regularly see reptiles is not the right call at midnight.</li>
          </ul>

          <h2>When to Treat as an Emergency</h2>
          <p>Treat as a same-day emergency: any tremor, any tetanic episode, any seizure-like activity, any sudden inability to right itself, any flaccid paralysis or inability to support body weight, any gravid female showing weakness or straining without passing eggs. Do not wait to see if it gets worse. The window during which parenteral calcium can reverse the neuromuscular crisis is narrow, and reptiles can deteriorate rapidly once they cross the threshold.</p>

          <h2>Frequently Asked Questions</h2>
          <FAQAccordion items={FAQS.map(f => ({ question: f.question, answer: f.answer, answerText: f.answer }))} includeSchema={false} allowMultiple />
        </div>
      </ArticleLayout>
    </>
  )
}
