#!/usr/bin/env bash
# Publish refreshed page counts without pushing to main.
# Ruleset 24478557 requires a pull request and rejects this workflow's
# token on main. Counts land on bot/dashboard-sync, in one open PR, and
# in the dashboard-artifact/ directory uploaded by the workflow.
set -euo pipefail

BRANCH=bot/dashboard-sync
MSG="chore(dashboard): sync page counts [skip dashboard]"
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

artifact="$ROOT/dashboard-artifact"
mkdir -p "$artifact"
cp DASHBOARD.md "$artifact/DASHBOARD.md"
cp README.md "$artifact/README.md"

if [[ -z "$(git status --porcelain -- DASHBOARD.md README.md)" ]]; then
  echo "Page counts already match this checkout."
  exit 0
fi

git checkout -- DASHBOARD.md README.md
git config user.name "carloos-stabilizer"
git config user.email "stabilizer@carloos.local"

git fetch origin main
if git ls-remote --exit-code --heads origin "$BRANCH" >/dev/null 2>&1; then
  git fetch origin "$BRANCH"
  git checkout -B "$BRANCH" "origin/$BRANCH"
  git merge origin/main -m "merge main into dashboard sync [skip dashboard]" -X ours
else
  git checkout -B "$BRANCH" origin/main
fi

cp "$artifact/DASHBOARD.md" DASHBOARD.md
cp "$artifact/README.md" README.md
git add DASHBOARD.md README.md
if git diff --cached --quiet; then
  echo "Bot branch already has these counts."
else
  git commit -m "$MSG"
  git push origin "HEAD:refs/heads/$BRANCH"
fi

existing="$(gh pr list --head "$BRANCH" --base main --state open --json number --jq '.[0].number' || true)"
if [[ -n "${existing}" && "${existing}" != "null" ]]; then
  echo "Updated open dashboard PR #${existing}"
  exit 0
fi

# This repo does not allow GitHub Actions to open pull requests. The branch
# and the workflow artifact are the record when PR creation is refused.
if gh pr create --base main --head "$BRANCH" \
  --title "Sync dashboard page counts" \
  --body "$(cat <<'EOF'
Page counts regenerated by dashboard-sync.

Ruleset 24478557 blocks a direct push to main, including this workflow's token. This is the one bot pull request for those counts. Later syncs push onto this same branch.

The workflow also uploads `dashboard-pagecounts` as a run artifact.
EOF
)"; then
  echo "Opened the dashboard pull request."
else
  echo "Counts are on ${BRANCH} and in the dashboard-pagecounts artifact. Actions is not permitted to open the pull request."
fi
