#!/usr/bin/env node
/**
 * Polish-pass audit (Carlo's 2026-06-01 launch-quality-polish directive).
 *
 * For one site, surfaces:
 *   - Thin pages (low word count + few sections)
 *   - Orphan pages (no inbound internal link from any TSX in the site)
 *   - Duplicate titles
 *   - Missing breadcrumbs (no <Breadcrumb> component AND no inline aria-label nav)
 *   - Missing schema (no Article/Medical/FAQ buildXxxSchema call)
 *
 * Usage:
 *   node scripts/ci/polish-audit.mjs <site>
 *   node scripts/ci/polish-audit.mjs dog-com
 *
 * Output:
 *   Markdown report on stdout, suitable for piping to an ops/handoffs file.
 *
 * Not a CI gate — informational only. Cohort-5 polish passes consume it.
 */

import fs from 'node:fs'
import path from 'node:path'

const SITE = process.argv[2]
if (!SITE) {
  console.error('usage: node scripts/ci/polish-audit.mjs <site>')
  process.exit(2)
}

const APP_DIR = `apps/${SITE}/src/app`
const SRC_DIR = `apps/${SITE}/src`
const THIN_WORDS = 200
const THIN_H2S = 2

if (!fs.existsSync(APP_DIR)) {
  console.error(`no app dir at ${APP_DIR}`)
  process.exit(2)
}

function walk(dir, ext, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (['node_modules', '.next', '.turbo'].includes(e.name)) continue
    const p = path.join(dir, e.name)
    if (e.isDirectory()) walk(p, ext, out)
    else if (typeof ext === 'string' ? e.name === ext : ext.test(e.name)) out.push(p)
  }
  return out
}

const pages = walk(APP_DIR, 'page.tsx')

const routes = []
for (const p of pages) {
  const rel = p.slice(APP_DIR.length).replace(/\/page\.tsx$/, '') || '/'
  const route = rel.replace(/\/\([^)]+\)(?=\/|$)/g, '') || '/'
  const isDynamic = /\[/.test(route)
  const src = fs.readFileSync(p, 'utf8')

  const titleMatch = src.match(/title:\s*['"`]([^'"`]+)['"`]/) ||
                     src.match(/title:\s*`([^`]+)`/)
  const title = titleMatch ? titleMatch[1] : null

  // Strip noise for word count
  let body = src
    .replace(/import[^\n]+\n/g, '')
    .replace(/className=['"`][^'"`]+['"`]/g, '')
    .replace(/style=\{[^}]+\}/g, '')
    .replace(/[#a-zA-Z]+-\d+/g, '')
  const words = body.split(/\s+/).filter(w => /[a-zA-Z]/.test(w) && w.length > 1).length

  const h2 = (src.match(/<h2/g) || []).length
  const h3 = (src.match(/<h3/g) || []).length

  // Breadcrumb: shared component OR inline aria-label nav OR breadcrumbs= prop
  const hasBreadcrumb =
    /breadcrumbs=/.test(src) ||
    /<Breadcrumb /.test(src) ||
    /aria-label=['"]Breadcrumb['"]/.test(src)

  // Schema: any structured-data hook
  const hasArticleSchema = /buildArticleSchema/.test(src)
  const hasMedSchema = /buildMedicalWebPageSchema/.test(src)
  const hasFaqSchema = /buildFAQSchema|FAQAccordion/.test(src)
  const hasProductSchema = /buildProductSchema/.test(src)
  const hasHowToSchema = /buildHowToSchema/.test(src)
  const hasAnySchema = hasArticleSchema || hasMedSchema || hasFaqSchema || hasProductSchema || hasHowToSchema

  routes.push({
    file: p,
    route,
    isDynamic,
    title,
    words,
    h2,
    h3,
    hasBreadcrumb,
    hasAnySchema,
  })
}

// Collect inbound href references across the whole site src
const allHrefs = new Set()
for (const f of walk(SRC_DIR, /\.tsx$/)) {
  const src = fs.readFileSync(f, 'utf8')
  for (const m of src.matchAll(/href[=:]\s*['"`]([^'"`${}]+)['"`]/g)) {
    if (m[1].startsWith('/')) {
      const clean = m[1].split('?')[0].split('#')[0].replace(/\/$/, '') || '/'
      allHrefs.add(clean)
    }
  }
}

// Findings
const thin = routes
  .filter(r => !r.isDynamic && r.route !== '/' && r.words < THIN_WORDS && r.h2 < THIN_H2S)
  .sort((a, b) => a.words - b.words)

const orphans = routes
  .filter(r => !r.isDynamic && r.route !== '/' && !allHrefs.has(r.route))
  .sort((a, b) => a.route.localeCompare(b.route))

const titleMap = new Map()
for (const r of routes) {
  if (!r.title) continue
  if (!titleMap.has(r.title)) titleMap.set(r.title, [])
  titleMap.get(r.title).push(r.route)
}
const dupTitles = [...titleMap.entries()].filter(([, v]) => v.length > 1)

const noBreadcrumb = routes
  .filter(r => !r.isDynamic && r.route !== '/' && !r.hasBreadcrumb)
  .sort((a, b) => a.route.localeCompare(b.route))

const noSchema = routes
  .filter(r => !r.isDynamic && r.route !== '/' && !r.hasAnySchema)
  .sort((a, b) => a.route.localeCompare(b.route))

// Output: markdown report
const out = []
out.push(`# Polish audit — ${SITE}`)
out.push('')
out.push(`_Auto-generated by \`scripts/ci/polish-audit.mjs ${SITE}\`._`)
out.push('')
out.push(`Total page.tsx files (incl. dynamic): **${routes.length}**`)
out.push('')

out.push('## Thin pages')
out.push(`Threshold: < ${THIN_WORDS} words AND < ${THIN_H2S} h2 sections.`)
out.push(`Count: **${thin.length}**`)
if (thin.length) {
  out.push('')
  out.push('| Route | Words | H2 | File |')
  out.push('|---|---|---|---|')
  for (const r of thin) out.push(`| \`${r.route}\` | ${r.words} | ${r.h2} | \`${r.file}\` |`)
}
out.push('')

out.push('## Orphans (no inbound internal link from any TSX in the site)')
out.push(`Count: **${orphans.length}**`)
if (orphans.length) {
  out.push('')
  for (const r of orphans) out.push(`- \`${r.route}\` (file: \`${r.file}\`)`)
}
out.push('')

out.push('## Duplicate titles')
out.push(`Count: **${dupTitles.length}**`)
if (dupTitles.length) {
  out.push('')
  for (const [title, rs] of dupTitles) {
    out.push(`- "${title}"`)
    for (const r of rs) out.push(`  - \`${r}\``)
  }
}
out.push('')

out.push('## Missing breadcrumbs')
out.push('Detection: no `<Breadcrumb>` component AND no `breadcrumbs=` prop AND no `aria-label="Breadcrumb"` inline nav.')
out.push(`Count: **${noBreadcrumb.length}**`)
if (noBreadcrumb.length) {
  out.push('')
  for (const r of noBreadcrumb) out.push(`- \`${r.route}\``)
}
out.push('')

out.push('## Missing schema')
out.push('Detection: no `buildArticleSchema` / `buildMedicalWebPageSchema` / `buildFAQSchema` / `FAQAccordion` / `buildProductSchema` / `buildHowToSchema` reference.')
out.push(`Count: **${noSchema.length}**`)
if (noSchema.length) {
  out.push('')
  for (const r of noSchema) out.push(`- \`${r.route}\``)
}
out.push('')

console.log(out.join('\n'))
