#!/usr/bin/env node
/**
 * CI check: sitemap drift.
 *
 * Every app's src/app/sitemap.ts is a hardcoded url list (regenerated by
 * scripts/regenerate-sitemaps.mjs, but only when someone remembers to run
 * it). New pages silently drift out of the sitemap — an indexing-efficiency
 * leak. This gate walks each app's src/app/ directory, enumerates the static
 * indexable page.tsx routes, and fails if any of them is missing from that
 * app's sitemap.ts.
 *
 * Route enumeration rules (mirrors scripts/regenerate-sitemaps.mjs):
 *   - route groups `(name)/` are stripped from the URL path
 *   - dynamic segments `[param]` are skipped entirely (dynamic routes are
 *     enumerated separately via extraRoutes in regenerate-sitemaps.mjs and
 *     are deliberately out of scope here)
 *   - api/, admin/, dashboard/, _private and dot-folders are skipped
 *   - pages whose source sets noindex (`noIndex: true`, `index: false`, or
 *     a 'noindex' robots string) are skipped — not indexable, must NOT be
 *     in the sitemap
 *   - redirect stubs (next/navigation redirect() pages with no
 *     buildMetadata) are skipped — they 308 to a canonical URL
 *
 * This gate only checks ROUTE → SITEMAP presence (drift). It does not check
 * the reverse (sitemap entries for dynamic/[slug] routes are expected and
 * fine), and it never edits anything.
 *
 * Exit code: 0 if every indexable static route is in its sitemap, 1 otherwise.
 */
import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = process.cwd()

// All 10 production sites → canonical domain (must match the sitemap host).
const APPS = {
  'dog-com': 'dog.com',
  'fish-com': 'fish.com',
  'lizard-com': 'lizard.com',
  'saddle-com': 'saddle.com',
  'vets-co': 'vets.co',
  'horses-com': 'horses.com',
  'petfood-com': 'petfood.com',
  'petfoods-com': 'petfoods.com',
  'ferret-com': 'ferret.com',
  'ferrets-com': 'ferrets.com',
}

// Deliberate per-app exclusions: static routes that exist as page.tsx and are
// not noindexed in-source, but must stay OUT of the sitemap anyway. Keep this
// list small and always say why.
const IGNORE = {
  // (empty — every current static indexable route belongs in its sitemap)
}

// Directory names that never produce indexable sitemap routes.
const SKIP_DIRS = new Set(['api', 'admin', 'dashboard', 'node_modules', '.next', '.turbo'])

function isNoIndex(src) {
  // buildMetadata({ noIndex: true }) — SEOHead.tsx maps this to
  // robots: { index: false, follow: false }
  if (/\bnoIndex\s*:\s*true\b/.test(src)) return true
  // Raw Next metadata: robots: { index: false } / 'noindex' string forms
  if (/\bindex\s*:\s*false\b/.test(src)) return true
  if (/['"`][^'"`]*noindex[^'"`]*['"`]/i.test(src)) return true
  return false
}

function isRedirectStub(src) {
  return (
    /from\s+['"]next\/navigation['"]/.test(src) &&
    /\bredirect\(/.test(src) &&
    !/buildMetadata\(/.test(src)
  )
}

function staticRoutesFor(app) {
  const appDir = join(ROOT, 'apps', app, 'src/app')
  const routes = []

  function walk(dir, prefix) {
    let entries
    try {
      entries = readdirSync(dir, { withFileTypes: true })
    } catch {
      return
    }
    for (const entry of entries) {
      const path = join(dir, entry.name)
      if (entry.isDirectory()) {
        if (
          entry.name.startsWith('_') ||
          entry.name.startsWith('.') ||
          entry.name.includes('[') || // dynamic segment — out of scope
          SKIP_DIRS.has(entry.name)
        ) {
          continue
        }
        // Route groups `(name)` organize code only; strip from URL path.
        const isRouteGroup = entry.name.startsWith('(') && entry.name.endsWith(')')
        walk(path, isRouteGroup ? prefix : `${prefix}/${entry.name}`)
      } else if (/^page\.(tsx|ts|jsx|js)$/.test(entry.name)) {
        let src = ''
        try {
          src = readFileSync(path, 'utf8')
        } catch {}
        if (isNoIndex(src)) continue
        if (isRedirectStub(src)) continue
        routes.push({ route: prefix === '' ? '/' : prefix, file: path.replace(ROOT + '/', '') })
      }
    }
  }

  walk(appDir, '')
  return routes.sort((a, b) => a.route.localeCompare(b.route))
}

function sitemapPathsFor(app, domain) {
  const sitemapFile = join(ROOT, 'apps', app, 'src/app/sitemap.ts')
  let src
  try {
    src = readFileSync(sitemapFile, 'utf8')
  } catch {
    return null // missing sitemap.ts entirely — reported as its own failure
  }
  const paths = new Set()
  const re = /url\s*:\s*['"`]([^'"`]+)['"`]/g
  let m
  while ((m = re.exec(src)) !== null) {
    let url = m[1]
    // Tolerate template literals like `${baseUrl}/foo` by stripping the
    // interpolation; raw urls are https://<domain><path>.
    url = url.replace(/\$\{[^}]+\}/g, '')
    url = url.replace(new RegExp(`^https?://(www\\.)?${domain.replace('.', '\\.')}`), '')
    const path = (url.split('?')[0].split('#')[0].replace(/\/$/, '') || '/')
    paths.add(path.startsWith('/') ? path : `/${path}`)
  }
  return paths
}

let totalMissing = 0
const report = []

for (const [app, domain] of Object.entries(APPS)) {
  const ignored = new Set(IGNORE[app] || [])
  const routes = staticRoutesFor(app).filter((r) => !ignored.has(r.route))
  const sitemapPaths = sitemapPathsFor(app, domain)

  if (sitemapPaths === null) {
    totalMissing += routes.length
    report.push(`\n## ${app}: NO sitemap.ts found (apps/${app}/src/app/sitemap.ts)`)
    continue
  }

  const missing = routes.filter((r) => !sitemapPaths.has(r.route))
  if (missing.length > 0) {
    totalMissing += missing.length
    report.push(`\n## ${app}: ${missing.length} indexable route${missing.length === 1 ? '' : 's'} missing from sitemap.ts`)
    for (const r of missing) {
      report.push(`  ${r.route}  (${r.file})`)
    }
  } else {
    report.push(`## ${app}: clean (${routes.length} static indexable routes, all in sitemap)`)
  }
}

console.log(report.join('\n'))

if (totalMissing > 0) {
  console.error(`\nFAIL: ${totalMissing} indexable static route(s) missing from sitemap.ts.`)
  console.error('Add the route to the app sitemap (or run node scripts/regenerate-sitemaps.mjs),')
  console.error('or — if the page is deliberately out — noindex it or add it to IGNORE here with a reason.')
  process.exit(1)
} else {
  console.log(`\nPASS: every indexable static route is present in its sitemap across all ${Object.keys(APPS).length} sites.`)
  process.exit(0)
}
