import { MetadataRoute } from 'next'
import { Conditions, RESERVED_HEALTH_SLUGS } from '../data/conditions'
import { HusbandryTopics } from '../data/husbandry-topics'

/**
 * Auto-generated by scripts/regenerate-sitemaps.mjs.
 * To refresh after adding/removing pages, re-run:
 *   node scripts/regenerate-sitemaps.mjs
 *
 * Manual augmentation: the auto-regen script skips dynamic [slug] routes, so
 * the 15 reptile-condition pages built at /health/<slug> and the 8 husbandry
 * deep-dive pages built at /husbandry/<slug> are appended below from their
 * respective data catalogs.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()

  const dynamicConditionEntries: MetadataRoute.Sitemap = Conditions.filter(
    (c) => !RESERVED_HEALTH_SLUGS.has(c.slug),
  ).map((c) => ({
    url: `https://lizard.com/health/${c.slug}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    priority: 0.7,
  }))

  const husbandryEntries: MetadataRoute.Sitemap = HusbandryTopics.map((t) => ({
    url: `https://lizard.com/husbandry/${t.slug}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    priority: 0.7,
  }))

  return [
    { url: 'https://lizard.com', lastModified: now, changeFrequency: 'daily', priority: 1.00 },
    { url: 'https://lizard.com/editorial-standards', lastModified: now, changeFrequency: 'yearly', priority: 0.30 },
    { url: 'https://lizard.com/first-year-care-schedule', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://lizard.com/health', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://lizard.com/health/dehydration-reptiles', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/dysecdysis', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/egg-binding', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/hypocalcemia', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/metabolic-bone-disease', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/parasites', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/parasites-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/reptile-feeding-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/respiratory-infection', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/salmonella-prevention', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/sick-reptile-signs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/stomatitis', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/thermal-burns', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/vitamin-a-deficiency', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/husbandry', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://lizard.com/legal/affiliate-disclosure', lastModified: now, changeFrequency: 'yearly', priority: 0.20 },
    { url: 'https://lizard.com/legal/privacy-policy', lastModified: now, changeFrequency: 'yearly', priority: 0.20 },
    { url: 'https://lizard.com/legal/terms', lastModified: now, changeFrequency: 'yearly', priority: 0.20 },
    { url: 'https://lizard.com/reviews', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://lizard.com/reviews/best-bioactive-substrates', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/reviews/best-reptile-terrariums', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/reviews/best-thermometers-hygrometers', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/reviews/best-thermostats', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/reviews/best-uvb-bulbs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/setup', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://lizard.com/setup/bioactive-setup', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/setup/humidity-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/setup/lighting-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/setup/substrate-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/setup/temperature-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/setup/uvb-lighting-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://lizard.com/species/ball-python', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/ball-python-morphs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/bearded-dragon', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/blue-tongued-skink', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/boa-constrictor', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/corn-snake', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/crested-gecko', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/day-gecko', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/frilled-dragon', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/gargoyle-gecko', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/leopard-gecko', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/mossy-leaf-tail-gecko', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/panther-chameleon', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/russian-tortoise', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/savannah-monitor', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/sulcata-tortoise', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/tegu', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/tokay-gecko', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/uromastyx', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/veiled-chameleon', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    ...dynamicConditionEntries,
    ...husbandryEntries,
  ]
}
