import { MetadataRoute } from 'next'

/**
 * Auto-generated by scripts/regenerate-sitemaps.mjs.
 * To refresh after adding/removing pages, re-run:
 *   node scripts/regenerate-sitemaps.mjs
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()

  return [
    { url: 'https://lizard.com', lastModified: now, changeFrequency: 'daily', priority: 1.00 },
    { url: 'https://lizard.com/editorial-standards', lastModified: now, changeFrequency: 'yearly', priority: 0.30 },
    { url: 'https://lizard.com/first-year-care-schedule', lastModified: now, changeFrequency: 'monthly', priority: 0.90 },
    { url: 'https://lizard.com/health/dehydration-reptiles', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/dysecdysis', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/egg-binding', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/hypocalcemia', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/metabolic-bone-disease', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/parasites', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/parasites-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/reptile-feeding-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/respiratory-infection', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/salmonella-prevention', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/sick-reptile-signs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/stomatitis', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/thermal-burns', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/health/vitamin-a-deficiency', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/legal/affiliate-disclosure', lastModified: now, changeFrequency: 'yearly', priority: 0.20 },
    { url: 'https://lizard.com/legal/privacy-policy', lastModified: now, changeFrequency: 'yearly', priority: 0.20 },
    { url: 'https://lizard.com/legal/terms', lastModified: now, changeFrequency: 'yearly', priority: 0.20 },
    { url: 'https://lizard.com/reviews', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://lizard.com/reviews/best-bioactive-substrates', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/reviews/best-reptile-terrariums', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/reviews/best-thermometers-hygrometers', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/reviews/best-thermostats', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/reviews/best-uvb-bulbs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/setup', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://lizard.com/setup/bioactive-setup', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/setup/humidity-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/setup/lighting-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/setup/substrate-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/setup/temperature-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/setup/uvb-lighting-guide', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://lizard.com/species/ball-python', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/ball-python-morphs', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/bearded-dragon', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/blue-tongued-skink', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/boa-constrictor', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/corn-snake', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/crested-gecko', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/day-gecko', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/frilled-dragon', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/gargoyle-gecko', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/leopard-gecko', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/mossy-leaf-tail-gecko', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/panther-chameleon', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/russian-tortoise', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/savannah-monitor', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/sulcata-tortoise', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/tegu', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/tokay-gecko', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/uromastyx', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://lizard.com/species/veiled-chameleon', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
  ]
}
