/**
 * Husbandry hub page — Lizard.com
 *
 * Lists all 8 husbandry deep-dive topics generated by
 * /husbandry/[slug]/page.tsx. Foundational keeper-education tree that funnels
 * into species and equipment pages.
 */

import type { Metadata } from 'next'
import Link from 'next/link'
import { buildMetadata, EmailCapture } from '@carloOS/ui'
import { HusbandryTopics } from '../../data/husbandry-topics'

export const metadata: Metadata = buildMetadata({
  siteId: 'lizard-com',
  title: 'Reptile Husbandry Guides — UVB, Temp, Humidity | Lizard.com',
  description:
    'Foundational reptile husbandry guides: UVB lighting, basking temps, humidity, substrate, vivarium sizing, supplementation, quarantine, and thermoregulation.',
  path: '/husbandry',
})

export default function HusbandryHubPage() {
  return (
    <>
      <div
        className="relative z-10 px-container sm:px-container-sm py-16"
        style={{ background: 'linear-gradient(135deg, #0D1A0D, #080C08)' }}
      >
        <div className="flex items-center gap-2.5 mb-5">
          <span className="w-6 h-0.5 bg-brand-primary" />
          <span className="text-2xs font-bold tracking-eyebrow uppercase text-brand-primary">
            Reptile Husbandry
          </span>
        </div>
        <h1
          className="font-display font-bold text-brand-white tracking-tight leading-tight mb-4"
          style={{ fontSize: 'clamp(28px, 5vw, 52px)' }}
        >
          Reptile Husbandry Deep-Dives
        </h1>
        <p
          className="text-lg font-light leading-relaxed max-w-2xl"
          style={{ color: 'rgba(238,240,228,0.55)' }}
        >
          Eight foundational husbandry topics — UVB lighting, basking temperatures, humidity
          management, substrate selection, vivarium sizing, calcium + D3 supplementation, quarantine
          protocol, and thermoregulation. Sourced from Mader&rsquo;s RAMS, the Journal of
          Herpetological Medicine and Surgery, ARAV continuing-education materials, and peer-
          reviewed Reptiles Magazine content.
        </p>
      </div>

      <div className="relative z-10 px-container sm:px-container-sm py-14">
        <div className="grid sm:grid-cols-2 gap-4 max-w-content-wide mx-auto">
          {HusbandryTopics.map((t) => (
            <Link
              key={t.slug}
              href={`/husbandry/${t.slug}`}
              className="block rounded-lg p-5 no-underline hover:-translate-y-1 transition-all duration-200"
              style={{
                background: 'rgba(255,255,255,0.03)',
                border: '1px solid rgba(255,255,255,0.07)',
              }}
            >
              <div className="flex items-start gap-3">
                <div
                  style={{
                    fontFamily: 'var(--font-mono)',
                    fontSize: '11px',
                    fontWeight: 700,
                    color: 'var(--brand-primary)',
                    background: 'rgba(122,181,42,0.12)',
                    border: '1px solid rgba(122,181,42,0.25)',
                    padding: '4px 8px',
                    borderRadius: '4px',
                    letterSpacing: '0.06em',
                    flexShrink: 0,
                  }}
                >
                  {t.icon}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="text-2xs font-bold tracking-eyebrow uppercase text-brand-primary mb-2">
                    {t.category}
                  </div>
                  <div className="font-display font-bold text-brand-white text-base mb-1.5">
                    {t.topicName}
                  </div>
                  <div className="text-xs" style={{ color: 'rgba(238,240,228,0.45)' }}>
                    {t.shortDescription}
                  </div>
                </div>
              </div>
            </Link>
          ))}
        </div>
      </div>

      <div
        className="relative z-10 px-container sm:px-container-sm py-12"
        style={{ background: '#0D1A0D', borderTop: '1px solid rgba(122,181,42,0.1)' }}
      >
        <EmailCapture
          variant="inline"
          siteId="lizard-com"
          ctaText="Subscribe Free"
          source="husbandry-hub"
        />
      </div>

      {/* agent1-browse-all-start */}
      <section className="border-t border-brand-border bg-brand-surface px-container sm:px-container-sm py-10">
        <h2 className="font-display font-bold text-brand-dark text-lg mb-4">
          All Husbandry Guides
        </h2>
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-x-6 gap-y-2">
          {HusbandryTopics.map((t) => (
            <Link
              key={t.slug}
              href={`/husbandry/${t.slug}`}
              className="text-sm text-brand-primary no-underline hover:underline"
            >
              {t.topicName}
            </Link>
          ))}
        </div>
      </section>
      {/* agent1-browse-all-end */}
    </>
  )
}
