import { MetadataRoute } from 'next'

/**
 * Auto-generated by scripts/regenerate-sitemaps.mjs.
 * To refresh after adding/removing pages, re-run:
 *   node scripts/regenerate-sitemaps.mjs
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()

  return [
    { url: 'https://ferret.com', lastModified: now, changeFrequency: 'daily', priority: 1.00 },
    { url: 'https://ferret.com/behavior/training-and-bonding', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://ferret.com/care/bathing-and-grooming', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://ferret.com/care/cage-setup', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://ferret.com/care/diet-basics', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://ferret.com/care/exercise-and-enrichment', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://ferret.com/care/litter-training', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://ferret.com/care/toxic-foods', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://ferret.com/disclosure', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://ferret.com/ferret-starter-kit', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://ferret.com/first-year-schedule', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://ferret.com/health/adrenal-disease', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://ferret.com/health/aging-ferret-care', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://ferret.com/health/dental-disease', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://ferret.com/health/insulinoma', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://ferret.com/health/lymphoma', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://ferret.com/health/vaccinations', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://ferret.com/health/vet-visit-prep', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://ferret.com/tools', lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: 'https://ferret.com/tools/food-evaluator', lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
  ]
}
