import type { Metadata } from 'next'
import { buildMetadata, ArticleLayout, EmailCapture, RelatedLinks } from '@carloOS/ui'
import { buildArticleSchema } from '@carloOS/ui'

export const metadata: Metadata = buildMetadata({ siteId: 'lizard-com', title: "Nile Monitor Care Guide — Advanced Large Monitor | Lizard.com", description: "Nile monitors are large, fast, defensive semi-aquatic monitors for experts only. Room-sized enclosures, intense heat, water, and honest expectations.", path: "/species/nile-monitor", type: 'article' })
const schema = buildArticleSchema({ siteId: 'lizard-com', title: "Nile Monitor Care Guide", description: "Enclosure scale, heat, water, diet, temperament, and realistic care for Varanus niloticus, the Nile monitor.", url: "https://lizard.com/species/nile-monitor", imageUrl: '', authorName: 'Lizard.com Editorial', publishedAt: '2026-06-01T00:00:00Z', modifiedAt: '2026-06-01T00:00:00Z' })

export default function SpeciesNileMonitorPage() {
  return (
    <ArticleLayout siteId="lizard-com"
      hero={{ title: "Nile Monitor Care Guide", subtitle: "Varanus niloticus is a large, powerful, semi-aquatic African monitor reaching 4 to 6 feet. Fast, intelligent, and often defensive, the Nile monitor is an advanced-only species that needs a room-sized custom enclosure, intense heat and UVB, a large water feature, and a keeper with realistic expectations: most do not become tame, and they are a serious safety and space commitment.", category: "Species Guide — Advanced", authorName: 'Lizard.com Editorial', authorAvatar: '🦎', publishedAt: 'June 2026', readTime: "11 min" }}
      breadcrumbs={[{ name: "Home", href: "/" }, { name: "Species", href: "/species" }, { name: "Nile Monitor", href: "/species/nile-monitor" }]}
      schema={schema}
      sidebar={<>
        <div style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '12px', padding: '16px' }}>
          <div style={{ fontSize: '11px', fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: 'rgba(238,240,228,0.4)', marginBottom: '12px' }}>{"Quick Stats"}</div>
          {[["Scientific name", "Varanus niloticus"], ["Difficulty", "Advanced (expert only)"], ["Adult size", "4-6 ft"], ["Enclosure (adult)", "8x4x4 ft minimum, larger preferred"], ["Basking surface", "120-140 F"], ["Cool side", "80-85 F"], ["UVB", "Required high output"], ["Water", "Large soak/swim feature"], ["Diet", "Carnivore"], ["Lifespan", "10-20 years"]].map(([k, v]) => (
            <div key={k} style={{ display: 'flex', justifyContent: 'space-between', padding: '6px 0', borderBottom: '1px solid rgba(255,255,255,0.06)', fontSize: '12px' }}>
              <span style={{ color: 'rgba(238,240,228,0.45)' }}>{k}</span>
              <span style={{ color: 'var(--brand-white)', fontWeight: 600, textAlign: 'right', maxWidth: '55%' }}>{v}</span>
            </div>
          ))}
        </div>
        <RelatedLinks title={"Related Guides"} links={[{ label: "Savannah Monitor Care", href: "/species/savannah-monitor" }, { label: "Argentine Tegu Care", href: "/species/argentine-black-and-white-tegu" }, { label: "Beginner vs Advanced Species", href: "/species/beginner-vs-advanced-reptiles" }, { label: "Reptiles That Do Not Need UVB", href: "/species/reptiles-that-dont-need-uvb" }]} />
        <EmailCapture variant="sidebar" siteId="lizard-com" title="Free Care Sheets" subtitle="Species guides for subscribers." source={"lizard-species-nile-monitor"} ctaText="Download Free" />
      </>}
    >
      <div className="carloOS-article">
          <p>{"The Nile monitor is one of the most challenging lizards in the pet trade and is recommended only for experienced keepers who fully understand the commitment. In the wild it is a fast, semi-aquatic predator of rivers and lakes across much of Africa; in captivity it remains powerful, alert, and frequently defensive, with sharp claws, a strong bite, and a punishing tail whip. Cheap, widely sold hatchlings give a false impression of an easy pet; the adult is a large dangerous animal requiring a dedicated room-scale habitat. This care sheet emphasizes realistic expectations as much as parameters."}</p>
          <h2>{"A Realistic Temperament Warning"}</h2>

          <h2>{"Enclosure"}</h2>
          <p>{"An adult Nile monitor needs a custom-built enclosure of at least 8 by 4 by 4 feet, and many keepers build substantially larger (room-sized) habitats. The cage must contain deep burrowable substrate, a large heat-resistant basking platform, robust climbing structure, and a water feature big enough for this semi-aquatic species to fully submerge and swim. Hatchlings grow rapidly and outpace temporary enclosures within months, so the adult habitat should be planned from the start."}</p>
          <h2>{"Heat, UVB, and Water"}</h2>
          <ul>
            <li>{"Basking surface: 120-140 F, generated by a cluster of halogen floods over a sturdy platform"}</li>
            <li>{"Cool side: 80-85 F"}</li>
            <li>{"UVB: required high-output linear T5 across the basking zone"}</li>
            <li>{"Water: a large, clean, heated soak/swim area is essential for a semi-aquatic species"}</li>
            <li>{"Humidity: moderate to high, supported by the water feature and substrate"}</li>
          </ul>
          <h2>{"Diet"}</h2>
          <p>{"Nile monitors are carnivores. A varied captive diet centers on whole prey such as appropriately sized rodents, alongside insects, and other whole-animal items that supply balanced calcium and nutrients. Avoid a diet of lean muscle meat, which lacks calcium and drives metabolic disease. Feed growing juveniles frequently and adults less often, monitoring body condition since captive monitors readily become obese from overfeeding and underexercise."}</p>
          <h2>{"Handling and Safety"}</h2>
          <p>{"Handle only with full awareness of the animal’s strength and weapons, and never in a way that puts your face or others (especially children) at risk. Use protective equipment as needed and have an experienced second person for any procedure on a large adult. Routine veterinary care for an animal this size requires an exotics vet equipped for large reptiles."}</p>
          <h2>{"Common Health Concerns"}</h2>
          <ul>
            <li>{"Obesity from overfeeding and inadequate space to move"}</li>
            <li>{"Metabolic bone disease in juveniles from poor calcium or UVB"}</li>
            <li>{"Respiratory and skin infections from incorrect temperature or unclean water"}</li>
            <li>{"Stress-related disease and aggression from undersized housing"}</li>
            <li>{"Thermal burns from unguarded high-wattage basking equipment"}</li>
          </ul>
          <p>{"Establish care with an ARAV-member exotics veterinarian experienced with large monitors before acquiring one, and reconsider the purchase honestly if you cannot meet the space, heat, water, and safety demands."}</p>
          <h2>{"Sources & Further Reading"}</h2>
          <ul>
            <li>{"Mader, D. R. Reptile Medicine and Surgery (Elsevier)."}</li>
            <li>{"Bennett, D., monitor lizard (Varanus) husbandry and ecology references."}</li>
            <li>{"Association of Reptilian and Amphibian Veterinarians (ARAV), arav.org."}</li>
          </ul>
        <div style={{ background: 'var(--brand-surface, #1a1f2b)', border: '1px solid var(--brand-border, #2d3548)', borderRadius: '10px', padding: '20px', margin: '32px 0 24px' }}>
          <div style={{ fontSize: '13px', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.05em', color: 'var(--brand-text-mid, #8a96ad)', marginBottom: '8px' }}>Nile Monitor — Setup Equipment</div>
          <p style={{ fontSize: '14px', margin: '0 0 12px', color: 'var(--brand-text-mid, #8a96ad)', lineHeight: 1.55 }}>Browse large custom enclosures, high-output UVB, halogen flood basking bulbs, thermostats, and deep substrate sized for Nile monitor care. Lizard.com earns an affiliate commission on qualifying purchases — at no extra cost to you. Commission does not influence editorial content above.</p>
          <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
            <a href="/go/amazon-brand/nile%20monitor%20enclosure%20setup?s=species-nile-monitor" rel="sponsored noopener" style={{ display: 'inline-block', padding: '9px 16px', background: 'var(--brand-dark, #232f3e)', color: 'white', fontSize: '13px', fontWeight: 700, textDecoration: 'none', borderRadius: '6px' }}>Shop Nile Monitor Setup on Amazon →</a>
            <a href="/go/chewy-brand/nile%20monitor%20enclosure%20setup?s=species-nile-monitor" rel="sponsored noopener" style={{ display: 'inline-block', padding: '9px 16px', background: 'var(--brand-primary, #7bc25c)', color: 'white', fontSize: '13px', fontWeight: 700, textDecoration: 'none', borderRadius: '6px' }}>Shop on Chewy →</a>
          </div>
        </div>
      </div>
    </ArticleLayout>
  )
}
