#!/usr/bin/env node
// Auto-sync page counts in DASHBOARD.md and README.md.
// Counts page.tsx files under apps/*/src/app and writes them into marked sections.
// Zero dependencies — runs with bare node.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
// All 10 production sites — extended from the original Tier-1 5 to give Carlo
// a portfolio-wide page count post-mega-wave (~166 net new pages 2026-05-31)
// and the overnight 2026-06-01 SEO/GEO hardening pass.
const APPS = [
  'dog-com',
  'fish-com',
  'lizard-com',
  'saddle-com',
  'vets-co',
  'horses-com',
  'petfood-com',
  'petfoods-com',
  'ferret-com',
  'ferrets-com',
];
const DOMAIN = {
  'dog-com': 'dog.com',
  'fish-com': 'fish.com',
  'lizard-com': 'lizard.com',
  'saddle-com': 'saddle.com',
  'vets-co': 'vets.co',
  'horses-com': 'horses.com',
  'petfood-com': 'petfood.com',
  'petfoods-com': 'petfoods.com',
  'ferret-com': 'ferret.com',
  'ferrets-com': 'ferrets.com',
};
const PRIORITY = {
  'dog-com': 'Flagship',
  'fish-com': 'Tier 1',
  'lizard-com': 'Tier 2',
  'saddle-com': 'Tier 2',
  'vets-co': 'Tier 2',
  'horses-com': 'Tier 2',
  'petfood-com': 'Tier 2',
  'petfoods-com': 'Tier 3',
  'ferret-com': 'Tier 2',
  'ferrets-com': 'Tier 3',
};

function countPages(dir) {
  let n = 0;
  let entries;
  try { entries = readdirSync(dir, { withFileTypes: true }); } catch { return 0; }
  for (const e of entries) {
    const p = join(dir, e.name);
    if (e.isDirectory()) n += countPages(p);
    else if (e.isFile() && e.name === 'page.tsx') n++;
  }
  return n;
}

function replaceBlock(content, marker, body) {
  const re = new RegExp(`(<!-- ${marker}:start -->)[\\s\\S]*?(<!-- ${marker}:end -->)`);
  if (!re.test(content)) {
    console.warn(`marker "${marker}" not found`);
    return content;
  }
  return content.replace(re, `$1\n${body}\n$2`);
}

const counts = APPS.map(app => ({
  app,
  count: countPages(join(ROOT, 'apps', app, 'src', 'app')),
}));
const total = counts.reduce((s, c) => s + c.count, 0);

const dashboardBody = [
  `**${total} pages across ${APPS.length} sites**`,
  '',
  '## PAGES',
  counts.map(c => `${c.app}: ${c.count}`).join(' | '),
  '',
  '_Auto-generated by `scripts/dashboard.mjs`. Edit the script, not this block._',
].join('\n');

const readmeIntroBody = `**${total} pages** across ${APPS.length} sites: ${APPS.map(a => DOMAIN[a]).join(' · ')}`;

const readmeTableBody = [
  '| Site | Domain | Pages | Priority |',
  '|------|--------|-------|----------|',
  ...counts.map(c => `| ${c.app} | ${DOMAIN[c.app]} | ${c.count} | ${PRIORITY[c.app]} |`),
].join('\n');

const dashPath = join(ROOT, 'DASHBOARD.md');
const readmePath = join(ROOT, 'README.md');

let dash = readFileSync(dashPath, 'utf8');
dash = replaceBlock(dash, 'pagecount', dashboardBody);
writeFileSync(dashPath, dash);

let readme = readFileSync(readmePath, 'utf8');
readme = replaceBlock(readme, 'pagecount-intro', readmeIntroBody);
readme = replaceBlock(readme, 'pagecount-table', readmeTableBody);
writeFileSync(readmePath, readme);

console.log(`dashboard: ${total} total pages`);
counts.forEach(c => console.log(`  ${c.app.padEnd(12)} ${c.count}`));
