import { MetadataRoute } from 'next'

/**
 * Auto-generated by scripts/regenerate-sitemaps.mjs.
 * To refresh after adding/removing pages, re-run:
 *   node scripts/regenerate-sitemaps.mjs
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()

  return [
    { url: 'https://horses.com', lastModified: now, changeFrequency: 'daily', priority: 1.00 },
    { url: 'https://horses.com/breeds', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://horses.com/breeds/quarter-horse', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://horses.com/data', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://horses.com/disciplines', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://horses.com/disciplines/dressage', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://horses.com/disciplines/eventing', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://horses.com/disciplines/reining', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://horses.com/disciplines/show-jumping', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://horses.com/disciplines/trail-riding', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://horses.com/disciplines/western-pleasure', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://horses.com/disclosure', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://horses.com/first-horse-roadmap', lastModified: now, changeFrequency: 'weekly', priority: 0.90 },
    { url: 'https://horses.com/guides/equine-dental-care', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://horses.com/guides/equine-vaccination-schedule', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://horses.com/guides/saddle-fit-basics', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://horses.com/health/colic', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://horses.com/health/equine-ulcers', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://horses.com/reviews/best-equine-supplements', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://horses.com/reviews/best-winter-horse-blankets', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
    { url: 'https://horses.com/supplements/joint-supplements', lastModified: now, changeFrequency: 'monthly', priority: 0.70 },
  ]
}
